### ISSUE TITLE
Whirlpool distortion after a short time.

### ISSUE THREAD

**Issue by volfin** [crest-ocean/crest#154]
I've noticed this problem for a few versions now, but I figured it would work itself out. it hasn't :)

In the default Whirlpool demo, default settings, if you keep the scene running for 20 seconds or more, the center of the whirlpool starts distorting badly.
https://i.imgur.com/OG3qCes.png
This spike will grow up out of the center longer and longer until it suddenly vanishes. then 20 seconds later it all happens again.

**Comment by huwb** [comment]
Yeah thats the dynamic waves that all get advected towards the center and seem to throw a party there :). I'm not sure if there is a physics solution here but one approach would be to dampen the dynamic waves in the center by rendering a dark blob into the wave sim. I'll probably do the latter soon.

**Comment by volfin** [comment]
Awesome, thanks :)
