### ISSUE TITLE
HDRP support

### ISSUE THREAD

**Issue by huwb** [crest-ocean/crest#201]
Creating a new issue to track HDRP dev, which will likely ramp up as the LWRP version settles.

**Comment by MassDefenestration** [comment]
HDRP support is, in my opinion, the best way to attract further development and feedback.

Realistically, 2018/19 HDRP doesn't have any complete ocean shading solutions that look anything close to the competition. Unity is half a decade behind the competition both on and off the asset store.

I would be very interesting in running with Crest if HDRP support is introduced, there's a hell of a lot to love here.

**Comment by sasa42** [comment]
Same here. We reserved a lot of pixels per frame for crest hdrp. Adding the raytraced DXR reflections from the Unity Experimental DXR pre alpha would also solve all over water reflection issues toward fotoreal per default.)

**Comment by olavrv** [comment]
HDRP + DXR reflections would make Crest the absolute top water solution available on the market! We have used Ceto, Playway for a long time - and we are super excited about Crest. I think such a solution also would sell very well on the assetstore with HDRP/DXR support! Keep up the excellent work.

Feel free to check out our work: https://www.morildinteraktiv.no

**Comment by danwipf** [comment]
would love to have hdrp support!

**Comment by dongle** [comment]
Yes, would love to use this in an HDRP VR project. I appreciate all the work that has gone into this so far. Hopefully I can contribute a bit once I get more up to speed with Unity.

**Comment by huwb** [comment]
I made a channel on the discord (linked from the readme) to track progress here btw.

**Comment by urokuta** [comment]
looking forward to it!

**Comment by sbinunity** [comment]
I was surprised to see your contribution, it was so cool. In the past, I also studied real-time rendering of the ocean. I used the inverse Fourier transform to generate the waveform. To achieve its GPU version for efficiency, the interaction is difficult because there is no project to push to stop this. the study. But seeing your results today has ignited my interest in ocean rendering, and I have the urge to do something that I am very satisfied with. But unfortunately there is no support for the HDRP pipeline, I hope to support the HDRP pipeline in the future, I think there are too many people think so, the real rendering and interaction is more and more important for content creation. Please refer to https://sim.unigine.com/, this company has great technology about water, very good

**Comment by FastSkill** [comment]
Would love to see HDRP support! The ocean is amazing! great work indeed. I work mainly with HDRP and nothing I have seen done or done myself for ocean shaders is even close to comparable, so please please do make it happen.. big thumbs up!

**Comment by Gabrielkang** [comment]
Just need to put my 2 cents into the pool for HDRP support. 👯‍♂

**Comment by jesst3r** [comment]
thumbs up for HDRP, can't wait

**Comment by SpyChar** [comment]
Yes pls.

**Comment by StevenKek** [comment]
+1

**Comment by nlaha** [comment]
This would be appreciated.

**Comment by EddieSoloProjects** [comment]
+1 for HDRP. This is a must have :)

**Comment by valentinwinkelmann** [comment]
I agree. Crest absolutely needs a HDRP update. Especially since the HDRP is now officially no longer in beta.

**Comment by MrStormCoder** [comment]
+1 urgently needed

**Comment by huwb** [comment]
We're preparing the release. Should be a matter of days.

**Comment by vladakucharik** [comment]
+1 for HDRP

**Comment by huwb** [comment]
We submitted the package to the store and are awaiting feedback. I'll post back when there is news.

**Comment by AwesomeSuri** [comment]
Can't wait! Does this version also support VR?

**Comment by huwb** [comment]
We are proud to announce Crest for HDRP is now available on the Asset Store. https://assetstore.unity.com/packages/tools/particles-effects/crest-ocean-system-hdrp-164158 . The page lists requirements and other details.

The big differences to other versions of Crest are..

* Underwater effect rewritten as a more robust postprocessing effect.
* Shadowing - sharp shadowing of direct lighting only for now. Soft shadowing of the water volume is on our list.
* Ocean shader rebuilt from ground up to align with what shadergraph generates, for maximum compatibility with HDRP systems.

While we've received positive feedback from multiple rounds of testing, there will inevitably be teething issues, please bare with us while we settle it. We're offering the asset for a discounted price at the beginning while it matures.

(@AwesomeSuri we cant vouch for all VR setups, but we follow the shadergraph format closely and should work wherever normal shadergraphs work. But running HDRP in VR will want a beefy GPU..).
