### ISSUE TITLE
Execute in Edit Mode

### ISSUE THREAD

**Issue by SilverbackKarthik** [crest-ocean/crest#208]
Can we have the Ocean be generated in Edit Mode similar to Unity Particle System?

![image](https://user-images.githubusercontent.com/42980551/55348584-e031e900-548d-11e9-9c19-39a4521db8f5.png)

The reason behind this is that the project we are using this for is based on Unity Timeline and we would like to scrub the timeline in edit mode and see it with the waves. Even a low poly mesh based render would help visualize it.

I am making using of the Time Provider with the Timeline time to scrub in runtime mode now.

**Comment by huwb** [comment]
Yeah, probably. I did some experiments where i slap [ExecuteInEditMode] and set HideFlags to DontSave on the ocean components/generated GOs and it gets a bunch of the way there, but there might be a fair bit of fixup required to get all the state figured out to work in edit mode and be robust etc. I'll post back if i make progress.

**Comment by SilverbackKarthik** [comment]
Sounds great! I have been trying to work it out. This has been a most requested feature by our team do I have been trying to figure outs ways to get it working. Also, I have been trying to get Bow Wakes without having the objects move. Let me know if you have any pointers for that as well.

**Comment by huwb** [comment]
I put a bit more time into it and was surprised to see something kinda working. There are resource lifetime issues and usually some errors creep into the log (at which point i'm currently reopening the scene) but the basics seem to be there. I'd be very interested if it already works with the Timeline and what kinds of functional tradeoffs it currently has, if you'd be in a position to grab it and try it with your project? It's in the branch feature/ocean-in-edit-mode

**Comment by huwb** [comment]
Perhaps open a separate issue for bow wakes if you dont mind so we dont mix issues together. If you could outline what you're doing/what you want a bit more that would be useful.

**Comment by SilverbackKarthik** [comment]
That seems to be working better than what I thought it would.
We could make a few improvements to it and have it working in a more optimized manner.

Yes. I will create a separate Issue for the Bow Wake feature,

**Comment by moosichu** [comment]
@SilverbackKarthik are you working on this at the moment, I'm considering taking this on unless you are happy completing this. 🙂 If you've done any further work so far I am happy to take things on from there.

**Comment by SilverbackKarthik** [comment]
@moosichu Yes, I am using it in a project and trying to fix few optimization bugs. But, have not had the time to test them through. So, If you are starting to work on this, It's all yours. I would like to get updates on your work as well.

So, I guess thread could be a place to share the info.

**Comment by huwb** [comment]
@moosichu and I are focusing on other things in the short term so we're not pushing this forwards right now, but will post if we get back to it.

**Comment by moosichu** [comment]
Hi, sorry for the slow reply. I will get back to this at some point, just have a few higher priority things atm and it's been a busy couple weeks. 

The work that has been done so far (mostly by Huw) is in [this](https://github.com/moosichu/crest-oceanrender/tree/feature/ocean-in-edit-mode) branch, which I have mostly brought up-to-date with master. It still needs a fair bit of work though.

**Comment by huwb** [comment]
Merged into BIRP (master branch), will make its way into URP/HDRP in 4.3
