### ISSUE TITLE
NaNs - Flashing white circle sometimes appears when looking down into the water

### ISSUE THREAD

**Issue by ghost** [crest-ocean/crest#247]
A large white circle with a black circle in its center sometimes flashes on the screen when looking down into the water from above.

**Comment by VizzzU** [comment]
Hi ! Do you have some post effect added on cam ? I already have had some strange issues with the bloom .

**Comment by huwb** [comment]
Are you using gamma space rendering? It's not really supported unfortunately.

**Comment by drogga** [comment]
The problem went away when disabling post processing. Is Crest not compatible?

**Comment by huwb** [comment]
Are you referring in linear or gamma? The option is in the Player settings I believe. Default is gamma. Post should be fine afaik.

**Comment by drogga** [comment]
Using linear. Disabling bloom makes the flashing white circle go away, and the black circle goes away when disabling depth of field. Either this is a bug with Crest, or I'm setting this up wrong.

**Comment by drogga** [comment]
Actually, never mind. I figured out the problem through trial and error. Stop NaN propagation needs to be enabled on the post process layer.

**Comment by huwb** [comment]
Ah ok something must be generating nans. That gives me something to go on. Thanks!

**Comment by huwb** [comment]
I've not been able to reproduce this issue. I've tried with different combinations of PP effects and different example scenes.

Is someone able to send me a minimal project where this occurs?

**Comment by EliGould** [comment]
Might be the same problem as discussed on Discord today. Here is some footage of how the flickering looks for us. This seem to occur only when on the DefautLWRP instead of the CrestExampleLWRPAsset.

[FlickeringLightsBug.zip](https://github.com/crest-ocean/crest/files/3967111/FlickeringLightsBug.zip)

**Comment by EliGould** [comment]
I think it only happens when Anti Aliasing is enabled. 
![image](https://user-images.githubusercontent.com/15649355/70989955-dce69800-20c4-11ea-83a0-bd972ddfd0fa.png)

**Comment by EliGould** [comment]
I think it only happens when Anti Aliasing is enabled. 
![image](https://user-images.githubusercontent.com/15649355/70990077-14eddb00-20c5-11ea-8751-56d1aacd54ad.png)

**Comment by huwb** [comment]
Thanks - yep i can definitely see it now!! The torches also get a little crazy, but nothing like the water. Anyway hopefully this is fixable. Will post back when i have news.

**Comment by huwb** [comment]
Ok so i couldnt resist turning off material features and hacking out code and quickly narrowed it down to this line 468 of Ocean.shader. Adding `saturate()` around the exponential term sorts it:

`col = lerp(col, scatterCol, saturate(1. - exp(-_DepthFogDensity.xyz * pixelZ)));`

This would imply that pixelZ can be (large) negative when MSAA is enabled. I'm getting it straight from `LinearEyeDepth()` so i dont really know what to do with this information. Think i'll just add the `saturate()` and call it fixed.

**Comment by EliGould** [comment]
This works well for me, thank you.

**Comment by huwb** [comment]
Fix has gone live now in version 3.4.

I actually doubt its the same fix as the original bug, but its old enough that it could use a refresh if there still is an issue.
