### ISSUE TITLE
Camera underwater effect seems to break when enabling directional light shadows

### ISSUE THREAD

**Issue by Trafel** [crest-ocean/crest#256]
**Describe the bug**
The camera underwater effect seems to break

**Screenshots / video**
Shadow On : https://i.ibb.co/RS2HxmF/cctitre1.png
Shadow Off : https://i.ibb.co/QY7yKzk/cctitre2.png

**Log**
None

**Versions**
Open source master branch on Unity 2018.3.6f1

**To Reproduce**
 - Unzip project
 - Open _main_ scene in crest exemples
 - In _Ocean Renderer_ component of _Ocean_ game object check "Create Shadow Data"
 - (optional; for better visibility) _Open Ocean-Underwater_ Material and change _X_, _Y_ and _Z_ values of "Fog Density" to **0.02**
 -  In _Environment > Directional light_ gameobject change "Shadow Type" to "Hard Shadow" or "Soft Shadows"
 - Press Play and go deeper in the ocean, some strange dark artifacts will start to appear

**Platform**
 - Editor
 - Platform Windows 10

**Additional context**
None

**Comment by huwb** [comment]
Thanks, i see it. I guess this is issues in the UnderwaterCurtain.shader. I won't have time to look at this in the short term, but if someone else has time to pick this up i'm happy to talk it through. Otherwise i'll post back when i've had a run at it.

**Comment by huwb** [comment]
This should be fixed on 60cdcdccda1de4217e9c4dc0ec0a88ad910b014f . We knocked out the shadowing factor for underwater. We are looking at rebuilding the underwater effect and will see if we can reinstate shadows.
