### ISSUE TITLE
Planar reflection and skybox issue

### ISSUE THREAD

**Issue by jjxtra** [crest-ocean/crest#257]
I have a planar reflection in the default main scene. I have switched to the default Unity skybox.

There are two issues:

1- The sun is off center. You can see it move in the water as you rotate the camera.

![image](https://user-images.githubusercontent.com/1271832/57983856-7f497a80-7a13-11e9-9f9c-4a61e07855ab.png)

![image](https://user-images.githubusercontent.com/1271832/57983859-85d7f200-7a13-11e9-84d7-7f175cbd2787.png)

2- As sun drops below horizon, it continues to light the water from underneath causing a strange green appearance. I even tried adding a large cube underneath everything as a double sided shadow caster but it had no effect.

![image](https://user-images.githubusercontent.com/1271832/57983875-adc75580-7a13-11e9-9ef9-be14d72053bb.png)

**Comment by VizzzU** [comment]
Can you try to follow the form it will be easier to reproduce the bugs . (Unity version , platform , how to reproduce etc ... )
In unity 2019.1 , 2018 , with LWRP and standard version i have no reflection issues . Regards : )

**Comment by jjxtra** [comment]
All Unity version, standard pipeline. Can reproduce with my pull request repo.

**Comment by huwb** [comment]
Thanks for this

number 1 - yeah i had a feeling this might be off but needed someone to give me a push. thanks i'll let you know if i can figure this out

number 2 - think i'm going to play the "its a feature" card again.. i thought about this and it affects all the other objects in the scene, not just the ocean. so i feel its not an ocean specific problem (even if it looks particularly crazy). i think the solve should be to scale the intensity down and/or switch to another primary moon light. let me know what you think.

**Comment by jjxtra** [comment]
It fixes the sun positioning problem yes!

**Comment by huwb** [comment]
Thanks all, glad to see this closed.

By the way if the second issue is a legit issue please respond to the notes above as we need more information.
