### ISSUE TITLE
Shoreline Transparency/Alpha Fade?

### ISSUE THREAD

**Issue by LIVENDA** [crest-ocean/crest#262]
How can we implement or best method to achieving shoreline fading when intersecting with the terrain ?  

![Shoreline_fade](https://user-images.githubusercontent.com/8242904/58637751-6190e500-8332-11e9-97a5-85e04473f227.jpg)

Thanks!

**Comment by Midda-C** [comment]
Yeah, a depth-fade or something (like soft-intersecting on particles) parameter on the material would help a lot.

**Comment by LIVENDA** [comment]
> Yeah, a depth-fade or something (like soft-intersecting on particles) parameter on the material would help a lot.

Certainly would, I see this as a very important addition as the rest of the system looks great. I also like to congratulate the developer on this implementation, high performance, looks phenomenal and overall very flexible.

**Comment by huwb** [comment]
There are mechanisms to address the two above:

* shadowing
* shoreline foam min depth

I'm not sure i'm comfortable adding a generic alpha fade to the material as i'm trying to keep it physicsbased where possible. I could however give pointers on where to add a fade, and it would be good to see/explore the benefits as it might be worth taking artistic license on this and implementing it in crest.

**Comment by andgeno** [comment]
Could you please give us an concrete example of the two ways you suggested?

I can't find a material for shoreline foam. The shadowing feature did nothing or not enough to fix the intersection to become less visible for me.

**Comment by huwb** [comment]
Finally tried this.

https://github.com/crest-ocean/crest/tree/feature/fade-reflection-at-shore

It reuses the same parameter that fades the foam near the shore: Shoreline Foam Min Depth

Let me know what you think.

**Comment by huwb** [comment]
Hi guys, any thoughts on the above?

**Comment by huwb** [comment]
I cleaned up the test branch and merged it into master

#353
