### ISSUE TITLE
Dynamic water simulation is time independent

### ISSUE THREAD

**Issue by UnknownSoldier1** [crest-ocean/crest#263]
Hello,

I have a game where the player can speed up or pause the game simulation and I wrote a custom time provider that applies that to the water as well. As it appears though, this does not affect the dynamic wave simulation and therefore waves created by boats are still simulated, even if my time provider doesn't advance. Also, when my time provider advances faster than normal the dynamic waves also don't simulate faster as they should.

I don't know how hard it is to fix or if this is actually desired behaviour but from my perspective this probably is a bug.

**Comment by huwb** [comment]
If i set time.timescale to 0 then it seems to freeze the dyn waves for me.  How are you controlling the time?

(unfortunately it seems that if i decrease and icnrease timescale quickly then it adds tons of acceleration to the sim for some reason :/ so thats a bug)

**Comment by UnknownSoldier1** [comment]
I'm using this piece of code to do this:

`public class WaterTimeSync : TimeProviderBase
    {
        public override float CurrentTime => time;

        private float time;

        private void Update()
        {
            time += Time.deltaTime * GameManager.current.SpeedManager.GameSpeed;
        }
    }`

You mentioned time.timescale? Is that an independent thing from the time provider?

**Comment by huwb** [comment]
Oh right i see the problem - the sim delta time is driven by unity's delta
time.

            GetSimSubstepData(Time.deltaTime, out numSubsteps, out
substepDt);

I guess ideally the time provider would provide a time and a delta time.
I'd be interested to see a PR with this change if you feel up for trying
it. Otherwise i'll add it to my list and post back when i've had a chance
to look at it.

The workaround for now might be to use Unity's Time.timeScale  for slowing
down time as the sim will repsond to this..

**Comment by UnknownSoldier1** [comment]
Unfortunately using Time.timeScale won't fix my issue as it slows down everything, including UI etc. That said, it's not an urgent fix and I can certainly wait for a fix for this, so tackle this issue when you have the time.

**Comment by huwb** [comment]
In #295 i add delta time to the time provider and this is merged into master now.
