### ISSUE TITLE
Issue with Feed Velocity To Extrude.  Distortion goes nuts when camera is near.

### ISSUE THREAD

**Issue by holdingjason** [crest-ocean/crest#274]
When a camera is in certain LOD levels i.e right above the boat in the boat three demo (med boat) you can get a increase of wave distortion that keeps growing over time.  Flipping to another camera shot along side of the boat pulled back to a different LOD level cause the wave distortion being generated to appear as I would expect.  Going back to the original shot and it looks normal for a second and then grows out of control again.  See attached for boat settings.

Version is built in latest code on github from main branch.

Windows

[movie1.zip](https://github.com/huwb/crest-oceanrender/files/3307740/movie1.zip)
![unknown](https://user-images.githubusercontent.com/42001313/59797001-91793b80-9293-11e9-8bbd-a6cb75234c33.png)

**Comment by huwb** [comment]
Generally the lods are dependant on camera position as you know (and as any view dependent level of detail is, by definition). Here the dynamic wave sim interaction is not behaving well when it overlaps all LODs vs when it only overlaps some of them. I do check how many lods its overlapping and renormalize the input, but its probably not enough. What is needed here is a more nuanced way of distributing the energy over the overlapping LODs. Unfortunately this is probably unlikely to bubble up to the top of my todo list any time soon. Is it workable if the interaction strength is dialled down? If not i can probably give starting points for what to modify to make it LOD out more gracefully.

**Comment by huwb** [comment]
#295 should sort this. there is a setting in teh dynamic wave sim (gravity) that speeds them up, which should avoid this kind of weirdness. also i changed the way interactions are pushed into sim slightly which should help.

You will however need to retweak the settings as the sim changed quite a lot. Its worth getting a separate new copy of crest and taking a look there.
