### ISSUE TITLE
Move public crest repositories and assets to an organisation

### ISSUE THREAD

**Issue by moosichu** [crest-ocean/crest#286]
See: https://help.github.com/en/articles/transferring-a-repository

# Problems this would solve

As Crest grows and has more users, we may want to create more repositories to seperate-out examples, create a website, create an image gallery and more. Furthermore, being able to have a [/crest-ocean](https://github.com/crest-ocean) as the one-stop-shop for everything crest could help simplify being able to find Crest on GitHub.

# What are the risks associate with doing this?

Obviously changing the location of something like this on the web could potentially be a very painful experience if it broke everyone's setup and made it difficult to find the new repository.

Fortunately, GitHub have done a lot to ensure that it [shouldn't be an issue](https://help.github.com/en/articles/transferring-a-repository). Therefore everyone will still be able to use crest as they currently do, without interuption to their workflows: all issues, pull requests and the wiki will be preserved as-is. Going to this URL will redirect you to the new repo, and pulling/pushing to the old URL will still work without any issues.

I've tested this myself with https://github.com/moosichu/test-repo-transfer, which now redirects to [crest-ocean/test-repo-transfer](https://github.com/crest-ocean/test-repo-transfer).

I believe private branches are stored in a seperate repository already (checking with @huwb), so there won't be any issues there either.

**Comment by moosichu** [comment]
Also to make it clear, the new organisation will likely be: https://github.com/crest-ocean, with the repository being moved to [https://github.com/crest-ocean/crest](https://github.com/crest-ocean). I anyone has any opinions aobut that please do let us know! :)

**Comment by huwb** [comment]
Thanks Tom. Moved to https://github.com/crest-ocean/crest
