### ISSUE TITLE
PS4 doesnt match PC

### ISSUE THREAD

**Issue by dizzy2003** [crest-ocean/crest#290]
Just did a quick test on ps4 of commit 087c6c498f54f5779e29a7e951675951a4d377fc

![image](https://user-images.githubusercontent.com/15023384/60853512-baac3c80-a23f-11e9-9a06-b44fcc8554ef.png)

Note this is standard main scene but I did tick Procedural SkyBox enable, also does include the fix to ps4 to use the copied depth texture (which may now need more work?)

 The debug textures on the right also show grid like circular dots that I dont see on pc.

The foam isnt showing which could be depth cache issues?

(PC for comparison from editor)
![image](https://user-images.githubusercontent.com/15023384/60853965-b2550100-a241-11e9-881b-b3e4529d8afc.png)

**Comment by dizzy2003** [comment]
A bit more info.

Changed the ocean shader to just render the foam value o.foam_screenPos.x also enabled all the overlay info

![image](https://user-images.githubusercontent.com/15023384/60861261-2d77e080-a25d-11e9-8db3-13571e913402.png)

PC Editor for comparison 

![image](https://user-images.githubusercontent.com/15023384/60861300-4aacaf00-a25d-11e9-98b3-1b6eb0f6f687.png)

You can see the weird grid dots on the Sea Floor depth, I drew the sea floor depth render texture on screen (output from the islanddepthcache camera target texture) and it was the same on pc and ps4, but maybe that isnt being used anymore..

also the shadows are totally black on the ps4 debug output.

**Comment by dizzy2003** [comment]
![image](https://user-images.githubusercontent.com/15023384/60866672-4e93fd80-a26c-11e9-8ea1-e1408a601c8c.png)

Making LodDataMgrSeaFloorDepth useGeometryShader return false seems to have fixed ps4.

**Comment by moosichu** [comment]
Good to know. It seems like the issues with the depth geometry shader were propagating to the other lods. Whilst it might be worthwhile to get it working on PS4, I think for now we will just disable it. Glad the solution was simple!

**Comment by moosichu** [comment]
Do you get any errors in the logs about shadows out of interest, I noticed that they aren't working either. If there are compilation issues that would be especially useful to know, as we had some on Vulkan that we were able to fix.

**Comment by dizzy2003** [comment]
re shadows:

No compile errors or warnings in any shaders
Nothing in the log :(

**Comment by moosichu** [comment]
Just created PR #292, without hardware to test on this is probably the best solution for now.

**Comment by huwb** [comment]
thanks @dizzy2003 

re copied depth, i guess you mean this: https://github.com/crest-ocean/crest/issues/193 . i don't think you/I ever put code into crest for this - although i might be misremembering. i'd guess this code is not included in crest.

is the camera set to deferred rendering? on the built-in pipeline shadows don't work when camera is deferred at the moment
https://github.com/crest-ocean/crest/issues/198

**Comment by moosichu** [comment]
Going to close this issue, we can create a seperate issue for PS4 shadows if that does turn out to be its own thing.
