### ISSUE TITLE
Ocean lighting issues when using Enviro

### ISSUE THREAD

**Issue by andgeno** [crest-ocean/crest#294]
**Describe the bug**
I'm using Crest Ocean and Enviro in my project and noticed that the rendered ocean more or less ignores lighting. This results in a way too bright ocean in dark/night scenes.

**Screenshots / video**
These are very helpful to understand and diagnose issues.

Scene at day
![image](https://user-images.githubusercontent.com/2432608/61088513-ca42a580-a438-11e9-8688-7cc6ed58a548.png)

Scene at night
![image](https://user-images.githubusercontent.com/2432608/61088579-fb22da80-a438-11e9-8cf5-d69d16527e9a.png)

**Log**
No errors or warnings in the logs.

**Versions**
Unity: 2018.4.3f1 Built-in Render Pipeline
Plugin: Crest Ocean (Commit dcdbe0a56430fa11a39eabe739f175dcf04cb7d4)
Plugin: Enviro - Sky and Weather 2.1.5

**To Reproduce**
- Import Enviro and Crest Ocean in a new project
- Create a new Unity scene
- Create an empty GameObject and add component `EnviroSkyMgr` to it
- At this very moment (without going into Play Mode) Enviro has permanently modified the scene lighting settings (`Lighting` tab). I think it it `RenderSettings.ambientMode`. 

My camera uses deferred rendering in linear color space.

Here are two side-by-side screenshots of the Crest example scene (left) and my scene (right):
![image](https://user-images.githubusercontent.com/2432608/61089029-1b06ce00-a43a-11e9-8b02-fe75c7d147b0.png)

I was able to lower the setting `Environment Lighting | Intensity Multiplier` in the scene lighting settings to make the ocean appear darker. So I tried the same in my scene but I can't do that because the settings is gone/replaced with this HDR color picker that also seems to be permanently controlled by Enviro and thus cannot be changed.

**Platform**
Issue happens in-editor.
OS: Windows 10

**Comment by huwb** [comment]
hi @andgeno , thanks for posting this.

the userguide has a section on Reflections. i just added a paragraph to the end of this section which describes a useful debugging/troubleshooting strategy - adding a test object and verifying it receives reflections. could you let me know if it makes sense and try it out and attach a screenshot?

https://github.com/crest-ocean/crest/blob/master/USERGUIDE.md#reflections

**Comment by VizzzU** [comment]
You just have to put the reflection probe on standalone in the reflection tab . It add the dynamic clouds and handle the light but is a bit memory consuming if you put everything in ultra.

**Comment by VizzzU** [comment]
![2019-07-13 21_31_42-Window](https://user-images.githubusercontent.com/45937523/61175810-e91a7680-a5b5-11e9-91fd-b1c66e9a99bd.jpg)

**Comment by andgeno** [comment]
> 
> 
> hi @andgeno , thanks for posting this.
> 
> the userguide has a section on Reflections. i just added a paragraph to the end of this section which describes a useful debugging/troubleshooting strategy - adding a test object and verifying it receives reflections. could you let me know if it makes sense and try it out and attach a screenshot?
> 
> https://github.com/crest-ocean/crest/blob/master/USERGUIDE.md#reflections

Hi @huwb, thanks for checking this. I've added a sphere to the scene and this is how it looks like at day and night.

![image](https://user-images.githubusercontent.com/2432608/61176041-2bde4d80-a5ba-11e9-9ecd-157570f66537.png)

![image](https://user-images.githubusercontent.com/2432608/61176043-4a444900-a5ba-11e9-8939-16151bbb2b7b.png)

Here is my setup:
![image](https://user-images.githubusercontent.com/2432608/61176059-9c856a00-a5ba-11e9-9429-4e1dad917dac.png)

Is the reflection probe really needed? I think I did not find any in the Crest example scene.

In the screenshot at night I can clearly see that the ocean is lit as bright as in the scene itself.

**Comment by andgeno** [comment]
> 
> 
> You just have to put the reflection probe on standalone and add update reflection in the reflection tab . It add the dynamic clouds and handle the light but is a bit memory consuming if you put everything in ultra.

What do you mean by "on standalone"?

**Comment by andgeno** [comment]
@VizzzU Could you send me your test scene please? I think that would help me so I can compare what I am missing.

**Comment by VizzzU** [comment]
![step1](https://user-images.githubusercontent.com/45937523/61176249-ea4fa180-a5bd-11e9-9f0d-ae71d158a955.jpg)
![step2](https://user-images.githubusercontent.com/45937523/61176251-f176af80-a5bd-11e9-9332-f631952b0bf1.jpg)
![step3](https://user-images.githubusercontent.com/45937523/61176256-081d0680-a5be-11e9-8e4f-d7ab1c9a6529.jpg)
![step4](https://user-images.githubusercontent.com/45937523/61176259-0a7f6080-a5be-11e9-8d3a-632ad7556009.jpg)


Do not forget to build at least a lightmap in window/rendering/lightingSettings or o put it on auto generate ( to feed light to ocean at startup then the probe will do the job each update

**Comment by VizzzU** [comment]
Hae fun Night and days !

**Comment by andgeno** [comment]
Thank you so much for all the details including the fog.
I was able to get the ocean look correctly in an empty scene. 😀 

It looks like there is something wrong with my game scene I was testing the settings with.
I'm still debugging it to find out what really prevents the ocean from looking correctly.

**Comment by andgeno** [comment]
@VizzzU Could post step by step instructions for adding fog? I don't see how this would work similar to Azure. I included `EnviroFogCore.cginc` in `Ocean.shader`. The included file has a `TransparentFog` method but I'm not sure if this is what i should call and then ... how.

**Comment by VizzzU** [comment]
My bad , applyFog is for Azure , you are right it is the transparentFog method . Take a look at the Enviro alpha blended particle shader , this is exactly what you need .
I think vondox will include an integration in his future Enviro update .

**Comment by huwb** [comment]
Cool, sounds like I can close this
