### ISSUE TITLE
RenderAlphaOnSurface pops on large scales

### ISSUE THREAD

**Issue by babon** [crest-ocean/crest#300]
https://www.youtube.com/watch?v=efK4QDkJIzg
I wanted to use the texture projecting feature to indicate a circle play area inside the ocean
Some waves seem to pop through the texture when you set the scale of RenderAlphaOnSurface to a large value.
https://i.imgur.com/xP3j33A.jpg

_________
I replaced the default untiy Plane in the mesh filter with a much higher-poly one, that decreased the popping by about 70%
https://i.imgur.com/xSjm96e.jpg
but thats a lot more polygons, if i want to have a 1500x1500 texture projection, will i have to use a Plane with almost the same polygon density as the rendered ocean itself?
https://i.imgur.com/21lo5SE.jpg

**Comment by babon** [comment]
I replaced the default untiy Plane in the mesh filter with a much higher-poly one, that decreased the popping by about 70%
https://i.imgur.com/xSjm96e.jpg
but thats a lot more polygons, if i want to have a 1500x1500 texture projection, will i have to use a Plane with almost the same polygon density as the rendered ocean itself?
https://i.imgur.com/21lo5SE.jpg

**Comment by huwb** [comment]
hi there,

yeah this doesnt scale well for large areas - it needs triangles that match the smallest triangles in the ocean which result in a lot of tris. i don't think the solution in crest is a good fit here.

i think a much more robust system would be based on Projectors. I'm not quite sure what would be required to project onto the ocean surface and what the tradeoffs will be.

i'm closing this as i don't see a way to fix this unfortunately, but will get notifications if you reply so we can continue to discuss.
