### ISSUE TITLE
Showcase Of Ships & Scoundrels

### ISSUE THREAD

**Issue by JJarvis89** [crest-ocean/crest#304]
Hey,

This is not really an issue, but I'd like to show you a game I have been working on at Korion for quite some time which makes use of Crest:

https://www.youtube.com/watch?v=zCeK_Kdxqa0&feature=youtu.be

An Early Access version of the game will become available on Steam in August. 

We'd greatly appreciate it if this could be included in the Showcase Gallery!

**Comment by moosichu** [comment]
Hey @JJarvis89, 

That really inspiring to see! There's some great stuff in there. 

We are currently preparing for @huwb to present Crest at the 'Advances in Real-Time Rendering in 3D Graphics and Games' course at Siggraph next month. As part of that we are putting together a Crest 'sizzle reel' to show-off what people have achieved, and it would be awesome to have some high-quality raw footage from 'Of Ships & Scoundrels' to put in there if you are happy for us to do so (and upload online at a later-date). 

We also have a discord server at https://discord.gg/g7GpjDC, which you can use to DM me `@Moosichu`. We would need to have any footage today if possible, but it would be great if we could put some things in from the game.

Could we also please add the trailer to the [Showcase Gallery](https://github.com/crest-ocean/crest#showcase-gallery)?

Cheers,

Tom

**Comment by moosichu** [comment]
Also, a big thank you for sharing this!

**Comment by moosichu** [comment]
If you could also look at #305 and tell is if you are happy with that change. 👍 That will add it to the showcase gallery.

**Comment by JJarvis89** [comment]
@moosichu Thanks for the quick reply. I'll check with the team if we can quickly provide some raw footage!

Thanks,
James

**Comment by moosichu** [comment]
Even a link to a download of the trailer without YouTube compression would be perfect. Just whichever is easiest.
