### ISSUE TITLE
ChangeRequest: FloatingObjectBase should expose velocity as a property instead of RigidBody

### ISSUE THREAD

**Issue by ncthbrt** [crest-ocean/crest#308]
Not all games rely on Unity's builtin rigidbody physics. For example the prototype I'm currently building relies on "KinematicCharacterController" which uses capsule casts and `Compute Penetration` to provide collision resolution. I'd like to be able to make use of `FloatingObjectBase` without having to rely on the rigidbody system. 

I've analyzed usage of `FloatingObjectBase`, and rigidbody is not required to be a public property of `FloatingObjectBase` -- only velocity is used. 

I'd thus like to request that FloatingObjectBase remove `RB` as an abstract property, and instead add a `Velocity` accessor. Children of `FloatingObjectBase` will still retain the `RB` property, and will simply need to add `public Vector3 Velocity => RB.velocity;`

**Comment by huwb** [comment]
Good shout, created above PR

**Comment by huwb** [comment]
Merged in

**Comment by ncthbrt** [comment]
Thanks Huw!
