### ISSUE TITLE
Crest-ocean only renders in left eye when Single Pass Instanced selectd in VR 

### ISSUE THREAD

**Issue by PJ373** [crest-ocean/crest#312]
Bug Description:
For the Oculus Rift, when I switch from single pass to single pass instanced for a LWRP VR Unity project in Unity 2019.1.  Crest only renders in the left eye.  It does not render in the right eye.  (Note: Unity terrain has the same issue. I reported it and it was reproducable by them and is an open bug Issue ID: 1170619 submitted July 19, 2019.)

![image](https://user-images.githubusercontent.com/40904467/62415079-47a1a600-b5f2-11e9-8ef0-c2d876ad9bd9.png)

**Logs**
No errors in the log.

**Versions**
LWRP 5.16.1
 Unity 2019.1.13f1

**To Reproduce**
Open a new project using the Unity LWRP VR template.   Import open Crest demo Main scene.
Switch your LWRP VR project from single pass to single pass instanced in the project player settings.  Then play.  Crest and if you have Unity terrain will only render in the left eye.

**Platform**
Windows and Oculus Rift

**Comment by huwb** [comment]
Thanks for posting this. I think the solution is to enable instancing, which is not a bad thing to support anyway, so i think we should look at this. Will post with progress.

**Comment by gosolo2** [comment]
Default Renderer (ForwardRenderer)
HDR - Use Pipeline Settings
MSAA - Use Pipeline Settings
Target Eye - Both

**Comment by moosichu** [comment]
We don't support instanced rendering yet, but the other VR options should work.

**Comment by TeorikDeli** [comment]
So, HDRP recommends (idk if it only supports this) to use Single Pass Instanced. Is HDRP version of Crest also doesn't support SPI? I am going to purchase it today, if it supports now or very soon. We're rewriting a project from scratch for HDRP, and we were using Crest in that project. It is the most powerful solution for Unity and I want to use it in HDRP too =/

**Comment by daleeidd** [comment]
@TeorikDeli Crest HDRP does support Single Pass Instanced. There is a couple of issues with underwater left to resolve.

**Comment by yutokun** [comment]
Thank you for the awesome ocean asset. I was impressed so much!

Unity will drop support for legacy VR support and migrate to XR Plug-in Management in 2020.1. Crest Ocean URP does only support Single Pass in VR, but XPM does not support it. Is there plans to support Single Pass Instanced in URP?

I'm using
Unity 2019.4.2f1
URP 7.3.1
Crest Ocean System URP 4.3

Multi Pass
![screenshot 1594034895](https://user-images.githubusercontent.com/8219697/86588903-9193c880-bfc7-11ea-839e-a4f39aba5cad.jpg)

Single Pass Instanced
![screenshot 1594034945](https://user-images.githubusercontent.com/8219697/86588919-98bad680-bfc7-11ea-9138-b1be593ab4d3.jpg)

**Comment by daleeidd** [comment]
@yutokun Crest 4.4 was submitted the other day with Single Pass Instanced support for URP

**Comment by yutokun** [comment]
@daleeidd Great! Thanks for told me that. I'm looking forward to it.

**Comment by daleeidd** [comment]
4.4 has been released. Single Pass Instanced is supported across all pipelines now. Open an issue if you see any problems.

**Comment by RoadwayVR** [comment]
For anyone who has the same problem, I created the following Tutorial Video:

https://youtu.be/JiCJN8EvoCA
