### ISSUE TITLE
Curtain fog density seems to disappear at lower depths.

### ISSUE THREAD

**Issue by holdingjason** [crest-ocean/crest#318]
This entire sequence was recreated in the latest master, standard demo.

1.  Density of fog effect on objects seems to clear up the deeper you go.
2.  This effect can also be noticed on terrain etc as well as objects.
3.  Darkening effect as you go deeper does not appear to effect things like terrain etc near camera.

Near surface see the nice blue haze you have on the crab, fish and especially the terrain.
https://cdn.discordapp.com/attachments/568134291540803595/610571334275170326/unknown.png

Still some of that blue haze but now it seems to have less impact on the crab and terrain.  Also no real change in the darkness of the terrain and crab.
https://cdn.discordapp.com/attachments/568134291540803595/610571462235127809/unknown.png

Deeper still no haze at all on the crab or terrain.  Lighting in the distance is now totally dark as it should be.  Lighting however on the terrain and crab is wrong since we should be dark here as well, even without the haze.  In this situation however we do need haze since I would want to bring down a light source so we could see, I would want it to then look like the first shot with the blue haze.
https://media.discordapp.net/attachments/568134291540803595/610571704153931785/unknown.png?width=1076&height=527

**Comment by holdingjason** [comment]
Just screwing around with this.  I found this code in the oceanemmisive shader.  This is where we check the camera depth and end up going dark at somepoint.  However this also completely eliminates the haze effect since the color drops out completely.  Ambient Light and light from the directional source are still lighting the scene so that is why we get light on the terrain and objects etc.  I can replicate what I want by limiting camDepth to say no more then 10 or so and then adjusting the ambient/directional light source in code to slowly darken them.  This works for the most part however if I shine a spot light at that point (or I am guessing a point light) it does not pick up any of the scattering effect but looks crystal clear.

	if (i_outscatterLight)
	{
		half camDepth = max(_OceanCenterPosWorld.y - _WorldSpaceCameraPos.y, 0.0);
		
		if (i_underwater)
		{
			col *= exp(-_DepthFogDensity.xyz * camDepth * DEPTH_OUTSCATTER_CONSTANT);
		}
	}

**Comment by holdingjason** [comment]
Further thinking on this.  I don't think we want the curtain to go to far into dark etc.  This won't work with other lighting techniques ala spot light etc without adding that lighting to the curtain as well so it mixes correctly and keep it hazy at a minimum with a min color scattering.  Just tossing around random thoughts after playing with the shader.

**Comment by holdingjason** [comment]
So I can get the results I want more or less by locking camera depth to 0 and then using a script to lower ambient and directional lighting over time as I go deeper.  This gives me the results I want.  My guess is there is some wiggle room at the surface + 10 meters or so that would work better so perhaps doing the camDepth calc up to a min point and then not letting it get above 10 or something might work.  Not sure so would like your thoughts.

	if (i_outscatterLight)
	{
		half camDepth = max(_OceanCenterPosWorld.y - _WorldSpaceCameraPos.y, 0.0);
		
		camDepth = 0;
		
		if (i_underwater)
		{
			col *= exp(-_DepthFogDensity.xyz * camDepth * DEPTH_OUTSCATTER_CONSTANT);
		}
	}

**Comment by woistjadefox** [comment]
Hi there!
A user on discord has also discovered that bug a while a go and found a workaround:
-------
Just passing this along since @Goran was asking about how we ended up handling those skirt issues and underwater lighting darkening over time.  Maybe @Tom Read Cutting and @Huw Bowles have some better ideas but it does work.  You basically have to kill the scatter depth option and modify the subsurface stuff a bit so you dont totally lose the cool effect while looking up at the surface.
#if _SUBSURFACESCATTERING_ON
    {
#if _SUBSURFACESHALLOWCOLOUR_ON
        float shallowness = pow(1. - saturate(depth / _SubSurfaceDepthMax), _SubSurfaceDepthPower);
        half3 shallowCol = _SubSurfaceShallowCol;
#if _SHADOWS_ON
        shallowCol = lerp(_SubSurfaceShallowColShadow, shallowCol, shadow);
#endif
        col = lerp(col, shallowCol, shallowness);
#endif

        // light
        // use the constant term (0th order) of SH stuff - this is the average. it seems to give the right kind of colour
        col *= half3(unity_SHAr.w, unity_SHAg.w, unity_SHAb.w);

        // Approximate subsurface scattering - add light when surface faces viewer. Use geometry normal - don't need high freqs.
        half towardsSun = pow(max(0., dot(i_lightDir, -i_view)), _SubSurfaceSunFallOff);
        half3 subsurface = (_SubSurfaceBase + _SubSurfaceSun * towardsSun) * _SubSurfaceColour.rgb * _LightColor0 * shadow;

        if (!i_underwater)
            subsurface *= (1.0 - v * v) * sss;
        else
            subsurface = (_SubSurfaceBase + (_SubSurfaceSun * 0.35) * towardsSun) * _SubSurfaceColour.rgb * _LightColor0 * shadow;

        col += subsurface;
    }
#endif // _SUBSURFACESCATTERING_ON

    // outscatter light - attenuate the final colour by the camera depth under the water, to approximate less
    // throughput due to light scatter as the camera gets further under water.
    if (i_outscatterLight)
    {
        half camDepth = max(_OceanCenterPosWorld.y - _WorldSpaceCameraPos.y, 0.0);

        camDepth = min(camDepth, 5);

        //camDepth = 1;

        if (i_underwater)
        {
            //col *= exp(-_DepthFogDensity.xyz * camDepth * DEPTH_OUTSCATTER_CONSTANT);
        }
    }

    return col;
}
Then you manage all lighting etc yourself.

**Comment by woistjadefox** [comment]
Sorry, couldn't manage to get that freakin' formatting right in the comments. What a mess!

**Comment by huwb** [comment]
Thanks both, sorry we haven't been able to dig into this, has been a very busy time for us. We will get around to it at some point.

**Comment by huwb** [comment]
This is resolved by #428. Got there eventually :).
