### ISSUE TITLE
Setting Ocean To A Height of 450 Stops Waves

### ISSUE THREAD

**Issue by holdingjason** [crest-ocean/crest#324]
Using Demo project out of the latest build.

Move ocean object to a y > x not sure what the limit is that starts showing the problem but I do know 450 works.  Waves etc do not really work anymore.

Setting it back to 5 and the ocean looks fine.

**Comment by huwb** [comment]
Good find. The referenced commit 568aa35 should sort it. I'll post back when its been merged in.
