### ISSUE TITLE
Height Sampling To Soon Stops returning proper height info.

### ISSUE THREAD

**Issue by holdingjason** [crest-ocean/crest#325]
Using Demo from latest build that includes the rowboat or you can add the rowboat prefab that has the BoatProbes script.

Move RB getcomponent to awake from start.

Call FixedUpdate once form awake.  System will only return 5 forever after that in FixedUpdate calls which is the height of the Y pos for the ocean.  

Also if you do not do the fixedupdate call so just setting everything back to default Demo with no script changes if you debug out the first x calls to fixedupdate you will notice you will get back a 0 for the height queries for the first few frames.  So again some timing issue is going on here that could potentially cause issues depending on what your doing with that height info.  So we need someway to know that the system is ready because making these bad calls.  

You can also add the following code to OceanRenderer.cs for ease.  Call this in any Awake function will also lock up everything.

        SamplingData _samplingData = new SamplingData();

        public float GetWaterHeightAtPosition(Vector3 position)
        {
            float height = 0;
            var r = transform.lossyScale.magnitude;
            var collProvider = OceanRenderer.Instance.CollisionProvider;
            var rect = new Rect(new Vector2(position.x - r, position.z - r), 2f * r * Vector2.one);

            if (collProvider.GetSamplingData(ref rect, 2f * r, _samplingData))
            {
                var pos = position;
                collProvider.SampleHeight(ref pos, _samplingData, out height);
                collProvider.ReturnSamplingData(_samplingData);
            }

            return height;
        }

**Comment by holdingjason** [comment]
So for the 2nd issue where we just return some empty stuff the first few calls I see we are dropping into this code in boatprobes.  So getting the   // No collision coverage for the sample area, in this case use the null provider.

So not able to yet get sample data so would this be the best way to check for system init or something better?

        if (!collProvider.GetSamplingData(ref thisRect, _boatWidth, _samplingData))
        {
            // No collision coverage for the sample area, in this case use the null provider.
            collProvider = CollProviderNull.Instance;
        }

**Comment by huwb** [comment]
Thanks for this.

Looking through the code, the collision system doesn't init in time, and ends up generating a Null Collider which always gives sea level. In a447e03 I've added an error to catch this so it doesnt silently fail and give nonintuitive results.

Regarding the second separate issue about missing collision data, yes you can sample that function to check if the collision data has returned from the GPU yet or is still in transit. This is a characteristic of the system when using GPU collision data.
