### ISSUE TITLE
Foam/Wave tiling can be seen from above

### ISSUE THREAD

**Issue by RGharsunc** [crest-ocean/crest#331]
Is there a way to change size of the LOD for wave/fom for spectrums, the tiling can be seen even if the waves are relatively small and little or no foam is generated.
Basically we would want to get rid of the square shaped area of single spectrum.
![image](https://user-images.githubusercontent.com/30415357/63595773-ccb52500-c5ca-11e9-8089-653cb701ada3.png)

**Comment by huwb** [comment]
The square shape is a "feature" of the system, but if there is foam and waves distributed across the lods I usually find the shape is hidden enough, like in the example content. However it's possible to for it to look very obvious if you have full foam in one Lod and none in the next as in your screenshot.

**Comment by RGharsunc** [comment]
Thanks for the response!
Can we change the size of the square ? 
What if i want small waves affect all LODs.

**Comment by huwb** [comment]
You can increase the Lod resolution parameter on the ocean renderer script
which will mean there is another resolution to store these small waves over
a larger range. This will however add cost so with keeping an eye on frame
rate.

Only rendering small waves near the viewer is precisely what makes crest
efficient.
