### ISSUE TITLE
Bugs on opengl

### ISSUE THREAD

**Issue by minggoddess** [crest-ocean/crest#336]
Hi, Huw Bowles

Thank you for your open source commitment of Crest.

There are some bugs on opengl and gles after turning off collision. I fixed them up.
1. No gerstner wave generated.
         add 		Cull off   in AnimWavesGerstnerBatch.shader
2.Another Jitter when camera moves
         flip y in vertex shader of AnimWavesGerstnerBatch.shader 
#ifdef UNITY_UV_STARTS_AT_TOP
				float2 worldXZ = LD_0_UVToWorld(input.uv);
#else
				float2 worldXZ = LD_0_UVToWorld(float2(input.uv.x, 1 - input.uv.y));
#endif

**Comment by huwb** [comment]
Nice to hear from you @minggoddess , thanks for that!

Re 1, this seems to be already present in the latest version. Are you on an older version? Just checking.

Re 2, I've currently got this

``
			Varyings Vert(Attributes input)
			{
				Varyings o;
				o.positionCS = float4(input.positionOS.xy, 0.0, 0.5);

#if UNITY_UV_STARTS_AT_TOP // https://docs.unity3d.com/Manual/SL-PlatformDifferences.html
				o.positionCS.y = -o.positionCS.y;
#endif

				float2 worldXZ = UVToWorld(input.uv);
				o.worldPos.xy = worldXZ;
				o.uv_slice = float3(input.uv, _LD_SliceIndex);
				return o;
			}
``

I think your change amounts to taking one minus of input.uv.y. However i wanted to ask as I'm already "trying" to account for UV starting at top, as in the define, and I don't want to flip it twice.

**Comment by minggoddess** [comment]
Yeah， I am using an old version  about severals months ago. My changes are based on the old version. I checked
`
Varyings Vert(Attributes input)
			{
				Varyings o;
				o.positionCS = float4(input.positionOS.xy, 0.0, 0.5);

#if UNITY_UV_STARTS_AT_TOP // https://docs.unity3d.com/Manual/SL-PlatformDifferences.html
				o.positionCS.y = -o.positionCS.y;
#endif
				float2 worldXZ = UVToWorld(input.uv);
				o.worldPos.xy = worldXZ;
				o.uv_slice = float3(input.uv, _LD_SliceIndex);
				return o;
			}`
 just now, wave moves correctly in openGL.
 I thought you did not treat openGL bugs so I committed this issue.
There is no need to use my suggestion with your latest version.

Thank you for your reply. ^_^

**Comment by huwb** [comment]
We usually treat opengl bugs when you help us fix them! Thanks again contributing the above and apologies you ran into them.
