### ISSUE TITLE
Unity Origin Movement for Large Terrains

### ISSUE THREAD

**Issue by hdsumerkan** [crest-ocean/crest#337]
Hi,
I want to use Crest on my project but I have a small problem that needs to be solved. The thing is my world is around 20kms and it seems it is large enough to make unity wrong calculations on floating numbers.  I faced with precision problems when an object is far away from origin and because of that I am moving the origin when camera gets far away. When I use Crest with this kind of backend I got the attached video(Decreased origin movement distance to highlight my problem). Do you  have any suggestion on how to solve this problem?

https://drive.google.com/file/d/1-g-1y8zbivW7NMosRZn2WaEb2EOZNU0h/view?usp=sharing

**Comment by huwb** [comment]
I don't have masses of experience with this but i would point you to the notes we wrote up in the user guide, maybe these help?

https://github.com/crest-ocean/crest/blob/master/USERGUIDE.md#floating-origin

**Comment by huwb** [comment]
Closing, but if you reply we'll get notifications
