### ISSUE TITLE
Multiple plugin error for unity 2019.2

### ISSUE THREAD

**Issue by sirchick** [crest-ocean/crest#342]
Hi

I imported the GitHub project and got:

Multiple plugins with the same name 'freeimage' (found at 'Assets/crest-master/src/exr_processor/Debug/FreeImage.dll' and 'Assets/crest-master/src/exr_processor/Release/FreeImage.dll'). That means one or more plugins are set to be compatible with Editor. Only one plugin at the time can be used by Editor

How do i fix this ?

**Comment by huwb** [comment]
Hello, the repository contains multiple unity projects and should not be
copied in entirely.

The relevant assets that should be copied are in

Crest/assets/crest

**Comment by sirchick** [comment]
Ah my bad ,  thanks :)
