### ISSUE TITLE
Spectrum power interpolation doesn't respect disable option when calculating amplitude

### ISSUE THREAD

**Issue by daleeidd** [crest-ocean/crest#351]
**Describe the bug**
I am not certain if this is a bug or intended behaviour. This [line in the source](https://github.com/crest-ocean/crest/blob/master/crest/Assets/Crest/Crest/Scripts/Shapes/OceanWaveSpectrum.cs#L107) interpolates between the current power and the next higher power, but it doesn't check if the next power is disabled or not.

**Additional context**
There are three options I can think of:
1. Leave as is. This is expected behaviour
2. Find the next highest power that is enabled
3. If the next power is disabled, skip interpolation

The current option (1) can be a little confusing when debugging or authoring. I was wondering why a disabled slider was still affecting the spectrum.

I was going to do a PR, but I was not sure which option you would prefer.

**Comment by huwb** [comment]
Thanks for IDing this and for talking it through.

Is there an option 4 where the disabled flag forces the corresponding power down to the minimum value. So it will be as if the slider is set to the far left, regardless of its actual value. What do you think?

**Comment by daleeidd** [comment]
Option 4 sounds good. There is a PR waiting.
