### ISSUE TITLE
Foam suffers from precision artifacts on Switch

### ISSUE THREAD

**Issue by chrispewebb** [crest-ocean/crest#363]
When running on Switch slightly away from the origin, foam textures suffer from extreme artifacting caused by low precision texture coordinates (i_worldXZUndisplaced).

The cause of this issue is simply that lodAlpha_worldXZUndisplaced_oceanDepth is half precision, which on most platforms is actually defined as a float. On Switch however, this is now correctly compiled to a mediump vec4, which is not enough precision to store world coordinates.

Changing lodAlpha_worldXZUndisplaced_oceanDepth to a float4 resolves the issue on Switch.

**Comment by chrispewebb** [comment]
Just another note, this issue _sometimes_ does not appear, depending on what registers are around when doing the coord related math. I found sometimes it would actually do them in full precision anyway since it had those registers around (I was making changes to the ocean shader and was wondering why at random the foam was breaking haha)

**Comment by huwb** [comment]
Apologies it took us a while to get back to you. Thank you very much for tracking this down. The worldXZ should definitely be full precision.
