### ISSUE TITLE
Baked depth cache

### ISSUE THREAD

**Issue by huwb** [crest-ocean/crest#364]
Instead of always dynamically generated depth cache, could bake it offline, perhaps as an editor tool.

Pros: Simpler/more intuitive. Less prone to bugs. Gets around the instanced terrain issue.
Cons: Potentially large high precision texture (disk space concern). Needs rebake/regen when world changes.

I had an attempt at this but could not get it to load/save correctly: https://github.com/crest-ocean/crest/commit/742f62cfc0c42485083eb75b23406d4a05d47570

Discord user 'snacktime' also had a stab at this: https://gist.github.com/gamemachine/a83671661c867417c26820fe32e82562

This issue is to track this approach and see if we can get it shippable.

**Comment by daleeidd** [comment]
What was the issue both of you encountered? I have tested this on 2019.2.16f and it works. I tried it on 2018.4.0f1 and the texture saved squished horizontally. This is on MacOS. I did a site search through Unity's release notes and found a few fixes for MacOS for ReadPixels, but nothing pertinent for Windows. Not sure what version this was fixed in.

Live depth cache:
![Depth Cache Live](https://user-images.githubusercontent.com/5249806/71170682-f13ab880-22af-11ea-85da-4151e5dd1ad8.png)

Saved depth cache:
![Depth Cache Saved](https://user-images.githubusercontent.com/5249806/71170687-f6980300-22af-11ea-86d2-a0dbb4c87a4b.png)

The saved one is a bit blurry because of resolution setting when saved.

**Comment by huwb** [comment]
Interesting. I get this:

![image](https://user-images.githubusercontent.com/939901/71269853-2c88c600-2348-11ea-9b9f-54405c98ef9f.png)

One potential thing is that the depth cache was probably populating on starttup, even if you specified a saved cache. I've just pushed a change to that branch which makes it not render anything if a cache was specified.

Also, the "save" button was visible even when outside of play mode, when there was no data in the cache. It may not have actually saved any useful data in this case. I've made it so you can only save while in play mode as well.

**Comment by daleeidd** [comment]
But that function also populates the cache from the texture. Here is more substantial proof that it works (no island):

Without texture:
![No cache](https://user-images.githubusercontent.com/5249806/71299322-ee8bb080-23e0-11ea-8e71-a97477104985.jpg)

With texture:
![Cache](https://user-images.githubusercontent.com/5249806/71299312-da47b380-23e0-11ea-9f00-d0b253f8e3a8.jpg)

**Comment by daleeidd** [comment]
Also, this was the issue I was having in 2018.4 on MacOS when I was initially testing:

![Broken Saving](https://user-images.githubusercontent.com/5249806/71299670-b2f1e600-23e2-11ea-988e-1843448f1ba3.jpg)

The saving of the texture itself was broken. I thought this was your problem. This was fixed at some point though.

**Comment by daleeidd** [comment]
So your problem must have been unchecking "Populate on Startup" since that is also where the cache [loads the texture](https://github.com/crest-ocean/crest/blob/feature/save-depth-cache/crest/Assets/Crest/Crest/Scripts/LodData/OceanDepthCache.cs#L162).

**Comment by dizzy2003** [comment]
our solution is  we bake a 4096x4096 r8 texture once at runtime. (we used
to have a complex caching system)

**Comment by huwb** [comment]
Ah good point. I pushed a new commit that:

> Stop populate cache if a saved cache provided. Move assignment of saved cache out of this function.

Should be a little more sane now.

With that I get this:

![image](https://user-images.githubusercontent.com/939901/71306866-34934500-23de-11ea-9830-b5da851286d1.png)

The depths in the EXR look funky, I'm not quite sure what hte best solution is. Maybe I'm missing something obvious?

![image](https://user-images.githubusercontent.com/939901/71306881-62788980-23de-11ea-8495-ec0fad9f5a68.png)

**Comment by daleeidd** [comment]
I think it has to do with your OS and how it interprets EXR data. I get this with your recent commits:

![Saved](https://user-images.githubusercontent.com/5249806/71307092-2b859080-243d-11ea-9957-fa5053de037f.png)
![New commits](https://user-images.githubusercontent.com/5249806/71307099-51ab3080-243d-11ea-858b-a9a50ff37676.jpg)

**Comment by huwb** [comment]
Weird. It might be the texture compression format. I couldnt get mine to be "BC6H UFloat", maybe this is a Metal compression format. 

This is what i get if on windows i dont change any import settings on the texture at all:

![image](https://user-images.githubusercontent.com/939901/71311318-3b3dae80-2416-11ea-9bf3-dfc4715f470c.png)

**Comment by daleeidd** [comment]
I switched to Windows and got the same results as you. I worked out a solution by changing the [`RenderTextureFormat`  on this line](https://github.com/crest-ocean/crest/blob/feature/save-depth-cache/crest/Assets/Crest/Crest/Scripts/LodData/OceanDepthCache.cs#L165) to `DefaultHDR` [(which is `ARGBHalf` apparently)](https://docs.unity3d.com/ScriptReference/RenderTextureFormat.DefaultHDR.html). But this didn't work for Metal; it produces nothing.

Other things I tried:

Using [`TextureFormat.RHalf` on this line](https://github.com/crest-ocean/crest/blob/feature/save-depth-cache/crest/Assets/Crest/Crest/Scripts/LodData/OceanDepthCache.cs#L297) which got me the same RGB preview and format as Metal, but the R channel was still broken like you have shown.

Using EncodeToPNG. Only slightly different results.

Inverting the R channel after reading pixels. This produced something much closer to what we want, but still incorrect.

**Comment by huwb** [comment]
Thanks @daleeidd! Could you please give it another spin?

I put platform defines to select format and it works for me now!

I also apply what i believe to be good texture import settings (main thing is importing a single channel). Could you please verify that it works for you?

If it does then we might be in pretty good shape. What changes do you feel are required to make this shippable?

**Comment by daleeidd** [comment]
No worries. Works on MacOS and Windows for me. I am working on a few changes. Will do a PR later or tomorrow.

**Comment by moosichu** [comment]
Fixed by #378

**Comment by huwb** [comment]
Closing now as this just went live in version 3.4
