### ISSUE TITLE
Planar reflection broken on VR (Oculus Quest)

### ISSUE THREAD

**Issue by crystalbyte** [crest-ocean/crest#368]
**Describe the bug**
Planar reflections are heavily distorted on the Oculus Quest.
This is the editor output as it should render https://cdn.discordapp.com/attachments/559872374682681345/651484167103840277/unknown.png

**Screenshots / video**
This is how the scene renders on the Quest
https://cdn.discordapp.com/attachments/559872374682681345/651483552638304275/com.oculus.vrshell-20191203-174902.mp4

**Log**
There are no errors or warnings.

**Versions**
This happens with the following versions

- Unity 2019.1.14f (LWRP 5.7.2, Single Pass, Forward Renderer)
- Unity 2019.2.14f (LWRP 6.9.2, Single Pass, Forward Renderer)

**To Reproduce**

- Setup basic ocean scene with a reflective asset, enable planar reflection.
- Build on the Quest.

**Platform**
VR (Oculus Quest)

**Hardware**
Snapdragon SoC

**Comment by huwb** [comment]
Thanks for reporting. I'll let you know when i have news. I have an unusually high number of support requests at the moment but should be able to look at this before or on this weekend.

**Comment by crystalbyte** [comment]
As a side note. In order to get anything meaningful rendered on a Quest any transparent effects need to be disabled since the opaque texture is not accessible.

**Comment by huwb** [comment]
For me reflections looked doubled in VR, and setting camera type to Reflection fixed it: https://github.com/crest-ocean/crest/commit/1ab6695cdce6f4c6a272d29acc4561fc08dbd661

Could you try adding this line of code (highlighted in green)? Let me know if this makes sense

**Comment by crystalbyte** [comment]
After applying the change the reflection was indeed fixed, the only remaining issue is a heavy flickering which doesn't occur in the editor.

I have again recorded a video
https://cdn.discordapp.com/attachments/559872374682681345/651743030935683072/com.oculus.vrshell-20191204-121242.mp4

**Comment by huwb** [comment]
Have you tried increasing the reflection resolution on the planar reflection script? I think the default is very low (for perf) - like 256x256.

**Comment by crystalbyte** [comment]
Unfortunately increasing the texture size didn't help, while the reflection now looks more crisp, it still flickers heavily. These are the settings I use in the planar reflection script.

![image](https://user-images.githubusercontent.com/548964/70138920-a4d96100-1691-11ea-906e-1ed724d2b587.png)

**Comment by crystalbyte** [comment]
I changed the refresh rate to 120 and this is the result.
https://cdn.discordapp.com/attachments/559872374682681345/651771001339904020/com.oculus.vrshell-20191204-135943.mp4

As long as the reflection "shape" is not recomputed it looks and behaves perfectly, apart from the reflection moving with the camera of course. Once the reflection is updated the shape changes dramatically which results in the flickering when setting the refresh rate back to 1.

**Comment by huwb** [comment]
It might be update order. The VR stuff might update after the reflection
renders which would make jitter.

It may help to mess around with the script execution order in the editor,
perhaps pushing the OceanPlanarReflection script to have a larger update
order value.

I can look at this later but just giving a quick thought in the meantime.

**Comment by crystalbyte** [comment]
Just checked the execution order for the reflection script before and after default scripts without success.

**Comment by crystalbyte** [comment]
I just increased the texture size of the reflection to 2048 which helps somewhat since the flickering edges are now smaller and less pronounced. What hits me as strange is the fact, that even a static non moving object on a static non moving mirror plane computes different reflection images at different frames is this perhaps a left eye, right eye issue?

**Comment by huwb** [comment]
I tried messing around with the mock HMD and it seems to be fine.

Maybe the *Refresh per frame* setting is confusing. It means how many frames between reflection renders. So setting it to 1 means render every frame. I will try to think of a better name.

It might be that flickering edges are unforunately "normal" here and its a limitation of reflections. Its probably possible to turn on antialiasing on the reflections which may help, but will add cost. What do you think?

**Comment by huwb** [comment]
Oh thats a thought - if you disable *Hide Camera Gameobject* then you should see the camera that renders reflections appear in the scene view, and then you can mess around with its settings and probably turn on MSAA or experiment with it. If you find a configuration that works, i could add it as an option to the script.

**Comment by crystalbyte** [comment]
> It might be that flickering edges are unforunately "normal" here and its a limitation of reflections. Its probably possible to turn on antialiasing on the reflections which may help, but will add cost. What do you think?
I am unsure for we did find a reflective shader that works on the Quest without these kinds of issues, but is otherwise unreliable and borderline unusable.
https://assetstore.unity.com/packages/vfx/shaders/urp-lwrp-mirror-shaders-135215

On the rare occasion that we did get it to work tho it did so without any visual issues. I, therefor, refuse to believe that this is just the way it is.

**Comment by huwb** [comment]
Would it be possible to get a video from your build which has refresh set to 1, has high res reflections (to eliminate aliasing / resolution issues), and has motion to make the flickering appear. I see something in your first video but the issue isnt clear to me  I guess it would be good to get some panning motion and then some rotation motion, and then anything else that makes the issue obvious.

**Comment by crystalbyte** [comment]
I will record one shortly.

**Comment by crystalbyte** [comment]
I think I have found the culprit. What has been done in the other shader is render the reflection texture for each eye separate using `camera.GetStereoViewMatrix(Camera.StereoscopicEye.Left)` and `camera.GetStereoViewMatrix(Camera.StereoscopicEye.Right)` when an HMD is detected. In the case of the OceanPlanarReflection script this is not done resulting in each eye seeing the same reflection texture rendered from the same position. Since both eyes have an offset, this results in flickering.

**Comment by crystalbyte** [comment]
Sorry, clicked the close button by accident. I will still try to spin up a scene where the issue is visible in a video.

**Comment by crystalbyte** [comment]
I have uploaded a video where I hope the flickering is noticeable. Focus on the yellow windows of the small houses. The texture for the reflection is set to 4096 and I have removed all displacement and distortions from the water surface. On the desktop with this setup the reflection is static and a pixel perfect copy of the original.

https://cdn.discordapp.com/attachments/559872374682681345/654736708281303045/com.oculus.vrshell-20191212-182808.mp4

**Comment by huwb** [comment]
Please be patient with me and forgive me but.... i really dont see any issue, at all. The non-reflected window pixels are also flickering. That looks totally normal to me and would be addressed with AA. Sorry I'm not getting it.

I thought about the stereo matrix thing. I think this is different, and unrelated. I am currently setting hte camera type to Reflection and it will render once and this is deliberate and I dont think this should cause jitter.

**Comment by crystalbyte** [comment]
I can see, how you would come to that conclusion, VR comes with many issues, almost all of them result in flickering due to different reasons, the non reflected windows flicker, due to z fighting ofr instance. I will close this for now, since the original issue has been solved.
Should I be able to dive deeper into the causes, I will just hit you up on Discord.

**Comment by huwb** [comment]
Thanks
