### ISSUE TITLE
[LWRP] Underwater effect is cut at middle of screen

### ISSUE THREAD

**Issue by huwb** [crest-ocean/crest#369]
Underwater curtain seems to clip with near plane producing an odd result where curtain is cut.

Happens in single pass VR in LWRP.

**Comment by huwb** [comment]
For me, in main.unity, 2019.2, mock HMD, the depth cache wasn't populating. It seems the depth cache camera needed to be set to Reflection type to stop it being affected by VR. Fix: https://github.com/crest-ocean/crest/commit/4d8dcd3ff978080fc9741d1cc8774cadec7b8b78

**Comment by huwb** [comment]
We have a pretty good idea of the problem and should have a fix soon.

**Comment by NiekoEugenijus** [comment]
Hi, any news on this?

**Comment by huwb** [comment]
Hi there, sorry we haven't fixed it yet. I speak to my colleague and I hope we can fix it soon - will report back when i have news.

**Comment by moosichu** [comment]
Hi, I've been unable to dedicate much time to Crest for the past few months for personal reasons, I'm jumping onto looking at this now so hopefully will have something through soon 😄

**Comment by moosichu** [comment]
A fix for this should be integrated into the next release.

**Comment by huwb** [comment]
Should be fixed in Crest URP 3.5. Nice one @moosichu.
