### ISSUE TITLE
Under Water Fog Control

### ISSUE THREAD

**Issue by wash3d** [crest-ocean/crest#370]
There is Any Way to control how much fog we could have under water? I tried to make a submarine scene with not visibility as I desire and I did not found any way to get the fog effect down.
![image](https://user-images.githubusercontent.com/11538258/70110709-a291eb00-162e-11ea-875f-c9e365350d19.png)
Thanks

**Comment by huwb** [comment]
The density of the fog underwater can be controlled using the Fog Density parameter on the ocean material. This parameter applies to both above water and underwater

I added this to a couple of places in the user guide, including the underwater section.

**Comment by huwb** [comment]
Closing for now
