### ISSUE TITLE
Depth cache layer names won't expand in Unity 2019.2

### ISSUE THREAD

**Issue by cowhunt** [crest-ocean/crest#385]
Layer names field has arrow but does not expand when clicked, as shown here:

![image](https://user-images.githubusercontent.com/48890693/71563831-12f52600-2a8e-11ea-88e3-31c12550de24.png)

**Comment by huwb** [comment]
Should be fixed in the referenced commit, leaving open until 3.5 is published.

**Comment by huwb** [comment]
Closing now that 3.5 has gone live
