### ISSUE TITLE
Question: How to create small and frequent waves?

### ISSUE THREAD

**Issue by EcoEditor** [crest-ocean/crest#386]
Hello Huw,

I've noticed the ShapeGrestnerBatched.cs script is responsible for creating waves in OceanInputs - 
OceanWavesBatched object.
We want to get small and frequent waves in our sea and we managed to get this look by exceeding the number of Components per Octave (from 8 to 100). 
I've got an error about exceeding buffer size and realized the look we got was actually a "bug" on my side, and overall increasing this variable can compromise performance. 
Also, after increasing the buffer size on both the script and the shader (keeping the "Component per Octave" at 100) - the expected look changed as well.

Which component should I change to get the desired result? 

Thank you!

**Comment by huwb** [comment]
I'm not sure, could you illustrate what you are aiming to achieve?

**Comment by huwb** [comment]
Closing for now but if you reply we'll get a notification so feel free to revive this later.
