### ISSUE TITLE
Flow map/shore waves

### ISSUE THREAD

**Issue by Kandob** [crest-ocean/crest#389]
A good addition would be the ability to either add a flow map or make waves near shallow surfaces move towards the shore. I'm using crest for an island and it looks like a pool near the shores.

**Comment by huwb** [comment]
There is an ocean input for adding a flow map - shader `Crest/Inputs/Flow/Add Flow Map`. It's fairly recent and I haven't heard of people using it, I would be curious to hear if it works for you.

I'm not sure if you've added ocean inputs before, there's a video on it here in case you have not: https://www.youtube.com/watch?v=sQIakAjSq4Y&t=3s

**Comment by Kandob** [comment]
I don't see `Crest/Inputs/Flow/Add Flow Map`. There's fixed direction and whirlpool and both don't work. I've followed the video you've linked. 

Here's the fixed direction input:
![1234](https://user-images.githubusercontent.com/14958256/72207540-6c038780-349a-11ea-81d0-bb913cf7f082.png)

I can see the plane in the simulation map but as far as I can see it has no effect on the flow. I've tried changing the speed and direction in the shader.

**Comment by huwb** [comment]
Could you fill out the issue template? We have numerous versions of crest, and numerous versions within each, which is why we added the template. Thanks!

**Comment by Kandob** [comment]
**Describe the bug**
Adding a directional flow input does not have any effect

**Screenshots / video**
![1234](https://user-images.githubusercontent.com/14958256/72208454-0d8ed700-34a3-11ea-8261-def617993bd0.png)

**Log**
No warnings/errors

**Versions**
built-in, Unity 2019.3.0f3 

**To Reproduce**
Add the script and shader as usual to a plane and place the plane on top of the ocean.

**Platform**
 - Editor and standalone
 - Windows 10

**Hardware**
GTX 1070, i7 4770k

**Comment by huwb** [comment]
Hm the shader should be there: https://github.com/crest-ocean/crest/blob/master/crest/Assets/Crest/Crest/Shaders/OceanInputs/FlowAddFlowMap.shader

It may not be on the last release though if you are on that version? If so you'll need to download crest directly from the main page of this repos to get latest.

**Comment by Kandob** [comment]
I get the same result with the shader you linked to. The flow map shows up in the AnimWaves map but it doesn't affect the actual waves.

![Annotation 2020-01-12 151903](https://user-images.githubusercontent.com/14958256/72220230-e55cb200-354e-11ea-89e1-4829f65dde4d.png)

**Comment by Kandob** [comment]
I've managed to get it working. I forgot to tick 'Create Flow Sim' in the ocean renderer script. 

But there's another problem. I have to set the speed very high in order to move the waves towards the shore.
https://media.giphy.com/media/XI25VW8YSupR49XWJC/giphy.gif

**Comment by huwb** [comment]
Ok, I see this hasn't really worked.

The flow system was designed for horizontally flowing water, like rivers etc. We don't have a great solution for shorelines at the moment, but we're thinking about it and hope to have another run at this soon.

It would be possible to orient the waves along the shoreline manually by setting the wind direction. It would be possible to set up multiple *Shape Gerstner Batched* scripts for different angles and crossfade between them using the *Weight* param on this script. Not ideal but thats the best we can offer right now.

**Comment by Kandob** [comment]
Thanks for the suggestion. I've tried it but since I'm using crest for an island i can't really make it work well, they just cancel each other out.

I saw an option called _Direct towards point_ and I don't know what it exactly does, I can't seem to make the waves all move to a point.

**Comment by huwb** [comment]
Yeah the direct towards point appears to be broken. We were never 100% happy with how it worked - it had its own set of problems - so we'll be seeking a new solution going forwards. I'll update this issue if we make progress on it.
