### ISSUE TITLE
Turn off underwater effects in an area

### ISSUE THREAD

**Issue by Kandob** [crest-ocean/crest#390]
I have an underwater area with windows but with crest when you're underwater even closed areas will have the underwater effects. Would it be possible to turn off the effects for the camera but still have them for the windows?

![daniel-gerhard-1111](https://user-images.githubusercontent.com/14958256/71907123-a94ed900-316b-11ea-98c0-9924b92169d0.jpg)

This would be the same case for submarines and ships with sections that are underwater.

**Comment by huwb** [comment]
See #376 as a recent version of this question.

#77 might be of interest/worth tracking - it's not the full solution but will hopefully improve the clipping aspect.

Closing as a dupe.
