### ISSUE TITLE
Reflections bleeding through walls in darkness

### ISSUE THREAD

**Issue by Kandob** [crest-ocean/crest#392]
I've made a room with complete darkness and thick walls but it seems like the reflection from outside is bleeding through. Also, the shadowing doesn't make the ocean completely dark. Is this a bug or am I doing something wrong?

![Annotation 2020-01-09 222444](https://user-images.githubusercontent.com/14958256/72106206-38581e80-332f-11ea-8f18-0e4c80333769.png)

**Comment by huwb** [comment]
Hi there, i'm not sure about this one. I believe this would also be an issue for any reflective material (besides water). I don't have enough experience to know how this kind of thing is solved. Maybe something with reflection probe settings?

**Comment by Kandob** [comment]
My guess is that the specular is not being masked in shadowed areas. I can see some fresnel at certain angles which shouldn't be visible in complete darkness.

Is the fact that the ocean can't be completely dark a limitation in unity or is it something else?

**Comment by huwb** [comment]
I think its something with the reflection probe settings - but I'm not an expert at lighting and have never tackled a tricky case like this, so I may be limited help.

**Comment by Kandob** [comment]
The thing is, i'm not using any reflection probes.

**Comment by huwb** [comment]
Ok then. In that case you might try reducing the jitter / blur radius of the shadow data, on the shadow settings:

![image](https://user-images.githubusercontent.com/939901/72217090-a2d0b080-3521-11ea-9916-ed11dae2bb42.png)

**Comment by Kandob** [comment]
I've tried it but it has no effect on the reflections

**Comment by b1gry4n** [comment]
Another thing to keep in mind is that the reflection camera is actually another camera, any image effects youre applying to your main camera arent taken in to consideration when rendering the reflection. So for example if you are darkening your colors in the main camera its possible the sky/objects are still bright or brighter to the reflection camera.

**Comment by Kandob** [comment]
No that's not he issue here, the planar reflection script that comes with crest uses the camera it's attached to.
https://github.com/crest-ocean/crest/blob/e74e5e5ad630820658b5ffe2aa73f4477887e9c9/crest/Assets/Crest/Crest/Scripts/Reflection/OceanPlanarReflection.cs#L107

**Comment by b1gry4n** [comment]
youre right, I must have confused crest with other water assets. my bad

**Comment by daleeidd** [comment]
@Kandob Can you please provide a minimal scene/project that reproduces this? We won't be able to determine the issue or improve Crest for this use case without having your setup.

**Comment by daleeidd** [comment]
So this does appear to be an issue with the jittered/blurred sampling of shadows. Work towards preventing shadow leaks might help resolve this, but it would depend on how thick the walls are for this case. If we sampled the non-jittered shadow position and determined it was in maximum shadow, then we could just use that value and skip jittering.

Another solution that comes to mind which could be useful is a shadow input component which can override shadow data.

I'll look into both.

**Comment by daleeidd** [comment]
We have added the _Register Shadow Input_ component which will help solve this which will be out for 4.6. It will allow you to set the shadow data and bypass jittering.

**Comment by daleeidd** [comment]
Fixing shadow and unshadowed data from bleeding is on our radar so I think we can close this one. Shadow inputs which is now out with 4.6 gives everyone a workaround.
