### ISSUE TITLE
IndexOutOfRangeException with DWP2 using new height queries

### ISSUE THREAD

**Issue by skaughtx0r** [crest-ocean/crest#399]
Getting an IndexOutOfRangeException in Crest.QueryBase.UpdateQueryPoints().

I started to try and make a reproducible project with just the DWP2 demo scene and Crest and it just errors immediately, the water never renders, and all the water objects just fall.

It seems the issue is that there is a s_maxQueryCount set to 4096 and if that gets exceeded, exceptions start to get spammed.

**Log**

The following errors are spammed repeatedly in the log.

```
IndexOutOfRangeException: Index was outside the bounds of the array.
Crest.QueryBase.UpdateQueryPoints (System.Int32 i_ownerHash, Crest.SamplingData i_samplingData, UnityEngine.Vector3[] queryPoints, UnityEngine.Vector3[] queryNormals) (at Assets/Crest/Crest/Scripts/Collision/QueryBase.cs:245)
Crest.QueryDisplacements.Query (System.Int32 i_ownerHash, Crest.SamplingData i_samplingData, UnityEngine.Vector3[] i_queryPoints, System.Single[] o_resultHeights, UnityEngine.Vector3[] o_resultNorms, UnityEngine.Vector3[] o_resultVels) (at Assets/Crest/Crest/Scripts/Collision/QueryDisplacements.cs:61)
DWP2.CrestWaterDataProvider.GetWaterHeights (UnityEngine.Vector3[]& p0s, UnityEngine.Vector3[]& p1s, UnityEngine.Vector3[]& p2s, System.Single[]& waterHeights0, System.Single[]& waterHeights1, System.Single[]& waterHeights2, UnityEngine.Matrix4x4[]& localToWorldMatrices) (at Assets/DWP2/Dynamic Water Physics 2/Scripts/WaterObject/WaterDataProvider/CrestWaterDataProvider.cs:104)
DWP2.WaterObjectManager.Schedule () (at Assets/DWP2/Dynamic Water Physics 2/Scripts/WaterObject/WaterObjectManager.cs:475)
DWP2.WaterObjectManager.FixedUpdate () (at Assets/DWP2/Dynamic Water Physics 2/Scripts/WaterObject/WaterObjectManager.cs:228)
```
```
ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: Bad indices/count arguments (managedBufferStartIndex:0 computeBufferStartIndex:0 count:5196)
UnityEngine.ComputeBuffer.SetData (System.Array data, System.Int32 managedBufferStartIndex, System.Int32 computeBufferStartIndex, System.Int32 count) (at C:/buildslave/unity/build/Runtime/Export/ComputeShader.bindings.cs:166)
Crest.QueryBase.ExecuteQueries () (at Assets/Crest/Crest/Scripts/Collision/QueryBase.cs:423)
Crest.QueryBase.Update () (at Assets/Crest/Crest/Scripts/Collision/QueryBase.cs:403)
```

**Versions**
Crest: master branch
DWP2: 2.1.0
Unity: 2018.4.10f1

**To Reproduce**
This can be reproduced by adding the Crest Ocean to the DWP2 demo scene. I have an example project, but I probably cannot attach it here, message me in discord and we can figure out a way to get it to you.

You can probably reproduce by querying more than 4096 points.

**Platform**
 - Editor and Standalone
 - Windows

**Hardware**
Nvidia RTX 2080

**Comment by skaughtx0r** [comment]
@huwb I think the main issue here is that `s_maxGuids` and `s_maxQueryCount` in QueryBase need to be configurable. I need more than 4096 queries and 64 guids. It might also be good to let `s_maxRequests` be configurable as well.

I can do this in a PR, I'm just not sure where to put the settings, should they go into the `IReadbackSettingsProvider` ?

**Comment by huwb** [comment]
Thanks for bumping, sorry for the delay with this..

`s_maxGuids` - i contemplated removing this completely. its only a safeguard that was put in to the first version of the code as a reasonable limit, but i think it can be extended or removed. maybe up it to 512, or 1024? given that it doesnt really do a lot, i'm not really excited about adding another user facing configuration which will need documentation and etc. Let me know what you think?

`IReadbackSettingsProvider` is gone on latest. perhaps try adding it to the SimSettingsAnimWaves if you're up for it? I'm not quite sure if it will work 100% this way but it should be quick to try. But if you prefer i try it let me know.

Thanks!

**Comment by skaughtx0r** [comment]
OK, PR is up #415

**Comment by huwb** [comment]
Merged, thanks again @skaughtx0r
