### ISSUE TITLE
Occlusion culling in planar reflection

### ISSUE THREAD

**Issue by Kandob** [crest-ocean/crest#401]
**Describe the bug**
I found the same issue here: https://github.com/crest-ocean/crest/issues/116 but I noticed that it's already implemented in the script. However, I still have this problem in my scene.

I usually set `camera.useOcclusionCulling = false;` but since the script that comes with Crest uses the attached camera instead of a dedicated camera it would disable occlusion culling altogether.

**Screenshots / video**
https://media.giphy.com/media/QYwFipmOpF6vrEdeo2/giphy.gif

**Log**
No warnings/errors

**Versions**
Built-in, 2019.3.0f3

**To Reproduce**
Like usual. Bake the occlusion and apply the planar script to the camera.

**Platform**
 - Windows 10

**Hardware**
GTX 1070, i7 4770k

**Comment by daleeidd** [comment]
Sorry for getting back to this so late... I believe this is related to #528 where there is a more in-depth discussion about this.
