### ISSUE TITLE
OpenGL 4.5 "Invalid texture unit!" Errors on Linux in UnityEngine.Graphics:ExecuteCommandBuffer(CommandBuffer)

### ISSUE THREAD

**Issue by LiveOverflow** [crest-ocean/crest#410]
**Describe the bug**
Crest Ocean has a weird behaviour on a Linux build where close water areas are not rendered. It looks like the water is getting pushed away from the player.
It's probably not just a render error, as the character controller in the screenshot queries the ocean height for swimming, and the character can walk freely on the terrain as the water is always pushed away around the player.

**Screenshots / video**
![](https://media.discordapp.net/attachments/559872374682681345/670745215925092392/crest_opengl.png)

**Log**

```
OpenGL Error: Invalid texture unit!
UnityEngine.ComputeShader.Dispatch(Int32, Int32, Int32, Int32)
Crest.QueryBase.ExecuteQueries() [QueryBase.cs:428]
Crest.QueryBase.Update() [QueryBase.cs:403]
```

```
This GfxDevice does not support asynchronous readback
UnityEngine.Rendering.AsyncGPUReadback:Request(ComputeBuffer, Action`1)
Crest.QueryBase:Update() [QueryBase.cs:413]
```

```
OpenGL Error: Invalid texture unit!
UnityEngine.Graphics:ExecuteCommandBuffer(CommandBuffer)
Crest.BuildCommandBuffer:LateUpdate() [BuildCommandBuffer.cs:95]
```

**Versions**
Crest commit id: `c7ab95abc8919beb58b32777bdb3a191f88845f1`
Unity 2019.3.0f5 - built-in render pipeline

**Platform**
 - Linux 4.15 Ubuntu 18.04 64bit
 - OpenGL 4.5 (Core Profile) Mesa 18.2.8

**Hardware**
 - Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2)

**Comment by huwb** [comment]
Hm ok, I dont think we support OpenGL. Could you try setting the API to Vulkan in the player settings?

**Comment by moosichu** [comment]
For various reasons we only support Vulkan and not OpenGL unfortunately. Vulkan should work. I used to develop on Linux a lot (and will be again soon), so that should be OK.
