### ISSUE TITLE
Large Height Map (or maybe not)

### ISSUE THREAD

**Issue by damonbla** [crest-ocean/crest#412]
Hi, this is not really an issue, but more of a question. It may be tough or impossible, and I know it's mentioned shortly in the documentation, but I'm looking to compute a height map of a large portion of the final ocean surface (probably about half), maybe once a second, for as long as I can, up to a few minutes, and then outputting each map as a separate image.

We've managed to get this working nicely for very small portions of the surface by performing height samples, and the results looked great. It's like looking at the bottom of a pool on a sunny day, the caustics there. Unfortunately, as you probably expect, trying to do this for very large portions of the water surface is quite slow, on the order of minutes per image. We tried a 4k square and it took about 53 minutes to output one height map.

Why would I want to do this? Well, we are essentially looking to simulate how a radar would "see" waves on an ocean's surface. Crest creates such nice ocean waves, and fast, in Unity, and looked perfect for our needs. However, to calculate ray intersections with the water at far distances (up to 3km) from a boat for example, with wave shadowing, etc, we need to have the actual geometry of a large portion of the water for intersections. We thought by creating a height map and then basically recreating the ocean's surface with a mesh from that, we could get the data we needed.

Is it possible there is a way to do that with Crest without the process of creating a height map and back-generating the ocean surface? Am I wrong - could a ray actually be shot from halfway across the ocean's surface at a nearly parallel angle with the water and an intersection be detected? Sorry if this is a really ignorant question! I'm not new to Unity or shaders, but I'm new to ocean and wave generation and some of the shader and LOD madness that makes Crest work.

**Comment by huwb** [comment]
This shader takes world xz positions and computes wave height at each position

https://github.com/crest-ocean/crest/blob/master/crest/Assets/Crest/Crest/Shaders/Resources/QueryDisplacements.compute

I would make your 4k render target, then revert a full screen quad into it, compute a position based on wherever you want each texel to be, then call the code from the above shader to compute a height from the position. Sounds easy right? :)

**Comment by huwb** [comment]
Oh actually that shader computes a displacement vector to each position. It is converted to a height in the world using:

Displacement.y + sea level

**Comment by damonbla** [comment]
Thank you @huwb! Easy, yeah right ;-) I've never played around with a compute shader, but it looks like now is the time. Thanks for pointing me in the right direction. I'll let you know how it goes!

**Comment by damonbla** [comment]
Figured I'd post an update here now that I've finally had a chance to put some time into this! I managed to get it working, and with a 512x512 texture it's running at about 9 fps on a GeForce 980. 

Here's a screen capture:
![heightToTexture](https://user-images.githubusercontent.com/4601836/74033335-e503db00-4983-11ea-8984-709b5bda38c4.png)

The quad with the heights is just floating in the air in the scene. The red spheres are for debug to show the borders of the area from which I'm gathering the heights. That area can be moved around and the height calculations will automatically move around with it. I made it so that it's easy to enlarge the capture area, which will be nice. Interestingly you can see a "line" going through the data, which I believe is an LOD border. I think there must be a way to smooth that out, but for my purposes I'm not sure it's important anyway. I know I can optimize a few things to speed this up as well - I was just trying to get something working in the first place.

Next step is to get the texture to display those heights from a point of view other than straight down. Thanks again for the help!

**Comment by huwb** [comment]
The sea floor has a hard line which would affect the wave heights, i'd try disabling or moving the island around.

Understood about the optimiation, i'm curious though as it should cost almost nothing at all. are you reading back data onto the CPU synchronously? thats the only thing i could think of that should cost more than a fraction of a ms on that gpu, or maybe i've misunderstood the approach, if so ignore me

**Comment by damonbla** [comment]
Thanks about the sea floor comment - I actually need to remove it for our purposes, which involve a deeper sea anyway.

I am indeed reading the data back synchronously, with everything being done in a regular old Unity Update() function. I know it's not the best way to do this at all, but mostly so far I've just been trying to get something to work. Now that it is working, I'll look at making it asynchronous.

One thing I found was that quite a bit of that wasted processing time was simply on writing the pixels representing height into that texture. By making the shader do the texture writing (instead of SetPixels() in the Update function) I doubled the speed, though it's not quite working correctly. I've never written to textures with anything other than a fragment shader, so there's a bit of a learning curve. I'll let you know how the optimizations go.

Once again, thank you so much for the help! It's appreciated.

**Comment by huwb** [comment]
Sure

Reading the texture synchronously will force a flush of all the gpu commands, so essentially it will get the gpu to render an entire frame and stop and wait for the result to come back. so that should be a juicy optimisation..

**Comment by damonbla** [comment]
Thanks again! I've managed to double my performance, up to 15 fps, just by doing some of the texture processing asynchronously. I know I can go much faster too by doing the compute shader data reading asynchronously, but it's been a struggle so far. 

It's the Unity AsyncGPUReadbackRequest() stuff that is tripping me up. I see you are doing it Crest (QueryBase.cs has been a big help for my understanding of how to do all of this), but I haven't been able to get it working in my project. There are precious few resources online about how to use the AsyncGPURead class. I thought I had it, but it was actually slowing everything down instead of speeding it up (and not actually getting good data back), so I know something was wrong. I feel like I'm close though. I think it's related to keeping track of a list of queries and not just getting data as often as possible.

One unrelated and maybe obvious question: is the Crest wave simulation deterministic? When I hit play in Unity do the exact same waves get created every time, assuming I don't change any ocean settings? It seems like it is, but I wanted to double check.

**Comment by huwb** [comment]
Yeah it should be deterministic - if not we'd treat it as a bug so if you encounter this let us know.

I might close this as its not something on our list as an issue, but i'd welcome you to keep posting here, i'll receive notifications when you do.

**Comment by damonbla** [comment]
Sounds good! Makes sense that it should be closed.

I did finally manage to get this working with asynchronous GPU read requests, and it brought the performance up to around 24 fps. This should be fast enough to move ahead with the other work I wanted to do.

Thanks again for all your help!
