### ISSUE TITLE
Build underwater effects are very dark / do not match editor

### ISSUE THREAD

**Issue by hellstorm102** [crest-ocean/crest#413]
the settings i have in the editor for underwater look great, however they do not look like this in the built exe

**Screenshots / video**
These are very helpful to understand and diagnose issues.

![Untitled](https://user-images.githubusercontent.com/6035435/73498177-c5642580-4379-11ea-8b01-0ccfedb5481f.png)
left is editor, right is build

**Versions**
using 2018.3 version with editor at 2018.4.0f1

**To Reproduce**
? 

**Platform**
standalone win 64

**Hardware**
i9 9900k , 2080, valve index

**Additional context**
using VR, set to linear, forward , dx11

**Comment by huwb** [comment]
This might be if the material options/features on the underwater material don't match the features enabled on the ocean material. The toggles define how the shader is compiled and there needs to be a good match across both.

**Comment by hellstorm102** [comment]
greetings!

the issue was resolved by me updating the shaders variants and adding the 2 crest underwater shaders to the always included shaders. it looks perfect in build now!


thanks for the reply!
