### ISSUE TITLE
I don't see water in oculus quest

### ISSUE THREAD

**Issue by spexy90** [crest-ocean/crest#420]
**Describe the bug**
Hi, I'm trying to use crest in unity for oculus quest. The problem is that by starting the apk in oculus, I don't see water while everything works from unity. Maybe I have to set the scene somehow specific for oculus quest? 

Maybe it's a stupid mistake, these are my first tests with oculus quest ...

Thank you in advanced

**Screenshots / video**
From unity game player:  
![unityGamePlayer](https://user-images.githubusercontent.com/7711554/74342138-4e7f5180-4da9-11ea-95bc-60f86a662764.jpg)
From Oculus quest:
![From oculus quest](https://user-images.githubusercontent.com/7711554/74342141-4fb07e80-4da9-11ea-8387-bcb111304ad3.jpg)

**Log**
error:
Compute shader (UpdateShadow): Property (_ShadowMapTexture) at kernel index (0) is not set
Warning:
Virtual Reality SDK Oculus failed to initialize.
Will attempt to enable Oculus instead.
Assets\Oculus\Avatar\Scripts\OvrAvatar.cs(703,34): warning CS0168: The variable 'e' is declared but never used
Warning! Using more than 1 pixel lights on a mobile device may decrease performance severely. You can change the mobile quality settings in 'Project Settings -> Quality Settings'

**Versions**
Unity 2019.2.17f1 

**To Reproduce**
I simply imported the example scene from the crest package and I inserted the player controller for oculus quest...

**Platform**
Oculus Quest - Android

**Hardware**
Oculus Quest

**Comment by huwb** [comment]
Thanks for posting this. 

I haven't seen that error from the shadow stuff before. Could you disable "create shadow data" on the ocean renderer script and try again?

**Comment by spexy90** [comment]
Thank you for your answer. 

I have tried but nothing. In the end, I reset everything and did it all over again. Now it works ... maybe some settings lost along the way...

**Comment by huwb** [comment]
Ah ok sorry for the trouble
