### ISSUE TITLE
Question about applying Unity's Job System on Crest

### ISSUE THREAD

**Issue by EcoEditor** [crest-ocean/crest#422]
Hi @huwb 

We're using the Crest in a VR project and experience some lag in our scene (also due to our heavy assets...), however I wonder if it is a good idea to try and implement the Job System (available from 2018.1) on the OceanRenderer.cs script? So the rendering of the sea will be done on another thread.

Would you say it's a good approach?

**Comment by moosichu** [comment]
Hi @EcoEditor,

All of the calculations in Crest are done on the GPU. The CPU is not the bottleneck here and there aren't really many good candiates for jobification.

**Comment by huwb** [comment]
Just to add, the userguide has tips on performance optimization which may be worth checking out

**Comment by huwb** [comment]
Actually the info is in performance.md if you're using this github version

**Comment by EcoEditor** [comment]
Thanks, you right it's not what cause the frame rate to drop.
