### ISSUE TITLE
Creating a rogue wave

### ISSUE THREAD

**Issue by damonbla** [crest-ocean/crest#425]
This is really more of a question. I'm trying to artificially create a single much larger wave in the ocean simulation, and I can't seem to do it with the dynamic or animated wave inputs. What I mostly end up with is a standing bulge in the water, or I've even managed to create some interesting water tentacle monster type things. One time I managed to make what looked like an underwater nuclear explosion, but the water stayed up in the air for much too long to be usable. I could post a video of that effect if it would help.

The animated inputs make standing bulges (or indentations) based on the shape or texture that you give them. I thought I could "induce" a giant wave by taking advantage of something like the "Ripple Generator" in the example boat scene and jacking up the shader values, but that has not worked either. The ripples are too small, and actually, if I bring those scripts and the material into my own scene it doesn't even make any ripples. I'm not sure if that's my ocean settings, but I've looked and tried to make everything the same as the sample scene, so maybe not.

The real question is whether it's actually possible in the first place to create single rogue waves with any mechanism in Crest?

**Comment by moosichu** [comment]
You can render a wave as an animated wave input, but you willl need to manually animate it into a texture yourself. The alternative is to write your own script and shader to do so. Does that help? This kind of question could be better suited to our Discord channel: https://discord.gg/g7GpjDC

People in the help-and-advice section can be very helpful, and others have tried things like this before and good give good pointers. We respond there as well. Closing this issue, but if you have any more questions please feel to reply, or say hi on Discord!

**Comment by huwb** [comment]
> The animated inputs make standing bulges (or indentations) based on the shape or texture that you give them

Yes this is the way we would suggest doing it, add the shape you want and animate it as desired

**Comment by damonbla** [comment]
Thank you! I was actually wondering if there was something like a Discord channel for asking questions like this. I'll be sure to join up when I get a chance. I will also just attempt to make a good looking wave with an animated input and do it that way.
