### ISSUE TITLE
Boat Sample renders with grey ocean on iOS

### ISSUE THREAD

**Issue by mmaclaurin** [crest-ocean/crest#450]
1. New URP project
2. Import Crest 
3. Open Sample BoatDev/Scenes/boat
4. Set iOS as build target
5. Add boat scene to build
6. Build for iOS
7. Test build on iOS

Result: scene animates correctly, including bouyancy, but the ocean is entirely grey.

![IMG_1274](https://user-images.githubusercontent.com/911260/77233958-4369cf00-6b68-11ea-9aeb-6349223a3693.PNG)

in the XCode console (doesn't look related:)
Initialize engine version: 2019.3.6f1 (5c3fb0a11183)
2020-03-21 11:22:38.943791-0700 Crestest[370:100696] Unbalanced calls to begin/end appearance transitions for <SplashScreenController: 0x10495bd10>.
UnloadTime: 3.218792 ms
ArgumentNullException: Value cannot be null.
Parameter name: shader
  at Crest.OceanDebugGUI.Awake () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.GameObject.AddComponent[T] () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.GameObject:AddComponent()

**Versions**
URP 7.1.8
Unity 2019.3.6f1

**To Reproduce**
How can the developers reproduce this bug? Are you able to reproduce the issue in the example content/scenes?
Please include steps to reproduce the behaviour, with the example content ideally so we can follow the steps on our side.

**Platform**
- Running debug on iOS, building on Mac

**Comment by daleeidd** [comment]
I believe this is the same issue someone had on the discord. Let me know if it solves it for you:

> There might be a conflict with the render pipeline asset under graphics and under quality. Enabling the "post process" checkbox on the camera should fix it. The proper way to fix it is to either remove the render pipeline assets under the quality settings or updating them by porting over the correct settings from crest's pipeline asset (depth and opaque texture and render list). We'll try and make the asset more compatible with the default project template

**Comment by mmaclaurin** [comment]
Dale, you are correct and this did fix it. I did not realize that quality settings switch pipeline assets!

**Comment by daleeidd** [comment]
I'll leave this open until we address this with documentation or something. Thanks for reporting

**Comment by huwb** [comment]
Thanks @daleeidd . I gave the setup/installation documentation a big rewrite - if you feel like it check out userguide.pdf that i regenerated in my latest commit in URP.

It hopefully sidesteps this pitfall by getting the user to install URP, thereby creating a render pipeline config asset that will be already assigned in graphics/quality settings, rather than manually assigning the crest example config.

**Comment by mmaclaurin** [comment]
What actually caused the problem for me is that the default URP template
assigns different assets to Medium and High quality, medium was default on
my iPhone but high on my Mac. Presumably medium did not have the right
setup.

So while setting up URP is helpful, it's not where I was getting stuck - it
was the multiple pipeline assets in the default URP setup.

- Matt
