### ISSUE TITLE
Waves not properly rendered with small values of camera FOV

### ISSUE THREAD

**Issue by Efril** [crest-ocean/crest#453]
**Describe the bug**
Decreasing camera Field of View seems a standart way to make spyglass or binocular. But in Crest this method seems simply zoomed far LODs that look ugly.

**Screenshots / video**
FOV value is set to 1.875:
![TroubledWaters_UI_2020-03-23-21-15-18_1600x900](https://user-images.githubusercontent.com/20504421/77355736-0d8a3d80-6d56-11ea-88cc-b67aaf6989bb.png)
The same scene but FOV is 60 for comparison (all fine):
![TroubledWaters_UI_2020-03-23-21-15-11_1600x900](https://user-images.githubusercontent.com/20504421/77355826-37dbfb00-6d56-11ea-8d54-3feecf2b74f4.png)

**Log**
No logs

**Versions**
Built-in Unity renderer. Unity version: 2019.2.12f1

**To Reproduce**
1) Open 'main.unity' scene from Crest examples.
2) Run the scene.
3) Set 'Field of View' of 'DemoCamera' to 2.

**Platform**
Unity Editor on Windows 10

**Hardware**
Radeon RX 570

**Additional context**
Is there any workarounds? Maybe other zooming method which works with Crest?

**Comment by huwb** [comment]
Yeah narrow FOV is notoriously difficult for depth-based LOD techniques, and affects Crest quite badly.

It might be possible to tackle this by increasing the min scale on the OceanRenderer temporarily, to push detail further out away from the camera, and perhaps change normal map scale on the ocean material temporarily?

These are hacks that might make this workable. I can't think of what a more solid solution would look like.

**Comment by huwb** [comment]
I'll close but if you reply I'll get a notification so feel free to update this.
