### ISSUE TITLE
I am using Untiy 3D and there seems to be a problem with the foam. It doesn't seem to appear in the shoreline, but it does appear within the waves.

### ISSUE THREAD

**Issue by DanielleVisser** [crest-ocean/crest#457]
**Describe the bug**

**Screenshots / video**
These are very helpful to understand and diagnose issues.

**Log**
What is in the editor log? Clear before running and then provide any errors/warnings that appear. The log frequently provides the key hints.

**Versions**
Which render pipeline (built-in/LWRP/HDRP)? Which version of LWRP/HDRP? Which version of unity (including minor, i.e. 2019.1.0f2)? 

**To Reproduce**
How can the developers reproduce this bug? Are you able to reproduce the issue in the example content/scenes?
Please include steps to reproduce the behaviour, with the example content ideally so we can follow the steps on our side.

**Platform**
 - Editor or standalone?
 - Platform (win/mac/...)

**Hardware**
What hardware are you seeing the issue on? GPU model is particularly useful.

**Additional context**

**Comment by daleeidd** [comment]
Can you please fill out the form on how to reproduce (and other information)? The provided main scene should have foam at the shoreline. Thanks.

**Comment by huwb** [comment]
Not having a depth cache configured to calculate the water depths would result in this as well

**Comment by daleeidd** [comment]
Closing as looks like this has gone stale. If you are still continuing to have an issue, please respond to this thread and I will reopen.
