### ISSUE TITLE
Configuration crest version 6 with Dynamic water Physics 1

### ISSUE THREAD

**Issue by Cataldo90** [crest-ocean/crest#459]
I put the waterinterface.cs script in crest but it doesn't work with Crest.
can you help me configure it with dynamic water physics?

**Comment by huwb** [comment]
Hello, I think it requires DWP2 . It might be worth contacting the author to verify. We provide the API, dwp implements it.

**Comment by Cataldo90** [comment]
thanks for the answer, i need your help, is it possible to create a wake for my ship with a mustache? if it's possible you can help me maybe if you have a unity package already done.
Is the sea sketched?
thanks and best regards

**Comment by huwb** [comment]
unfortunately i didnt understand either of your questions, could you please elaborate. i will close this issue as it has been answered, but i will get notificaton if you reply here so feel free to continue this conversation. or our discord is a good place to ask questions to us and the community.

**Comment by Cataldo90** [comment]
sorry if I expressed myself wrong, my question was that there is a way to create a wake with my ship on CREST and sea spray?
Best Reguards 












Cataldo  Cataldo Russo
 Cal-Tek S.r.l. 
T +39 0984 494891| M +39 3318077810| info@cal-tek.euVia Ponte Pietro Bucci, Cubo 45C - Terzo Piano, Rende (CS) - Italywww.cal-tek.eu













Da: "Huw Bowles" notifications@github.com
A: "crest-ocean/crest" crest@noreply.github.com
Cc: "Cataldo90" c.russo@cal-tek.eu,"Comment" comment@noreply.github.com
Data: Thu, 02 Apr 2020 14:29:32 -0700
Oggetto: Re: [crest-ocean/crest] Configuration crest version 6 with Dynamic water Physics 1 (#459)



unfortunately i didnt understand either of your questions, could you please elaborate. i will close this issue as it has been answered, but i will get notificaton if you reply here so feel free to continue this conversation. or our discord is a good place to ask questions to us and the community.

**Comment by huwb** [comment]
we have rudimentary support for wakes, see boat.unity and threeboats.unity in the crest example scenes.

we dont have particle fx for spray but its on our list for the future..
