### ISSUE TITLE
Underwater reflection color

### ISSUE THREAD

**Issue by AntonisKl** [crest-ocean/crest#465]
### Information
- Unity 2019.3.7f1
- Built-in rendering pipeline
- Crest v10.0.0
- Platform: Windows 10
- GPU: Intel UHD graphics 630

### Bug description
Hello,
I noticed that from Crest v8.0.0 and forwards, the underwater reflections are displayed with wrong color (reddish). I notice this issue in the "main" scene from Crest examples v10.0.0 and when I include the Ocean Renderer in my own scene. You can see the issue in the below screenshot.
![image](https://user-images.githubusercontent.com/18524649/78471533-aba8db00-773a-11ea-9f4b-9c0331f497b8.png)

Any help would be appreciated.
Thank you.

**Comment by daleeidd** [comment]
Are you talking about the caustics? The texture was changed to a coloured one. The source file shows links to the original

https://github.com/crest-ocean/crest/blob/master/crest/Assets/Crest/Crest/Textures/Caustics/SOURCE.txt

**Comment by AntonisKl** [comment]
> Are you talking about the caustics?
Yes.
So, the expected behavior is for them to be displayed like this?

**Comment by daleeidd** [comment]
Yes. Ever since version 9.0.0.
