### ISSUE TITLE
Wave Fx scripts are not updated .

### ISSUE THREAD

**Issue by VizzzU** [crest-ocean/crest#466]
**Describe the bug**
I know it is just a "feature" but i love it .

**Screenshots / video**
These are very helpful to understand and diagnose issues.

**Log**
Sampling Data is no longer used so it throws an error.

**Versions**
All versions i guess

**To Reproduce**
Just import the scripts in unity .

**Platform**
both i guess

**Hardware**
//

**Additional context**
Hi Hub and other contributors , it's been a while ! Good to see that your project is still in great shape !!!!

**Comment by huwb** [comment]
Hi!

I guess you refer to the particle effects on the waves? As i noted on hte other issue you posted, i'm continuing the conversation over at #93 

I'll close this so we can consolidate there. If you were talking about something different let me know and i'll reopen.

**Comment by VizzzU** [comment]
Thx for the quick response as always !
