### ISSUE TITLE
Xbox One error: Crest requires graphic devices that support compute shaders

### ISSUE THREAD

**Issue by huwb** [crest-ocean/crest#469]
When targeting exbox one, Crest may throw an error on startup and not initialise

> Crest requires graphic devices that support compute shaders

**Comment by huwb** [comment]
**Resolution** DX12 must be set as the top/preferred API in the player settings for unity to work properly on Xbox One.

**Comment by xarcius** [comment]
Hi
I have this error on XBOX ONE S
I have set the settings:
Color Space: Linear
Graphics APIs: Direct3D12 (Expermental)
Don't work

Color Space: Gamma
Graphics APIs: Direct3D12 (Experimental)
Don't work

I'm using Unity 2018.4.12f1.
what can I do?

![error](https://user-images.githubusercontent.com/26920270/80894480-942e2500-8cdb-11ea-9c58-26c171e9c143.jpg)

**Comment by daleeidd** [comment]
@xarcius We have seen this before. Is #423 related to your issue?

There is also #303 but that is specific to shadows. So disabling shadows would be another good thing to try.

**Comment by huwb** [comment]
Is direct3d 12 at the top of the list of graphics API s in your settings?

Worth testing with a newer version of unity?

If these suggestions don't help, then I would file a bug report with unity.

**Comment by xarcius** [comment]
> 
> 
> @xarcius We have seen this before. Is #423 related to your issue?
> 
> There is also #303 but that is specific to shadows. So disabling shadows would be another good thing to try.

Great ! It's work. The solution is:
The missing thing was, that UWP is not treated as Game by default on XBox. It must be changed from app to game first. Apps are treaded as DX11 only.
Infos on how to configure xbox can be found: 
https://walbourn.github.io/directx-and-uwp-on-xbox-one/

**Comment by daleeidd** [comment]
@xarcius No worries. I am glad you have it working.

@huwb should we document this somewhere? Crest might be the first asset someone uses where this is an issue. It could go in the user guide or the wiki which can then be referred to by documentation?

**Comment by huwb** [comment]
Yeah potentially - where do you think makes sense? Q&A in userguide maybe?

**Comment by daleeidd** [comment]
I'll create a wiki page and link it from the _Which platforms does Crest support?_ question in the Q&A section to avoid bloat.

**Comment by daleeidd** [comment]
Done with e73d375708c482a5df9ac51aec1cc92ae17bc140. [Platform Support](https://github.com/crest-ocean/crest/wiki/Platform-Support)
