### ISSUE TITLE
Slow code on loops, arrays and indexing

### ISSUE THREAD

**Issue by Karu1977** [crest-ocean/crest#471]
The Crest ocean drops framerate in Unity significantly. May be it's particially by shader complexity, but still some calculations are made on CPU. I checked the cs-files and found several problems. This is obviuous for anyone, who knows how high-level language code is tranferred to machine commands. Computers become more and more powerful, but work more and more slow, because programmers don't know how their code works internally.

1. Explicite evaluation of array length on each iteration.
2. Multiple evaluation of same values (field access and indexing).
3. Index range checking optimization.

------------------------------------------------------------
1. Explicite evaluation of array length on each iteration.
------------------------------------------------------------

In the following fragment of code

`for (int i = 0; i < patchTypes.Length; i++)`

the array length is evaluated on each iteration, because code is not aware, is array changed between iteration or not, it's possible in mulithreading. This means get array reference in memory and access the length field, instead of holding the length in processor register. Such things should be replaced by

```
int  arrLen =  patchTypes.Length;

for (int i = 0; i < arrLen; i++)
```

-------------------------------------------------------------------------
2. Multiple evaluation of same values (field access and indexing).
-------------------------------------------------------------------------

Let's the the method QueryBase.UpdateQueryPoints. In many places two variables are used:

```
_segmentRegistrarRingBuffer.Current
_segmentRegistrarRingBuffer.Current._segments
```

which causes multiple evaluation of end token. Should be replaced by something like this

```
var srrbCurrent = _segmentRegistrarRingBuffer.Current;
var srrbCurrentSegments = _segmentRegistrarRingBuffer.Current._segments;
```

Using var is bad, I just don't know real types of variables. var is faster to write, but harder to understand, what is the real type behind. This confusing causes time wasting, trying to understand, what is it.

Next, let's check one of the loops.

```
for (int normi = 0; normi < countNorms; normi++)
{
    var arrIdx = segment.x + countPts + 3 * normi;

    _queryPosXZ_minGridSize[arrIdx + 0].x = queryNormals[normi].x;
    _queryPosXZ_minGridSize[arrIdx + 0].y = queryNormals[normi].z;
    _queryPosXZ_minGridSize[arrIdx + 0].z = minGridSize;

    _queryPosXZ_minGridSize[arrIdx + 1].x = queryNormals[normi].x + s_finiteDiffDx;
    _queryPosXZ_minGridSize[arrIdx + 1].y = queryNormals[normi].z;
    _queryPosXZ_minGridSize[arrIdx + 1].z = minGridSize;

    _queryPosXZ_minGridSize[arrIdx + 2].x = queryNormals[normi].x;
    _queryPosXZ_minGridSize[arrIdx + 2].y = queryNormals[normi].z + s_finiteDiffDx;
    _queryPosXZ_minGridSize[arrIdx + 2].z = minGridSize;
}
```

Excessive use of array indexing:
_queryPosXZ_minGridSize[arrIdx + 0] - evaluated 3 times instead of 1
_queryPosXZ_minGridSize[arrIdx + 1] - evaluated 3 times instead of 1
_queryPosXZ_minGridSize[arrIdx + 2] - evaluated 3 times instead of 1
queryNormals[normi] - evaluated 6 times instead of 1

Should be replaced by something like this:

```
for (int normi = 0; normi < countNorms; normi++)
{
    var arrIdx = segment.x + countPts + 3 * normi;
    Vector3 ni = queryNormals[normi];

    _queryPosXZ_minGridSize[arrIdx + 0] = new Vector3 (ni.x, ni.z, minGridSize);
    _queryPosXZ_minGridSize[arrIdx + 1] = new Vector3 (ni.x + s_finiteDiffDx, ni.z, minGridSize);
    _queryPosXZ_minGridSize[arrIdx + 2] = new Vector3 (ni.x, ni.z + s_finiteDiffDx, minGridSize);
}

```
And such things are all around.

```
var dz = -Vector3.forward * s_finiteDiffDx;
for (int i = 0; i < countNorms; i++)
{
    var p = _queryResults[firstNorm + 3 * i + 0];
    var px = dx + _queryResults[firstNorm + 3 * i + 1];
    var pz = dz + _queryResults[firstNorm + 3 * i + 2];

    normals[i] = Vector3.Cross(p - px, p - pz).normalized;
    normals[i].y *= -1f;
}
```

Multiple evaluation of (firstNorm + 3 * i) and multiple indexing. Should be replaced by

```
for (int i = 0; i < countNorms; i++)
{
    int ofs = firstNorm + 3 * i;
    var p = _queryResults[ofs+ 0];
    var px = dx + _queryResults[ofs + 1];
    var pz = dz + _queryResults[ofs + 2];

    Vector3 n = Vector3.Cross(p - px, p - pz).normalized;
    n.y = -n.y;
    normals[i] = n;
}
```

-------------------------------------------------------------------------
3. Index range checking optimization.
-------------------------------------------------------------------------

Also, index range checking is performed on each iteration, it's additional slowdown. for primitive types fixed statements and pointers should be used as much as possible

```
int [] someArray;
int i, arrLen = someArray.Length;

for (i = 0;   i < arrLen;   i++)
{
    // internally following checks are performed:
    // if ((i < 0)   ||   (i >= someArray.Length)
    // {
    //    throw ArgumentOutOfRangeException ();
    // }
    someArray [i] = someThing;
}

```
can be replaced as follows:

```
fixed (int* someArrayPtr = & someArray [0])
{
    for (i = 0; i < arrLen; i++)
    {
         someArrayPtr [i] = someThing;
    }
}
```

**Comment by huwb** [comment]
Hello, we replied on the discord that we did not believe that these would provide a tangible speedup. Things like this tend to either get picked up by the compiler, or pale in comparison to real perf issues (memory reads, etc). If you have evidence (data) to the contrary, please provide it (we'll get notifications from this thread even if closed).

Otherwise we welcome you to make these changes to your own fork, but we wont be merging this into our repos evidence that these actually provide a speedup.
