### ISSUE TITLE
HDRP Crest Ocean VR single-pass instanced gives error with underwater shader. 

### ISSUE THREAD

**Issue by Aldana-DigitalWizards** [crest-ocean/crest#475]
**Bug**
I was testing the HDRP Crest Ocean with VR and found that when I try to go underwater, I get this error, with single-pass instanced on.

**Log**
shader error in 'Hidden/Crest/Underwater/Post Process HDRP': syntax error : unexpected token '||' at HDRP/temp.hlsl(230) (on d3d11)Compiling Vertex program with STEREO_INSTANCING_ON
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_FULL_HDR
Shader error in 'Hidden/Crest/Underwater/Post Process HDRP': unexpected #else at HDRP/temp.hlsl(232) (on d3d11)Compiling Vertex program with STEREO_INSTANCING_ON
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_FULL_HDR
Shader error in 'Hidden/Crest/Underwater/Post Process HDRP': redefinition of 'InvViewProjection' at HDRP/temp.hlsl(233) (on d3d11)Compiling Vertex program with STEREO_INSTANCING_ON
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_FULL_HDR

**Versions**
HDRP render pipeline
Version of HDRP 7.1.8
Unity version 2019.3.5f1

**To Reproduce**
I used the scene example main. Since I was trying it with VR I then changed the multi-pass to single-pass instanced. I followed the steps to add the underwater effect to the camera. Then if you try to place the camera underwater you will get an error.

**Platform**
 - Platform: VR, windows

**Additional context**
I tried it using multi-pass and the underwater effect works but not in single-pass instanced.

**Comment by daleeidd** [comment]
Thanks. The will be fixed by the next release. I'll leave this open until then.

**Comment by daleeidd** [comment]
Although, this issue will be fixed in next release, there is a still a bug with single pass instanced and the underwater effect. It only renders in the left eye. We are looking into this.

**Comment by daleeidd** [comment]
This particular issue has been resolved in release 4.1. Just to reiterate that HDRP underwater still doesn't work 100% in VR single pass instanced.
