### ISSUE TITLE
[URP] Shader Inputs/Flow/Fixed Direction doesn't work on Metal

### ISSUE THREAD

**Issue by huwb** [crest-ocean/crest#488]
**Describe the bug**
Using the shader *Inputs/Flow/Fixed Direction* doesn't work on Metal. Throws this error:

> Metal: Error creating pipeline state (Crest/Inputs/Flow/Fixed Direction): fragment shader color output does not have enough component for the pixel format (MTLPixelFormatBGRA8Unorm_sRGB)

I don't understand why the flow target is a BGRA8 when it should be RGHalf?

**Screenshots / video**
*These are very helpful to understand and diagnose issues.*

**Versions**
Crest URP I think? 4.1?
Unity 2019.3.10f1

**To Reproduce**
Use fixed flow direction input on Metal.

**Platform**
 - Editor / OSX

**Hardware**
MacBook Pro 2014, osx 10.13.6

**Additional context**
*Add any other context about the problem here.*

**Comment by huwb** [comment]
@daleeidd could you please take a swing at this? thanks!

**Comment by klauskobald** [comment]
Here come more details:
I am using URP on  unity 2019.3.10, Editor, MacBook Pro 2014, osx 10.13.6
If you need a demonstration, we can do a jitsi (or similar) talk.

**Comment by daleeidd** [comment]
I added a PR which will clear the error #489 

@huwb For me I got two errors:

```
Metal: Error creating pipeline state (Crest/Inputs/Flow/Fixed Direction): fragment shader color output does not have enough components for the pixel format (MTLPixelFormatBGRA8Unorm_sRGB)
(null)
Metal: Error creating pipeline state (Crest/Inputs/Flow/Fixed Direction): fragment shader color output does not have enough components for the pixel format (MTLPixelFormatRGBA16Float)
(null)
```

These errors are due to the Material Preview in the inspector. No preview for the material is shown, but if I fix the error it does. I'm going to submit a bug to Unity.

@klauskobald This error won't stop the shaders from working. You might have another issue. Are you sure that flow is setup correctly?

**Comment by klauskobald** [comment]
@daleeidd no, I am not sure, if I setup up correctly. That was the reason for my first mail. The error was popping up, so I added it to the mail. Unfortunately there is no documentation about adding a flow. It is also not clear to me, if the flow would be visible or if it needs another component.
The whirlpool example creates 3. But I guess that‘s not the right place to discuss that topic.

**Comment by daleeidd** [comment]
@klauskobald Apologies if the error caused confusion.

The following should get flow fixed direction working:
- On the _OceanRenderer_ component make sure the flow checkbox is enabled.
- On the ocean material make sure flow checkbox is enabled.
- An input will be a mesh with the flow input material (one with shader _Crest/Inputs/Flow/Fixed Direction_ in your case) set and the _RegisterFlowInput_ component added.

Make sure the mesh covers the area you want and experiment with some of the properties on the flow input material. You should see results.

**Comment by klauskobald** [comment]
Hi, I started over and also added some foam. It was not clearly visible without the foam. So, thanks.

**Comment by daleeidd** [comment]
Thanks. I'll close this issue.

**Comment by huwb** [comment]
Thanks @daleeidd 

The flow section seemed to be missing your steps from above so I've added it now so its in line with the ocean input types:

> To turn on this feature, enable the "Create Flow Sim* option on the *OceanRenderer* script, and ensure the *Flow* option is ticked on the ocean material.
