### ISSUE TITLE
Sampling ocean physics globally (rather than the LOD based on the camera)

### ISSUE THREAD

**Issue by GainDeveloper** [crest-ocean/crest#490]
Currently physics appears to be tied to the LOD defined by the rendering camera. This causes problems when teleporting the camera between different physics objects in the scene (especially the further away the object is from the camera).
Of course this could not support all effects tied directly to the camera (dynamic waves ect.) but could perhaps be solved by the physics sampling the gerstner waves directly?

**Comment by moosichu** [comment]
I can see why this would be valuable. We haven't had that many requests for this feature and it would be a significant amount of work to get it working.

The main issue is that we need to ensure that the height query results on the CPU match the result on the GPU *exactly*, or you will get really weird behaviour. 

Some parts of this are non-trivial, and become increasingly non-trivial the more features there are.

For example, flow, depth and (in an upcoming feature) shorelines can all dramatically affect the shapes of gerstner waves. And the actual sources of these data *are* view dependent (unless we change how they work) and that would be a harder problem to solve.

https://github.com/crest-ocean/crest/pull/157
https://github.com/crest-ocean/crest/pull/268

We do have these old branches would could be of use. I think for now, unless there is more demand, we won't be supporting such a feature as we don't have the capacity to do so right now. Especially as supporting such a feature would take an awful lot of resources.

Is that a good summary of the situation @huwb?

**Comment by huwb** [comment]
Exactly. You can also add arbitrary shapes directly to the surface or modify it in arbitrary ways using shaders.

I think those branches you referenced are indeed worth looking into. Let us know if you have luck with them.

**Comment by GainDeveloper** [comment]
Thanks for the information! My use case doesn't require a lot of the camera dependent features so these branches should help.

Thanks!
