### ISSUE TITLE
Almost on all Androids - RenderTexture.Create failed: format unsupported for random writes - RG16 SFloat (46).

### ISSUE THREAD

**Issue by klauskobald** [crest-ocean/crest#493]
I get millions of these errors in the log.
Any idea, where I can change to a texture format, that works on Oculus Quest?
I found one location in LodDataMgrShadow: return RenderTextureFormat.RG16;
But changing that did not alter the error output.

**Comment by moosichu** [comment]
Hi, if you can please share all the log messages and different callstacks for where this error is printed we can help make a solution to this. Without more information there isn't much we can do.

**Comment by klauskobald** [comment]
This is happening on 80% of the tested android devices via googles automated pre-launch report. They all support opengl 3.1 + 

2020-06-16T21:32:15Z Error RenderTexture.Create failed: format unsupported for random writes - R16 SFloat (45).
Crest.BuildCommandBuffer:LateUpdate()

2020-06-16T21:32:15Z Error RenderTexture.Create failed: format unsupported for random writes - R8 UNorm (5).
Crest.BuildCommandBuffer:LateUpdate()

2020-06-16T21:32:15Z Error RenderTexture.Create failed: format unsupported for random writes - RG8 UNorm (6).
UnityEngine.Rendering.RenderPipelineManager:DoRenderLoop_Internal(RenderPipelineAsset, IntPtr)

2020-06-16T21:32:15Z Error RenderTexture.Create failed: format unsupported for random writes - RG16 SFloat (46).
UnityEngine.RenderTexture:GetDepthBuffer()
Crest.LodDataMgrPersistent:BuildCommandBuffer(OceanRenderer, CommandBuffer)
Crest.BuildCommandBuffer:Build(OceanRenderer, CommandBuffer)
Crest.BuildCommandBuffer:LateUpdate()

2020-06-16T21:32:15Z Error RenderTexture.Create failed: format unsupported for random writes - R16 SFloat (45).
UnityEngine.RenderTexture:GetDepthBuffer()
Crest.LodDataMgrPersistent:BuildCommandBuffer(OceanRenderer, CommandBuffer)
Crest.BuildCommandBuffer:Build(OceanRenderer, CommandBuffer)
Crest.BuildCommandBuffer:LateUpdate()

2020-06-16T21:32:15Z Error RenderTexture.Create failed: format unsupported for random writes - RG16 SFloat (46).
Crest.BuildCommandBuffer:LateUpdate()

**Comment by daleeidd** [comment]
Crest doesn't support OpenGL. Does the issue occur if you use Vulkan instead of OpenGL? Not sure if the graphics API makes a difference with this issue, but it is worth a try.

**Comment by klauskobald** [comment]
ok - so now I am confused! I have only OpenGLES3  in the Unity graphic settings! Why is this working at all, then? I will remove it and put vulkan there.

**Comment by klauskobald** [comment]
the change to vulkan did not really improve things. error is still there, however it seems, that it occurs less often. Unfortunatly most of devices did not send complete logs for some reason. actually all devices stall after about 70 seconds  except for google pixel 4. 
but it might be the change of the other issue regarding the compute buffer size causing the stall. So I will change this back now and try again.

**Comment by daleeidd** [comment]
> Why is this working at all, then?

It might seem to work in OpenGL. There are API differences between OpenGL and others like coordinates for example. So it might seem to work but ultimately it won't work correctly. I am not sure if OpenGL is causing this problem though.

> except for google pixel 4

Does that mean it is functioning correctly for that device? Or has the logs revealed anything?

> So I will change this back now and try again.

Thanks for keeping us updated.

**Comment by klauskobald** [comment]
wow - that´s complicated. 
Unfortunately I can not retrieve any usefull information from the logs. As I want to publish my update somewhen and the optical fidelity is not number one priority I decided to do this:
I now have built an ocean abstraction layer with common interfaces, so I can implement any number of ocean systems ranging from a flat plane up to crest. 
People can now choose and try.

**Comment by klauskobald** [comment]
this is the log from one of the devices that run on googles prelaunch system. it´s a samsung SM-G960U1.
But it´s the same on almost all other android devices.

2020-07-28T16:49:41Z Log Install-ID: 813827-144763-715105-942607
2020-07-28T16:49:42Z Log Addressables - runtime data operation completed with status = Succeeded, result = UnityEngine.AddressableAssets.Initialization.ResourceManagerRuntimeData.
2020-07-28T16:49:42Z Log Addressables - loading initialization objects.
2020-07-28T16:49:42Z Log Addressables - loading content catalogs, 1 found.
2020-07-28T16:49:42Z Log Addressables - loading content catalog from jar:file:///data/app/com.sfinxit.dyb-QsmZM5ihHLlZORPxXuCZRA==/base.apk!/assets/aa/catalog.json.
2020-07-28T16:49:42Z Log Using configuration builder objects
2020-07-28T16:49:42Z Error RenderTexture.Create failed: format unsupported for random writes - RG16 SFloat (46).
UnityEngine.RenderTexture:GetDepthBuffer()
Crest.LodDataMgrPersistent:BuildCommandBuffer(OceanRenderer, CommandBuffer)
Crest.BuildCommandBuffer:BuildLodData(OceanRenderer, CommandBuffer)
Crest.BuildCommandBuffer:BuildAndExecute()

2020-07-28T16:49:42Z Warning !last repeated: 7
2020-07-28T16:49:42Z Error RenderTexture.Create failed: format unsupported for random writes - R16 SFloat (45).
UnityEngine.RenderTexture:GetDepthBuffer()
Crest.LodDataMgrPersistent:BuildCommandBuffer(OceanRenderer, CommandBuffer)
Crest.BuildCommandBuffer:BuildLodData(OceanRenderer, CommandBuffer)
Crest.BuildCommandBuffer:BuildAndExecute()

2020-07-28T16:49:42Z Warning !last repeated: 3
2020-07-28T16:49:42Z Error RenderTexture.Create failed: format unsupported for random writes - RG16 SFloat (46).
Crest.BuildCommandBuffer:BuildAndExecute()

2020-07-28T16:49:42Z Warning !last repeated: 15
2020-07-28T16:49:42Z Error RenderTexture.Create failed: format unsupported for random writes - R16 SFloat (45).
Crest.BuildCommandBuffer:BuildAndExecute()

2020-07-28T16:49:42Z Warning !last repeated: 7
2020-07-28T16:49:42Z Error RenderTexture.Create failed: format unsupported for random writes - R8 UNorm (5).
Crest.BuildCommandBuffer:BuildAndExecute()

2020-07-28T16:49:42Z Warning !last repeated: 3
2020-07-28T16:49:42Z Error RenderTexture.Create failed: format unsupported for random writes - RG8 UNorm (6).
UnityEngine.Rendering.RenderPipelineManager:DoRenderLoop_Internal(RenderPipelineAsset, IntPtr)

2020-07-28T16:49:42Z Warning !last repeated: 3
2020-07-28T16:49:42Z Error RenderTexture.Create failed: format unsupported for random writes - RG16 SFloat (46).
UnityEngine.RenderTexture:GetDepthBuffer()
Crest.LodDataMgrPersistent:BuildCommandBuffer(OceanRenderer, CommandBuffer)
Crest.BuildCommandBuffer:BuildLodData(OceanRenderer, CommandBuffer)
Crest.BuildCommandBuffer:BuildAndExecute()

2020-07-28T16:49:42Z Warning !last repeated: 7
2020-07-28T16:49:42Z Error RenderTexture.Create failed: format unsupported for random writes - R16 SFloat (45).
UnityEngine.RenderTexture:GetDepthBuffer()
Crest.LodDataMgrPersistent:BuildCommandBuffer(OceanRenderer, CommandBuffer)
Crest.BuildCommandBuffer:BuildLodData(OceanRenderer, CommandBuffer)
Crest.BuildCommandBuffer:BuildAndExecute()

2020-07-28T16:49:42Z Warning !last repeated: 3
2020-07-28T16:49:42Z Error RenderTexture.Create failed: format unsupported for random writes - RG16 SFloat (46).
Crest.BuildCommandBuffer:BuildAndExecute()

2020-07-28T16:49:42Z Warning !last repeated: 15
2020-07-28T16:49:42Z Error RenderTexture.Create failed: format unsupported for random writes - R16 SFloat (45).
Crest.BuildCommandBuffer:BuildAndExecute()

2020-07-28T16:49:42Z Warning !last repeated: 7
2020-07-28T16:49:42Z Error RenderTexture.Create failed: format unsupported for random writes - RG8 UNorm (6).
UnityEngine.Rendering.RenderPipelineManager:DoRenderLoop_Internal(RenderPipelineAsset, IntPtr)

2020-07-28T16:49:42Z Warning !last repeated: 3
2020-07-28T16:49:42Z Error RenderTexture.Create failed: format unsupported for random writes - RG16 SFloat (46).
UnityEngine.RenderTexture:GetDepthBuffer()
Crest.LodDataMgrPersistent:BuildCommandBuffer(OceanRenderer, CommandBuffer)
Crest.BuildCommandBuffer:BuildLodData(OceanRenderer, CommandBuffer)
Crest.BuildCommandBuffer:BuildAndExecute()

2020-07-28T16:49:42Z Warning !last repeated: 7
2020-07-28T16:49:42Z Error RenderTexture.Create failed: format unsupported for random writes - R16 SFloat (45).
UnityEngine.RenderTexture:GetDepthBuffer()
Crest.LodDataMgrPersistent:BuildCommandBuffer(OceanRenderer, CommandBuffer)
Crest.BuildCommandBuffer:BuildLodData(OceanRenderer, CommandBuffer)
Crest.BuildCommandBuffer:BuildAndExecute()

2020-07-28T16:49:42Z Warning !last repeated: 3
2020-07-28T16:49:42Z Error RenderTexture.Create failed: format unsupported for random writes - RG16 SFloat (46).
Crest.BuildCommandBuffer:BuildAndExecute()

2020-07-28T16:49:42Z Warning !last repeated: 15
2020-07-28T16:49:42Z Error RenderTexture.Create failed: format unsupported for random writes - R16 SFloat (45).
Crest.BuildCommandBuffer:BuildAndExecute()

**Comment by huwb** [comment]
Guess this is why urp avoids using compute shaders - patchy support for some features like this.

You could try setting the texture format in loddatamgrseafloordepth.cs from r16 to r32 to see if that helps.

Not sure there's an elegant solution to this I'm afraid.

**Comment by klauskobald** [comment]
whatever I put there does not help. I found out that when I put vulkan as first choice at least the ocean is rendered correctly where when opengl is first all the borders to terrain are rendered with rectangular edges.
so, the next question is: how can we suppress spamming the log?

**Comment by huwb** [comment]
i dont think we support opengl at all. Dale actually just added verification to make sure opengl is not active.

so in vulkan it works, but you get spam in the log? the above errors, even though it works?

**Comment by klauskobald** [comment]
I inspected more carefully and see that animated/dynamic waves, foam, shadow data are NOT created but depth cache seems to work, at least I can see shallow water color. When I turn off all "create" settings I still get texture erros for
RG16 SFloat (46).
R8 UNorm (5).
RG8 UNorm (6).
I did not see that before. So - damn!
I still have opengl as 2nd option for devices that do not support vulkan - app switches to a flat "fake" ocean then.
So, is there anything we can do? I really would like to bring this to an end after 4 months :-)

**Comment by huwb** [comment]
Are they coming from crest? I dont think we create textures of those types

**Comment by klauskobald** [comment]
you are right, there is one error from crest:

```
07-31 20:58:33.984  4122  4249 E Unity   : RenderTexture.Create failed: format unsupported for random writes - RG16 SFloat (46).
07-31 20:58:33.984  4122  4249 E Unity   : Crest.BuildCommandBuffer:BuildAndExecute()
07-31 20:58:33.984  4122  4249 E Unity   : Crest.OceanRenderer:RunUpdate()
07-31 20:58:33.984  4122  4249 E Unity   : Crest.OceanRenderer:LateUpdate()
```

and others from the URP!
any idea why this is? That cannot been  overseen by Unity!?
```
07-31 20:58:33.994  4122  4249 E Unity   : [./Runtime/Graphics/RenderTexture.cpp line 444] 
07-31 20:58:33.994  4122  4249 E Unity   : (Filename: ./Runtime/Graphics/RenderTexture.cpp Line: 444)
07-31 20:58:33.994  4122  4249 E Unity   : 
07-31 20:58:33.995  4122  4249 E Unity   : RenderTexture.Create failed: format unsupported for random writes - RG8 UNorm (6).
07-31 20:58:33.995  4122  4249 E Unity   : UnityEngine.Rendering.ScriptableRenderContext:InitializeSortSettings(Camera, SortingSettings&)
07-31 20:58:33.995  4122  4249 E Unity   : UnityEngine.Rendering.ScriptableRenderContext:InvokeOnRenderObjectCallback_Internal_Injected(ScriptableRenderContext&)
07-31 20:58:33.995  4122  4249 E Unity   : UnityEngine.Rendering.Universal.UniversalRenderPipeline:RenderSingleCamera(ScriptableRenderContext, CameraData, Boolean, Boolean)
07-31 20:58:33.995  4122  4249 E Unity   : UnityEngine.Rendering.Universal.UniversalRenderPipeline:RenderCameraStack(ScriptableRenderContext, Camera)
07-31 20:58:33.995  4122  4249 E Unity   : UnityEngine.Rendering.Universal.UniversalRenderPipeline:Render(ScriptableRenderContext, Camera[])
07-31 20:58:33.995  4122  4249 E Unity   : UnityEngine.Rendering.RenderPipeline:InternalRender(ScriptableRenderContext, Camera[])
07-31 20:58:33.995  4122  4249 E Unity   : UnityEngine.Rendering.RenderPipelineManager:DoRenderLoop_Internal(RenderPipelineAsset, IntPtr)

```

**Comment by huwb** [comment]
Android device hardware fragmentation sucks? :)

Maybe the crest one is the depth data? Have you disabled all the ocean features?

**Comment by klauskobald** [comment]
oceandepth is still running.

**Comment by huwb** [comment]
Yeah you can turn off oceandepth to remove our error if it helps, and then you'll need to see if unity can help with the other errors..

I'll close but we'll get notifications if you reply, curious to hear how it goes.

**Comment by klauskobald** [comment]
if I turn off crest, no error is produced bei URP. So I am pretty sure unity will tell me to repair "my" (crest) code.
can you tell me how this URP thing works?
I am trying to remote debug Android. 
What methods are called actually?
The only method called each frame is OceanChunkRenderer::BeginCameraRendering. (breakpoint stopps)
OnWillRenderObject is never called.

**Comment by klauskobald** [comment]
so, I found that there is the foam setting where textureformat can be selected. 
RFloat works on Android.
why did you make to choose it? I cannot see a difference between Half and Float.  
I changed all *Half with *Float, which seems to work on Android, meaning, it throws no errors. Still checking - it seems that most effects do not really show or look different from what I see in the editor. So, I guess the math is maybe not working correctly, can that be? I am afraid that every gpu might need different formats. Maybe the TextureFormat methods should automatically select a working format by probing the gpus capabilities?
The whole thing gets more and more complicated.

**Comment by huwb** [comment]
Half takes less memory than float, that's why it's the default. It's fine to use float.

If there's a capability for it we could hook into it. I'll have a look later.

**Comment by huwb** [comment]
There's a "loadstore" check that can be done on a graphics format but there's a user reporting it doesn't work which doesn't look promising

https://forum.unity.com/threads/in-place-texture-compute-support-uav-loads-support-check-not-in-unity.712361/

**Comment by klauskobald** [comment]
You could consider a "ProbeGraphicsCapabilities.CreateTexture(desc)" System which tries out all available formats and returns only the most promising Format to the LodDataMgr. If none is returned, it should disable the feature and fire an event, that "our" code can listen to. I did not check, if these errors can be caught, but if so, that should be pretty easy to implement.

**Comment by huwb** [comment]
I'll add it to our list, thanks
