### ISSUE TITLE
GUIDs not being flushed in compute water height query code

### ISSUE THREAD

**Issue by huwb** [crest-ocean/crest#495]
In the compute height query system, queries are made with an identifying GUID. This registers the query and the GUID is used to track it across frames.

Right now we are never flushing GUIDs which is bad - firstly the number of query GUIDs grows montonically, eventually throwing the "max guids" error. Secondly i believe queries are uploaded and processed if they are present, even if they're no longer being actually used.

There are at least 3 mechanisms we could use:

1. SegmentRegistrarRingBuffer.RemoveRegistrations(guid) could be called when a query is no longer active. This would be ideal, but seems error prone - how/when is this called? If it was C++ it could be on the SampleHeightHelper destructor. I looked at an equivalent in C# but it wasn't obvious.
2. Alternatively SegmentRegistrarRingBuffer.ClearAvailable() is supposed to clear out any requests that are not active, but I don't recall anymore how its supposed to know what is active, and I think i tried calling it and nothing happened, but i didnt investigate deeply.
3. The most extreme approach would be to have all query GUIDs registered from scratch every frame - so clear the registrations when a new registry is acquired using AcquireNew(). I think this works but may generate some memory churn - some dictionaries will be repeatedly cleared and repoopulated every frame. 

I think i'm leaning towards option 3. Thoughts @daleeidd @moosichu ?

**Comment by moosichu** [comment]
`I looked at an equivalent in C# but it wasn't obvious.`

The [IDisposable](https://docs.microsoft.com/en-us/dotnet/api/system.idisposable?view=netcore-3.1) interface is the standard way of doing this. You have to call it explicitly, but a lot of IDEs actually provide nice support and hints to make sure you do call it, and Unity use it extensively with their NativeArrays.

Option3: If we do that, I would recommend using NativeHashMap instead of a C# Dictionary to avoid garbage generation on that churn.

**Comment by huwb** [comment]
Thanks. Looking at it, the code is manually populating the registrar every time its acquired i and have no idea why. I simply removed it in the above referenced commit.

Thanks for the NativeHashMap note. Given we were already calling Clear() on the dictionary and repopulating which did not generate garbage, not sure if its worth moving, and the documentation has 0 information so its not very inviting. Are we happy to stick with dictionary in this case, or are there benefits from moving to the native one?

**Comment by moosichu** [comment]
Unity recommend using native containers by default unless you can't for a reason (eg. you are working with managed types). However, I forgot that NativeArray is the only built-in "stable" NativeContainer, and that all the other ones are in preview: https://docs.unity3d.com/Packages/com.unity.collections@0.8/manual/index.html So actually Dictionary for now is good. If there is no garbage in the profiler that's all good.

**Comment by huwb** [comment]
Thanks - i'll create a PR.

For my understanding, do you have a link for that recommendation, if its in writing somewhere? I hadn't realised the native containers were recommended over the managed types for general use - very interesting.

**Comment by moosichu** [comment]
> Thanks - i'll create a PR.
> 
> For my understanding, do you have a link for that recommendation, if its in writing somewhere? I hadn't realised the native containers were recommended over the managed types for general use - very interesting.

Unfortunately no because it came from a conversation I had in person with one of their engineers, I can look for something in writing.

**Comment by huwb** [comment]
Ah ok fair. If you do find something let me know. Just trying to get straight in my head that going to from managed to native for operations on the native containers is beneficial over the managed versions.

**Comment by huwb** [comment]
#496 merged
