### ISSUE TITLE
Water Effects for big ships

### ISSUE THREAD

**Issue by superamble** [crest-ocean/crest#503]
We would need to create water effects on big ships such as big stern waves (I have seen them herehttps://youtu.be/ekng3c43Y1E?t=59)

Is there any documentation about it?

**Comment by daleeidd** [comment]
There are both [Animated Waves](https://github.com/crest-ocean/crest/blob/master/USERGUIDE.md#animated-waves) and [Dynamic Waves](https://github.com/crest-ocean/crest/blob/master/USERGUIDE.md#dynamic-waves). They are very likely Dynamic Waves which is what we use for boat wakes in the example scenes. Have a look at boat.unity for dynamic waves and threeboats.unity for animated waves examples.

I'll close this for now. If you need more assistance there is the discord server or reply here.
