### ISSUE TITLE
Cull distances error in planar reflection script

### ISSUE THREAD

**Issue by huwb** [crest-ocean/crest#504]
**Describe the bug**
From discord user BaaBaa:

I keep getting this error randomly when entering playmode:

UnityException: Array needs to contain exactly 32 floats for layerCullDistances.
UnityEngine.Camera.set_layerCullDistances (System.Single[] value) (at <480508088aee40cab70818ff164a29d5>:0)
Crest.OceanPlanarReflection.ForceDistanceCulling (System.Single farClipPlane) (at Assets/Crest/Crest/Scripts/Reflection/OceanPlanarReflection.cs:247)
Crest.OceanPlanarReflection.OnPreRender () (at Assets/Crest/Crest/Scripts/Reflection/OceanPlanarReflection.cs:212)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Screenshots / video**
These are very helpful to understand and diagnose issues.

**Versions**
built-in rp

Which version of unity (including minor, i.e. 2019.1.0f2)? 

**To Reproduce**
How can the developers reproduce this bug? Are you able to reproduce the issue in the example content/scenes?
Please include steps to reproduce the behaviour, with the example content ideally so we can follow the steps on our side.

**Platform**
 - Editor or standalone?
 - Platform (win/mac/...)

**Hardware**
What hardware are you seeing the issue on? GPU model is particularly useful.

**Additional context**

**Comment by GeorgeDziov** [comment]
Dunno if it's still helpful but that happens when you disable scene reloading in the 
[Project settings->editor tab->domain reloading]

**Comment by daleeidd** [comment]
@GeorgeDziov is that with latest Crest? I cannot reproduce.

**Comment by GeorgeDziov** [comment]
I think so, downloaded it a few days ago, got the same issue when messing with domain reloading. Not critical to me personally, just thought it may help that BaaBaa dude. Can send the script for a look if needed, maybe I've imported the wrong version after all (btw is there any way to check the version inside the Crest folder itself?)

Forgot to say I'm using built-in RP at the moment, forward rendering, Unity 2020.2f1 on my i7 with GTX1080

**Comment by daleeidd** [comment]
@GeorgeDziov that's the old version. We don't do releases anymore for built-in so there are no versions. The [README](https://github.com/crest-ocean/crest#installation) has more information on how to get latest Crest

**Comment by GeorgeDziov** [comment]
Thanks for letting me know, will be sure to download from there from now on!
