### ISSUE TITLE
isUnderwater in .shader code and depending .hlsl files

### ISSUE THREAD

**Issue by Rastos78** [crest-ocean/crest#508]
Hi,
I would like to know how to create a function in a shader to know if a worldPos point is underwater and have a list of all the dependencies, please.
No matter how hard I look, I can't find it.

**Comment by huwb** [comment]
The clip surface feature has a "remove convex hull" shader which computes the water height at a position, in the shader.

*RegisterClipSurfaceInput.cs* has the setup code that binds the necessary data to the shader.

*ClipSurfaceConvexHull.shader* is the shader, which has code like this:

`
				float3 surfacePositionWS = SampleOceanDataDisplacedToWorldPosition
				(
					_LD_TexArray_AnimatedWaves,
					input.positionWS,
					_DisplacementSamplingIterations
				);

				// Move to sea level
				surfacePositionWS.y += _OceanCenterPosWorld.y;

				// Write red if underwater
				if (input.positionWS.y > surfacePositionWS.y)
				{
					clip(-1);
				}
`

"Write red if underwater" is comparing against the ocean height in `surfacePositionWS.y`.

We are exploring making this kind of thing simpler but that's the current system.

**Comment by Rastos78** [comment]
I duplicated and modified UnderwaterShared.hlsl to IsUnderwater.hlsl:
-Added the mention include in the shader referred to shader.
-Replaced _OceanCenterPosWorld.y to the position.y of ocean (0).
-but for _LD_TexArray_AnimatedWaves it's more complicated...

**Comment by Rastos78** [comment]
Even if I put the targeted shader in the right folder by adding the "#include OceanLODData.hlsl" it gives me the following error:

`Shader error in 'MicroSplat/Terrain': Unexpected identifier "Texture2DArray". Expected one of: typedef const void inline uniform nointerpolation extern shared static volatile row_major column_major struct or a user-defined type at Assets/Crest/Crest/Shaders/OceanLODData.hlsl(20)`

I'll consider your suggestion, the script I put it where I want to put it, right?

**Comment by moosichu** [comment]
Are you trying to do this from a surface-shader? If so you need to do some things if you want access to D3D11 fetures like texture arrays:

https://docs.unity3d.com/Manual/SL-PlatformDifferences.html

**
![image](https://user-images.githubusercontent.com/10348641/82147146-b5e3ec00-9845-11ea-86e0-0dc9288a8379.png)
**

**Comment by Rastos78** [comment]
With this syntax I can declare them:
`UNITY_DECLARE_TEX2DARRAY(_LD_TexArray_AnimatedWaves);`
And I created a script to synchronize it, of course.

I rewrote the functions I need in the target shader, but I got this error:
`Shader error in 'Target Shader': Unexpected token '('. Expected one of: ',' ';' at line 202`
Which corresponds to this line:
`const half4 data = i_dispSampler.SampleLevel(LODData_linear_clamp_sampler, i_uv_slice, 0.0);`

Thanks for your answer.

**Comment by Rastos78** [comment]
It's okay, I succeeded!
Thanks for the help.

**Comment by huwb** [comment]
Glad to hear. Would be curious to know what you are building if you can disclose? No worries if not!

**Comment by Rastos78** [comment]
I want the water to wet the ground as it passes through 😄
