### ISSUE TITLE
Resolution dependent horizontal line on the horizon with MSAA and fog

### ISSUE THREAD

**Issue by daleeidd** [crest-ocean/crest#511]
**Describe the bug**
When MSAA is enabled there appears a noticeable horizontal line at the horizon. It is most noticeable when fog is enabled. The issue is camera orientation and viewport resolution dependent.

**Screenshots / video**

![Screen Shot 2020-05-15 at 3 17 53 pm](https://user-images.githubusercontent.com/5249806/82123787-9665a880-97de-11ea-81ea-83edbd34c1e8.jpg)
The issue

![Side by side comparison](https://user-images.githubusercontent.com/5249806/82123866-07a55b80-97df-11ea-9156-8a0a89bc62e8.png)
Side-by-side comparison with fog enabled and without fog enabled

**Versions**
Built-in
URP

**To Reproduce**

1. Checkout branch dev/test-presets
2. Scale vertical resolution until line appears

**Platform**
 - Editor
 - Mac

Need to test on standalone and Windows.

**Additional context**
I'll try renderdoc tomorrow and see what I can find.

**Comment by huwb** [comment]
May be another case where something is using the averaged depth - average of furthest ocean distance and skybox distance (very large), leading to a highly fogged line?

**Comment by daleeidd** [comment]
It appears so. Had another quick look at this and it isn't an issue with Crest. Happens with a normal plane too. Looks like it is also fixed in URP since Unity is address MSAA issues for URP but not BIRP.

**Comment by huwb** [comment]
Ah good test. Also reminds me that we have the test material option on the ocean component which could help sanity check this kind of thing in the future as well.
