### ISSUE TITLE
PrefabStageUtility not found error when importing

### ISSUE THREAD

**Issue by hedgefield** [crest-ocean/crest#521]
**Describe the bug**
Hi, when importing the latest master branch (072a900) into 2019.3.10, I get the error `The name 'PrefabStageUtility' does not exist in the current context`.

**Log**
Assets\Crest\Crest\Scripts\OceanRenderer.cs(275,17): error CS0103: The name 'PrefabStageUtility' does not exist in the current context
Assets\Crest\Crest\Scripts\OceanRenderer.cs(346,17): error CS0103: The name 'PrefabStageUtility' does not exist in the current context

**Versions**
BIRP 2019.3.10f on Windows 10

**To Reproduce**
Clone the repo and import into that Unity version.

**Additional context**
The Unity docs list PrefabStageUtility as an experimental API, so they might have changed its location or function since the unity version the repo project was compiled in (I believe I saw it was 2018.4).

**Comment by huwb** [comment]
Apologies for this, thanks for the report. Fixed on latest.
