### ISSUE TITLE
Ocean lighting issues when using Enviro 2.0.3

### ISSUE THREAD

**Issue by superamble** [crest-ocean/crest#524]
I have the same problem that andgeno is describing in this post:
https://github.com/crest-ocean/crest/issues/294

I have seen the solution that VizzzU explained but since I am using an older version of Enviro I can't find the scripts that he was mentioning.

**Comment by moosichu** [comment]
https://github.com/crest-ocean/crest/wiki/How-to-use-Crest-with-Enviro let us know if this helps.

**Comment by daleeidd** [comment]
Thank you for reporting. I'll close this for now. Please respond to this issue if you need further assistance or have more information. We'll be notified.
