### ISSUE TITLE
MipMaps size killing the ocean

### ISSUE THREAD

**Issue by shredsimonster** [crest-ocean/crest#525]
Unity 2019.3 has started puking this in the debug and refuses to generate the ocean:

Graphics.CopyTexture called for entire mipmaps with different memory size (source (RGBA8 sRGB) is 11664 bytes and destination (RGBA8 sRGB) is 64 bytes)
UnityEngine.Graphics:CopyTexture(Texture, Int32, Int32, Texture, Int32, Int32)

I'm trying to backtrack my changes as it was working fine for a while but can't seem to find out what has started causing this problem. Could it be lighting settings? But even resetting those isn't fixing it. 

Haven't touched the shaders or scripts. Using it in different scenes within the same project won't work, but opening in other projects still works, so I've raked through the project settings but can't find what I'm supposed to have changed.

Thanks!

**Comment by shredsimonster** [comment]
Found it! In 'Project Settings' > 'Player' > 'Rendering' you can't switch your 'Lightmap Encoding' to anything but 'High Quality' otherwise the mipmap problem occurs. Might be useful including this in the documentation?

**Comment by shredsimonster** [comment]
aaand it's back, this time the lightmap settings weren't changed from 'high quality', so it's got to be something else...

I'm on an iMac retina late 2014, running Mojave btw.

**Comment by huwb** [comment]
Thanks for reporting. I've reopened.

Could you please give more details about versions. Which render pipeline if any, or are you using latest version from this github? Which OS and version. Thanks.

Could you give the full error - if you click it in the log window it should show a call stack. Also perhaps pick the first error, as there might be another error that happens first which is the real root of the problem.

**Comment by huwb** [comment]
Oh sorry you posted that it's an iMac, so ignore my question about OS, just the other bits then.

@daleeidd  @moosichu don't suppose this error looks familiar?

**Comment by daleeidd** [comment]
@huwb I haven't seen that one before. My MacBook is from 2014 but I am running Catalina.

**Comment by shredsimonster** [comment]
Hi guys, so i'm on the URP, meaning I chose the old '3D Project' at the beginning because I wanna run a volumetric lighting plugin that's not optimised for the new pipelines. I'm on Mojave 10.14.6

Thanks for the help guys! Problem is I can't replicate the error because I'm not sure what is causing it. For now the Ocean is rendering again in the Game Window and in builds...

**Comment by daleeidd** [comment]
@shredsimonster Thanks. I'll close this for now. Happy to re-open if you come across this again.
