### ISSUE TITLE
Your Low Res Tutorial Videos Feature Unreadable Text

### ISSUE THREAD

**Issue by XLjedi** [crest-ocean/crest#527]
I can't read the blurry text of anything you put in a video.  Could you PLEASE use a resolution that at least allows me to read the text!  Watching your videos can be borderline infuriating.  I can't read anything on the screen.

**Comment by huwb** [comment]
Hello, they appear like this for me on my laptop:

![image](https://user-images.githubusercontent.com/939901/83356234-a93eb800-a35c-11ea-8e0f-321ab2e3f28d.png)

You should see a settings button at the bottom of the the video - is the resolution set to a low value for you?

**Comment by XLjedi** [comment]
Ah!  ...it was definitely user error on my part then.

My video settings were set at "Auto" and were defaulting to a very low res.

LOL, now I may be able to make sense out of these videos, thank you!

**Comment by huwb** [comment]
Good to hear
