### ISSUE TITLE
[URP] Underwater Curtain/Meniscus broken in URP 7.4.1

### ISSUE THREAD

**Issue by daleeidd** [crest-ocean/crest#531]
**Describe the bug**
Underwater effects does not render. Both the curtain and meniscus.

**Screenshots / video**

![Bildschirmfoto_2020-06-05_um_10 51 07](https://user-images.githubusercontent.com/5249806/83934581-83e6f980-a7f5-11ea-9309-4caaa8cc4890.jpg)

**Log**
Nothing logged.

**Versions**
Crest 4.2
URP 7.4.1+
Unity 2019.4+

**To Reproduce**
Go underwater in main scene.

**Platform**
 - Editor
 - Mac

Haven't tested other platforms

**Additional Notes**
I checked the frame debugger, the curtain draw call is there but nothing renders. Also, 7.4.1 is not verified for 2019.4.

**Comment by huwb** [comment]
Is this maybe that issue where you need to toggle a feature on the underwater curtain material to get the shader to work? 

(@EliGould actually i seem to remember you reported the underwater curtain not working in the past - we seem to get this sometimes and simply toggling an option on the material seems to wake it up :/, but i could not figure out why. mentioning you in case its helpful).

**Comment by daleeidd** [comment]
I gave it a try and it didn't fix it.

**Comment by daleeidd** [comment]
I looked into it further. The curtain material preview is black when normally it would be an ocean colour. Also, the meniscus doesn't work either. Looks like it is something else.

**Comment by Snigros** [comment]
Daleeidd - thanks for your previous reply re my post in regard to #533.  I agree that the symptoms I am experiencing would appear to be this bug (I am also using the same product versions).

**Comment by daleeidd** [comment]
@Snigros No worries.

For anyone using 2019.4 and want this working, please consider using URP 7.3 (verified for 2019.4). I couldn't see anything in the change log that would be the cause. I will most likely submit a bug to Unity tomorrow.

**Comment by Snigros** [comment]
Daleeidd thanks for your reply.  I had swapped to URP 7.4.1 to see if it fixed a minor terrain billboard rendering issue I was experiencing (and I hadn't noticed that URP 7.4.1 wasn't verified for 2019.4). 

I can confirm that swapping back to URP 7.3.1 has fixed this issue (for me at least!).   Thanks again for your assistance.  Cheers, S

**Comment by NiekoEugenijus** [comment]
Might this be the problem?

![image](https://user-images.githubusercontent.com/40171814/85026724-b4c61780-b181-11ea-9e93-71177611493a.png)
And
NullReferenceException: Object reference not set to an instance of an object
Crest.UnderwaterEffect.Validate (Crest.OceanRenderer ocean, Crest.ValidatedHelper+ShowMessage showMessage) (at Assets/Plugins/Crest/Crest/Scripts/Helpers/UnderwaterEffect.cs:293)
Crest.UnderwaterEffect.Start () (at Assets/Plugins/Crest/Crest/Scripts/Helpers/UnderwaterEffect.cs:66)

**Comment by daleeidd** [comment]
@NiekoEugenijus Thanks. I have already handled that exception which will be fixed for 4.4. That cbuffer notice won't be the issue either.

I'll check again tomorrow. I think it might have something to do with the vertex part of the shader.

**Comment by daleeidd** [comment]
I couldn't work this out so I submitted a bug to Unity today. I will post here with updates.

**Comment by daleeidd** [comment]
I had another look and it looks like the `unity_CameraToWorld._13_23_33` is inverted. If I invert it, it works correctly. I am under the assumption that this matrix is safe to use without being concerned about platform specific issues like z-flipping. So I am hesitant to fix it as it could be working fine for most people despite the number of reports we get. I have updated the case with Unity.

We could pass the camera forward in ourselves with scripting. I might resort to that if I hear nothing from Unity before the next release.

**Comment by huwb** [comment]
That's pretty bizarre, have no idea why that would or could be flipped for some people. It almost seems like the value is not being set properly in the pass setup then (maybe it's uninitialised and taking whatever value is there from previous draw calls, but I doubt that is the case).

We could pass it in yes.

**Comment by daleeidd** [comment]
Will be fixed in 4.5

**Comment by Snigros** [comment]
FYI...I had been sticking with 2019.4.7f,  URP 7.3.1 and Crest 4.4 as a workaround to this issue.  Migrating to 2020.1.1f1,  URP 8.2.0 and Crest 4.4 provided a noticeable (overall) performance boost - so I would like to proceed with this stream going forward.   However the Underwater Curtain/Meniscus is also broken when using this combination....

**Comment by daleeidd** [comment]
Fix will still be in for 4.5 and beyond. But here is the Unity issue for this bug:

https://issuetracker.unity3d.com/product/unity/issues/guid/1257518

**Comment by daleeidd** [comment]
4.5 is released which solves this issue. Eventually we can revert this fix once Unity has fixed it on their end.

**Comment by Snigros** [comment]
Thanks for the 4.5 update.  I just tried using it with Unity 2020.1.2f1 and URP 8.2.0 - but underwater issue still there in my project unfortunately.  Probably has no bearing but I am also using Cinemachine cameras (2.6.0 and just tried 2.6.1) and Direct3D12.  To do this test I:

(a) made a new copy of my 2019.4.8f1 project (which works properly with URP 7.3.1 and Crest URP 4.4); (b) deleted the Crest files outside of Unity (c) upgraded the whole project to 2020.1.2f1, and then, (d) imported the new Crest 4.5 package e.g. the usual sort of update process.  Everything worked as expected - except the underwater effects.

FYI...
Cheers, S

**Comment by daleeidd** [comment]
@Snigros does re-import the underwater curtain material before entering play mode fix it?

**Comment by Snigros** [comment]
Yes it does!  

Thanks so much for pointing this out - and for the regular updates - much appreciated.  Cheers, S
