### ISSUE TITLE
[HDRP] Caustics appear on underside of ocean surface with dynamic resolution

### ISSUE THREAD

**Issue by daleeidd** [crest-ocean/crest#532]
**Describe the bug**

Reported by discord user ibby

From discord:
> I've got the caustics popping in out and on the water surface. When looking up from below.

> It's actually using dynamic resolution. I'm upscaling from 90% and as soon as I take out Allow Dynamic Resolution from my camera it works like in the main demo scene.

I believe this is the ocean mask for the underwater effect being the wrong size.

**Screenshots / video**

![crest_1](https://user-images.githubusercontent.com/5249806/83935551-fc51b880-a7fd-11ea-95aa-8223764ede34.jpg)
![crest_2](https://user-images.githubusercontent.com/5249806/83935553-fe1b7c00-a7fd-11ea-8ebf-e8edfb40e95f.jpg)

**Versions**
HDRP 4.2 

**To Reproduce**
I haven't reproduced this. But enabling dynamic resolution and "upscaling from 90%" should reproduce the issue.

**Additional context**

We've had similar issue where the ocean mask is wrong size. Using the new RTHandles is a step to solving this. But it might require some more work on the mask renderer shader itself. Currently, the render textures scale up fine but we have had issues in the past when scaling down since Unity doesn't resize them in that case. The end result is the mask is misaligned and/or a different scale to the actual ocean surface.

**Comment by huwb** [comment]
Thanks @daleeidd . Might already be your plan but it may be worth digging around existing PP effects to see how they handle it?

**Comment by daleeidd** [comment]
All good. I just had to apply both RTHandle scales to the UVs. I have dynamic resolution working so it should be good for 4.3.

**Comment by huwb** [comment]
Nice!

**Comment by daleeidd** [comment]
This will be fixed for Crest 4.4.

**Comment by daleeidd** [comment]
4.4 is out which fixes this issue. Please open an issue if you notice anything wrong.
