### ISSUE TITLE
Crest for Planets, need a direction

### ISSUE THREAD

**Issue by Arugin** [crest-ocean/crest#535]
Hello, I am developing space sim game and want to use Crest in it.
The problem is, that there is the Solar System in real scale in the game and there is no such thing as Y-up, that Crest needed. Aslo everything is constantly moving, rotating, etc.
I understand that this problen is out of scope of original asset, so I want to try to integrate it myself. Before I begin a heavy research I have some questions  to understand if it is even possible.

1. How much Creast is relying on Y-up? It is only in some places or everything is wired to it?
2. I have already my own Quadtree Planet generation system with lods and other stuff, is it possible to just apply crest ocean material to quads I am generating? What data I should pass from my Quad Mesh to materail to get it work?
3. I bought HDRP version of the asset, and I see that Ocean shader was generated using shader graph, but I see no graph itself in the assets. Do you plan to add it the future, so users can make changes to the shader?

Thanks in advance.

**Comment by huwb** [comment]
1. There is a strong assumption of "top down" in the system. All the wave data and everything is generated using top down orthographic projections. The systems sample it by converting XZ to a UV coord. So it's quite a deep assumption at the moment.
2. should be possible in theory yes
3. Shader graph has limitations so we need to convert it to shader code and patch the generated code. But we could make the source graph available if it's still helpful.

**Comment by huwb** [comment]
1. Actually I guess top down isn't necessarily the issue, it's more if it needs to be aligned with the y axis, as you noted. I'm not sure how many things assume or require this. I guess the key questions are how this orthographic/flatland data maps to a sphere, and how to compute UVs.

**Comment by Arugin** [comment]
Thanks for you answers. If p.2 in theory is possible, then I already have correctly generated quad sphere meshes and uvs for it. So I will try to investigate if it is possible to swap fixed worldspace y-axis, to "configurable" y-axis and see how it goes. If I will be able to port at least waves, it would be great.

**Comment by huwb** [comment]
Would be interested to see how it goes, let us know

It's worth checking out the 2 crest talks we gave if you havent seen them already

**Comment by huwb** [comment]
I'll close this as we're not planning to do more work right now but please let us know how it goes (we'll get notifications if you reply).

**Comment by Arugin** [comment]
> It's worth checking out the 2 crest talks we gave if you havent seen them already

I've lost links to these talks and for some reason couldn't find them anymore. Could you please post these links here?

**Comment by huwb** [comment]
the talks are on these pages (unfortunately i cant link more directly to the talk within the page but just search for 'crest')

https://advances.realtimerendering.com/s2013/index.html
https://advances.realtimerendering.com/s2017/index.html

**Comment by Arugin** [comment]
Thanks!
