### ISSUE TITLE
[URP] Cracks between ocean lods with enabled dynamic batching

### ISSUE THREAD

**Issue by kroer** [crest-ocean/crest#536]
If enable dynamic batching in URP, holes appear between lods of ocean.

Windows 10, Unity 2019.3.9f, URP

![Annotation 2020-06-08 175607](https://user-images.githubusercontent.com/10652194/84052841-678fbc00-a9b1-11ea-853e-25c5b334a45f.png)

**To Reproduce**
 - create new project using URP template
 - remove all from scene except light and camera
 - create empty object and add OceanRenderer to it
 - disable Dynamic Batching in URP settings

**Comment by huwb** [comment]
Hello, does this occur in the Game view? Things can look a bit odd in the Scene view at times.

**Comment by kroer** [comment]
Yes. Forgot to mention that I changed "Geometry Down Sample Factor from" 2 to 8. But it reproduces with 2 also.

![Annotation 2020-06-08 201148](https://user-images.githubusercontent.com/10652194/84065484-bd219400-a9c4-11ea-840a-24fe805f3106.png)

**Comment by daleeidd** [comment]
> Forgot to mention that I changed "Geometry Down Sample Factor from" 2 to 8

That's the actual cause of the problem. Set the value lower (2 or 4) and you will see the gaps disappear.

On a side note I should be able to add some validation for this.

**Comment by kroer** [comment]
You are right, thanks. But why it doesn't work with 8? Are there any restrictions on "Lod Data Resolution" and "Geometry Down Sample Factor" ratio?

**Comment by huwb** [comment]
Ask yes thanks @daleeidd . 8 seems to break the mechanism that welds tiles from different LODs together. It's a complex issue and I want able to fix it on the past so it's a constraint.

There are some minor restrictions, these are already checked by the system. (Like resolution must be a multiple of down sample factor - otherwise it's not a factor..)

@daleeidd yes good idea, could you clamp it to 4 in OnValidate?

**Comment by daleeidd** [comment]
Will do

**Comment by daleeidd** [comment]
I've added validation to the help box branch so we should see this in 4.3. There is a warning if base mesh density (LOD resolution x 0.25 ÷ down sampling factor ) goes below 8 which is when gaps appear.

@kroer I should mention that gaps appear based on both _LOD Data Resolution_ and _Geometry Down Sampling Factor_. So increasing either of them will close the gaps.

**Comment by kroer** [comment]
I tried LOD Resolution 256 and down sample factor = 4.LOD resolution x 0.25 ÷ down sampling factor = 16. The situation is even worse.

![Annotation 2020-06-09 173546](https://user-images.githubusercontent.com/10652194/84168440-b1db7080-aa77-11ea-8ab9-43445419a2c7.png)

![Annotation 2020-06-09 173920](https://user-images.githubusercontent.com/10652194/84168860-35955d00-aa78-11ea-9eb0-0b9ee45ddd3f.png)

PS: screen from different projects.

**Comment by daleeidd** [comment]
@kroer Apologies. You are correct. Dynamic batching does have an effect. Will investigate.

**Comment by daleeidd** [comment]
Dynamic batching does indeed raise the base mesh density requirement. We can simply disable batching by adding `"DisableBatching" = "True"` to the shader tags of the Ocean shader.

Having to double the base mesh density to accomodate batching doesn't sound like a good trade off. I think GPU instancing will be a more safe route for reducing draw calls. What do you think @huwb?

**Comment by huwb** [comment]
Ah right - i haven't really considered dynamic batching before and i'm not convinced something like dynamic batching can work with the ocean tiles - i'm not sure how per-tile shader properties would be properly set.

I agree with disabling batching given this and what you wrote above about vert count. Does this resolve the issue?

**Comment by daleeidd** [comment]
Done. Will make its way into 4.3

Strangely, dynamic batching is enabled for built-in. But it doesn't affect Crest like it does in URP where it is disabled. I had to recheck my base mesh density formula just to ensure that it wasn't dynamic batching all this time causing the problem. The formula still appears to be correct.

**Comment by daleeidd** [comment]
4.3 has been released. Reopen if you still experience the issue.
