### ISSUE TITLE
Editor error: 'Segment registrar scratch exhausted'

### ISSUE THREAD

**Issue by huwb** [crest-ocean/crest#539]
The error

> Segment registrar scratch exhausted

Can be spammed to the console in some scenarios in the editor. 

Repro: run the game with the Scene and Game windows in the background (so bring up an Animation window or something to make them background tabs). I think if nothing is rendering, then the async readbacks of the collision queries dont process and the ring buffer gets blocked up.

**Comment by moosichu** [comment]
Which version of Crest is this? I get this in empty Unity projects (if I'm not mis-remembering) so I don't think this is a Crest issue.

**Comment by huwb** [comment]
All of them i think. Its an error from our code.

I did find a repro in the end - will add to the above

**Comment by huwb** [comment]
Think we can just pretty much ignore this and just remove the error. I've created a PR with a few more notes linked above ^.

**Comment by daleeidd** [comment]
This might be related. I have come across this a few times:
```
ArgumentException: Slice start + length (1) range must be <= array.Length (0)
Unity.Collections.NativeSlice`1[T]..ctor (Unity.Collections.NativeArray`1[T] array, System.Int32 start, System.Int32 length) (at /Users/builduser/buildslave/unity/build/Runtime/Export/NativeArray/NativeSlice.cs:102)
Unity.Collections.NativeSliceExtensions.Slice[T] (Unity.Collections.NativeArray`1[T] thisArray, System.Int32 start, System.Int32 length) (at /Users/builduser/buildslave/unity/build/Runtime/Export/NativeArray/NativeSlice.cs:25)
Crest.QueryBase.RetrieveResults (System.Int32 guid, UnityEngine.Vector3[] displacements, System.Single[] heights, UnityEngine.Vector3[] normals) (at Assets/Crest/Crest/Scripts/Collision/QueryBase.cs:318)
Crest.QueryBase.Query (System.Int32 i_ownerHash, System.Single i_minSpatialLength, UnityEngine.Vector3[] i_queryPoints, UnityEngine.Vector3[] o_resultDisps, UnityEngine.Vector3[] o_resultNorms, UnityEngine.Vector3[] o_resultVels) (at Assets/Crest/Crest/Scripts/Collision/QueryBase.cs:530)
Crest.SampleHeightHelper.Sample (System.Single& o_height) (at Assets/Crest/Crest/Scripts/Collision/SamplingHelpers.cs:52)
Crest.UnderwaterEffect.LateUpdate () (at Assets/Crest/Crest/Scripts/Helpers/UnderwaterEffect.cs:108)
```

I haven't been able to determine what causes it though.

**Comment by huwb** [comment]
Ha I've never seen that.. so you don't have a repro for it?

Could it be specific to osx?

We can probably guard against it but I'm really curious to understand it more of you have any more info.

**Comment by daleeidd** [comment]
I have seen the error come from the OceanRenderer too (Happen in the same session). If I remember correctly, I was doing something with git so it was either reimporting or recompiling so it might be abnormal circumstances. I tried reproducing by doing the above to no success. I'll let you know if I see it again.

**Comment by huwb** [comment]
Ah ok interesting. if you get it again let me know. i think probably just adding a guard, maybe edit-mode only, would nail this. but think i'd like to let it happen again rather than put in preemptive code now.
