### ISSUE TITLE
ambient lighting (foam) may be off (HDRP) when using _IndirectMultipliers.x

### ISSUE THREAD

**Issue by dkyeck** [crest-ocean/crest#560]
in case you use _IndirectMultipliers combined with "Probes = Off" (sky ambient only) ambient lighting may be off as it would  pick up the indirect multiplier twice: sky ambient already contains the indirect multiplier, probes do not.

so depending on the ambient or probe mode you have to treat sh lighting differently.

**Comment by daleeidd** [comment]
We made a few changes in 4.4 with the indirect multiplier. Can you please recheck once you have updated and let me know if this is still something you need.

Also, apologies, but I don't really understand the issue. Could you explain it a bit more? Instructions on how to setup the main scene to reproduce this will help a lot. Thanks.

**Comment by daleeidd** [comment]
Crest HDRP 4.5 has light layer support added. With HDRP 8.2 you will be able to make even more adjustments with the indirect lighting controller.

I'll close this one for now. If you manage to re-evaluate then please let us know your findings here.
