### ISSUE TITLE
Weird edge at top of bump wave travelling 45°

### ISSUE THREAD

**Issue by StarChick971** [crest-ocean/crest#565]
I made a bump wave using _Add from texture_ shader with this texture: 
![WaveTopDown_straight](https://user-images.githubusercontent.com/54045907/86112886-d5b73280-bac8-11ea-8f5a-48d9d0cfe00b.png)

I attached that bump to a moving _GameObject_ **travelling 45 degrees across the ocean plane** but the ocean mesh vertices are so regular that you can notice the gap on diagonal creating "dent" shape at top of wave as in this picture:
![image](https://user-images.githubusercontent.com/54045907/86111468-13b35700-bac7-11ea-93df-6b933d309df6.png)
It is quite visible in in wireframe:
![image](https://user-images.githubusercontent.com/54045907/86111496-1d3cbf00-bac7-11ea-995a-056bcdf986cb.png)

Just copy-paste my red bump texture above to use as add bump texture then rotate the gameobject 45° and move it along teh forward axis, you should be able to see in some positions the dent edge appearing.

Note: Tested on _Windows 10 x64_ under _Unity 2019.4.0f1 URP_ in Editor but that also happens with other versions too (first noticed since 2019).

**Comment by huwb** [comment]
The shape in that texture is too 'sharp' for the mesh at that resolution. Smoothing it out a bit would help. Or increasing lod data resolution on the ocean component would add more verts/resolution which would help, but add cost.

Our surface mesh uses an edge layout which minimises this kind of artifacts, but they can still happen if there is a lot of curvature in the shape like the above example..
