### ISSUE TITLE
HDRP underwater not working with MSAA

### ISSUE THREAD

**Issue by TerabyteTim** [crest-ocean/crest#570]
I was told to put this here by the Unity support contact for help determining a solution.

I have found that with the "MSAA Within Forward" option turned on in my HDRP settings asset, the underwater effect does not work. 

First image is with "MSAA Within Forward" off, working as expected. 
The second image is with "MSAA Within Forward" on, broken.

![image](https://user-images.githubusercontent.com/12587315/86275690-7fa9c400-bb88-11ea-97e1-d6a04ed09779.png)
![image (1)](https://user-images.githubusercontent.com/12587315/86275694-820c1e00-bb88-11ea-954a-88bfe6fc3577.png)

I wanted to see if this was a known limitation, or a bug that can be fixed. 
A quick reply would be greatly appreciated so we know how to move forward, thanks!

**Comment by daleeidd** [comment]
Thanks. I was able to reproduce. We don't have a fix for this yet unfortunately. It is likely that MSAA is messing with a scene depth calculation. Will look further into this.

**Comment by daleeidd** [comment]
4.5 is released which solves this issue.
