### ISSUE TITLE
Ocean tiles culled at edges of frustum

### ISSUE THREAD

**Issue by daleeidd** [crest-ocean/crest#585]
**Describe the bug**
Ocean tiles are culled at edge of frustum when they shouldn't be.

**Screenshots / video**
![2](https://user-images.githubusercontent.com/5249806/87247358-fea2d480-c485-11ea-8b7b-fdcdd73cb8da.jpg)
![3](https://user-images.githubusercontent.com/5249806/87247481-ad471500-c486-11ea-84a7-130381f88959.jpg)
![4](https://user-images.githubusercontent.com/5249806/87247486-b3d58c80-c486-11ea-94bc-b0154c9e223f.jpg)

**Versions**
4.4 and higher. Not sure if earlier. Looks like all pipelines. 

**To Reproduce**
In the boat.unity, weigh in the global spectrum to increase turbulence which will help with exposes culling issues.

**Platform**
 - Editor and Standalone
 - Windows and Mac

**Hardware**
i7 and GTX 1080Ti

**Additional context**
I disabled the culling done in _LateUpdateTiles_ and disabled occlusion culling in camera and on tile renderers just to rule them out, but the issue still appears. It might have something to do with the displacement of the tiles pushing tiles that would be culling into the frustum?

**Comment by huwb** [comment]
Thanks for reporting

The gerstner waves are supposed to report the amount of horizontal displacement they're generating to the ocean renderer, and then the ocean chunk renderers should then expand the bounds of the tiles to cover all possible vert positions, so they don't cull if they could be on screen.

If the tile GOs are made visible and the draw bounds option is enabled on the ocean chunk renderer, it should draw expanded bounds, and the amount of expansion should depend on amount of chop in gerstner waves. Turning down the gerstner waves should result in the bounds reducing in size.

That's the theory - I tried looking into it and encountered multiple layers of things I don't understand. Maybe these systems have rotted over time and there might be a few bugs. Or I was just seeing dodgy things and need to reimport the project or something.

I ran out of time to look into it for now. If you feel like digging @daleeidd feel free, or I'll pick it up next time.

**Comment by daleeidd** [comment]
Will do. I'll just post what I find as I work it out. In the following I disabled the renderer for one tile and enabled it's draw bounds option:

![0](https://user-images.githubusercontent.com/5249806/87271556-220d6400-c506-11ea-9331-3a49f4fa832e.jpg)

**Comment by daleeidd** [comment]
In play mode, if I toggle the problem chunk renderers (disable then enabled), they fix themselves and now scale with the chop correctly.

I found that all bounds have the correct values, but for some reason are not reflected in rendering.

A solution is the not use a shared mesh. In the _Start_ function, if I changed from _sharedMesh_ to _mesh_, it works fine. This breaks instancing (SPI should still work fine though).

I wonder if this is a bug in Unity because of the first sentence above.

I am going to start exploring DrawMesh and DrawMeshInstanced.

**Comment by huwb** [comment]
Oh, well found. That could indeed be a unity bug. Yes that sounds like a plan.

So it seems like we're forced to not use shared mesh then for now?

**Comment by huwb** [comment]
Terrible idea but is toggling renderer.enabled on/off once on startup enough to bring it to life? Just wondering if theres a hacky workaround.

**Comment by daleeidd** [comment]
I have looked further into this and I think I have come to the correct conclusion this time round.

> So it seems like we're forced to not use shared mesh then for now?

That would be the quickest and simplest way to solve this.

It appears that shared meshes also have shared bounds. The last LOD tiles to assign to the bounds controls the size. It appears that when I toggle the LOD_0 chunk renderers in play mode, all I am doing is changing the ordering and making them the controllers of the shared bounds. I was focused on the smaller LODs so I didn't notice the change in the larger ones. We already noticed this issue in #549.

We could find a way to manage mesh bounds outside of the shared mesh, and only assign to the shared mesh when needed like in PreCull. I am not sure if this would work as it depends how culling is done in relation to the event (after all have executed at once or after each event). I'll have to give this a go.

> I am going to start exploring DrawMesh and DrawMeshInstanced. Getting it working for testing if easy enough, but didn't make things any better.

I was mistaken here. I had some other debug code that interfered. If we went with this route, we would be controlling the frustum culling ourselves I believe. It looks like DrawMeshInstanced works one-to-one except I have noticed jitters.

**Comment by huwb** [comment]
Hmm it's tempting to frustum cull ourselves. We're already doing some types of culling anyway.

It's a bit annoying as if we do this there's almost no point having tile game objects at all. The thing we do get from mesh renderers is the render pass setup including lighting values, reflection probes, etc. I can't see how we could do our own setup for the different pipelines and maintain it over time.

I think we should just move back to mesh from shared mesh. We could optionally post on the unity forum that the bounds should be on the renderer, not the mesh, but maybe there are reasons they have it like this.

**Comment by daleeidd** [comment]
Sounds good.
