### ISSUE TITLE
unused code in ObjectWaterInteraction.cs

### ISSUE THREAD

**Issue by klauskobald** [crest-ocean/crest#587]
I think that line can be removed, right?

            var rnd = 1f + _noiseAmp * (2f * Mathf.PerlinNoise(_noiseFreq * ocean.CurrentTime, 0.5f) - 1f);

rnd is never used

**Comment by daleeidd** [comment]
Thanks. It can be. I will have to do a sweep for unused code. I am unsure if this was planned to be used because it became unused as part of a "revert" natured commit. It was previously applied to velocity before being made unused.

**Comment by huwb** [comment]
I think it can be nuked, take. We should look at adding randomness to the dynamic waves so that they look more random and natural. This simple approach didn't really work

**Comment by daleeidd** [comment]
Thanks. Unused code has been removed. I'll close this since I don't think anyone else will report it.
