### ISSUE TITLE
Dynamic Waves crashes when Sea Floor Depth and Flow are not enabled

### ISSUE THREAD

**Issue by daleeidd** [crest-ocean/crest#588]
**Describe the bug**
Dynamic Waves no longer work correctly when Sea Floor Depth and Flow simulations are not running. The dynamic waves dissipate as they speed away.

Loading Unity with both disabled will prevent Crest from working. It crashes builds.

**Screenshots / video**

![21](https://user-images.githubusercontent.com/5249806/87541941-b4fbf900-c6d4-11ea-82a1-5db085c78b4b.jpg)
Loading Unity with a scene with both Flow and Sea Floor Depth disabled and Dynamic Waves enabled.

**Log**

From crash in build:
```
Begin MonoManager ReloadAssembly
- Completed reload, in  0.095 seconds
Metal RecreateSurface[0x111b856d0]: surface size 2880x1800
UnloadTime: 0.827029 ms

Native stacktrace:

	0   libmonobdwgc-2.0.dylib              0x0000000116413656 mono_handle_native_crash + 242
	1   libmonobdwgc-2.0.dylib              0x000000011637432d mono_sigsegv_signal_handler + 220
	2   libsystem_platform.dylib            0x00007fff6ee205fd _sigtramp + 29
	3   ???                                 0x0000000000000000 0x0 + 0
	4   UnityPlayer.dylib                   0x000000010f1500a9 _ZdaPvRKSt9nothrow_t + 413625
	5   UnityPlayer.dylib                   0x000000010f14fce3 _ZdaPvRKSt9nothrow_t + 412659
	6   UnityPlayer.dylib                   0x000000010f30833e _ZdaPvRKSt9nothrow_t + 2216526
	7   UnityPlayer.dylib                   0x000000010f308630 _ZdaPvRKSt9nothrow_t + 2217280
	8   UnityPlayer.dylib                   0x000000010f3086ae _ZdaPvRKSt9nothrow_t + 2217406
	9   UnityPlayer.dylib                   0x000000010f3088b8 _ZdaPvRKSt9nothrow_t + 2217928
	10  UnityPlayer.dylib                   0x000000010f307cf6 _ZdaPvRKSt9nothrow_t + 2214918
	11  UnityPlayer.dylib                   0x000000010f404bcc _ZdaPvRKSt9nothrow_t + 3250908
	12  libsystem_pthread.dylib             0x00007fff6ee2c109 _pthread_start + 148
	13  libsystem_pthread.dylib             0x00007fff6ee27b8b thread_start + 15
```

**Versions**
Built-in on master. I was debugging some other issues, and I was on a commit just after the 2019 upgrade and it was there too. (I'll have to look further back to find it)

**To Reproduce**
Use the boat scene. Disable the Sea Floor Depth simulation. Enter play mode and no dynamic waves will be working. Restart Unity and the ocean won't be working. Or do a build and it will crash.

**Platform**
 - Editor
 - Standalone
 - Mac
 - Windows

**Hardware**
MacBook Pro 2014. No dedicated graphics

**Additional context**
Toggling the Sea Floor Depth simulation option in play mode is the most revealing.

I narrowed it down to being in the LodDataMgrDynWaves.SetAdditionalSimParams function. If flow's or depth's data is not bound, then the dynamic waves simulation fails.

I will have to look further into this.

**Comment by huwb** [comment]
Yeah thats super bizarre, its very reproducible and pretty strange, if i knock out the compute shader code that samples depth/flow it still goes nutes.

I do have a theory but have run out of time to test - functions like `WorldToUV()` and `UVToWorld()` depend on `_LD_Params`, which are set when this is called: `OceanRenderer.Instance._lodDataSeaDepths.BindResultData(simMaterial);`

Maybe not calling this bind data for depth and flow means the params dont get set. LodDataMgrPersistent does not set these params, it just calls:

`
                _renderSimProperties.SetTexture(
                    sp_LD_TexArray_Target,
                    DataTexture
                );
`

Maybe it should set the params as well?

**Comment by daleeidd** [comment]
Will close once 4.5 is out

**Comment by daleeidd** [comment]
4.5 is released which solves this issue.
