### ISSUE TITLE
Horizon Line - Occlusion Bug

### ISSUE THREAD

**Issue by Puppetmaster3Dxxx** [crest-ocean/crest#589]
**Describe the bug**
Distance shoreline visible when occlusion is enabled

**Screenshots / video**

![Scene2_Day_Pussy_8612](https://user-images.githubusercontent.com/64129288/87544679-2de45c00-c6a7-11ea-8745-20ebbca99ba0.jpg)

**Versions**
Unity 2019.4, HDRP 7.3.1

**To Reproduce**
Use occlusion

**Platform**
Windows 10

**Hardware**
GTX 2080ti

**Comment by daleeidd** [comment]
Thank you for reporting. Which version of Crest? And is this with the _Horizon Safety Margin Multiplier_ set to zero? And any noteworthy camera settings like different FOV?

**Comment by Puppetmaster3Dxxx** [comment]
I used crest 4.4 and yes, the Safety Margin Multiplier was on 0.

Normal POV and Camera Settings

**Comment by Puppetmaster3Dxxx** [comment]
OK, even when occlusion is disabled I have that issue I just realised...

**Comment by Puppetmaster3Dxxx** [comment]
![Capture](https://user-images.githubusercontent.com/64129288/87630194-ddb3db00-c734-11ea-87eb-eaa14a7f5fce.JPG)

**Comment by Puppetmaster3Dxxx** [comment]
![Capture](https://user-images.githubusercontent.com/64129288/87630506-8bbf8500-c735-11ea-984f-15ae340c3791.JPG)

**Comment by huwb** [comment]
Puppetmaster needs to ship this stuff this week. It's there anything we can do to get him across the line @moosichu @daleeidd?

Assuming this is coming from the underwater effect, could you disable it @Puppetmaster3Dxxx? You should be able to control it from a timeline I think, to disable it in certain shots.

**Comment by daleeidd** [comment]
@huwb Sure. I'll prioritise it.

**Comment by daleeidd** [comment]
@Puppetmaster3Dxxx Does it happen if the _Horizon Safety Margin Multiplier_ is set to the default value (0.01)?

**Comment by Puppetmaster3Dxxx** [comment]
> 
> 
> @Puppetmaster3Dxxx Does it happen if the _Horizon Safety Margin Multiplier_ is set to the default value (0.01)? (I know it was set to zero to solve another issue)

Yes, everything above 0 is causing additional artefacts also at the top of the screen. I mentioned that in another bug and you told me how to fix it with setting the margin to 0. That worked great. But I still have that horizon line. And when you work on it, please use occlusion also. After my video-rendering this week I need to make an executable for my patrons. And without occlusion the performance is going down drastically. Just to keep occlusion enabled in mind. 

And thanks a lot guys!

**Comment by Puppetmaster3Dxxx** [comment]
@huwb I will try disabling the underwater effect. Good thing is, that I don´t go underwater in the video!

**Comment by daleeidd** [comment]
Spoke to @Puppetmaster3Dxxx on discord. This line goes away if the _Horizon Safety Margin Multiplier_ is used. The multiplier was set to zero as a workaround to issue #572. I'll close this one in favour of fixing the other.
