### ISSUE TITLE
[HDRP] Caustics become severe at with realistic sun intensity

### ISSUE THREAD

**Issue by huwb** [crest-ocean/crest#597]
**Describe the bug**
Caustics look very intense with realistic sun light.

**Screenshots / video**
![image](https://user-images.githubusercontent.com/939901/88223856-10436380-cc60-11ea-9af9-e63e850512fa.png)

**Versions**
Tested in win64 editor 2019.4.1

**To Reproduce**
Set the sun light intensity to 100,000 lux which is the intensity used for realistic sun values.

Optionally increase the exposure setting on the postprocessing script to make it less blown out but this is not required to see the issue.

**Comment by daleeidd** [comment]
The fix is pretty simple but it will affect caustics strength for everyone. I am multiplying causes by 0.0001 (ie dividing by 10,000) to give us a 0-1 range. This produced values closest to what we had before. I just need to change it to 100,000.

Are we going to change the sun intensity for the main scene? 100,000 looks crazy bright to me.

**Comment by huwb** [comment]
Thanks dale. I need to look at the code. I feel like it should be possible to have it proportional to the lighting rather than fixed to a range. Will have a look in a bit.

Yeah 100k is a realistic sun and we'll have users using it.

**Comment by daleeidd** [comment]
> proportional to the lighting rather than fixed to a range

Sorry. I miscommunicated. It does go over 1.

**Comment by huwb** [comment]
My understanding was that caustics yield a normalized multiplier for the background colour which is lit. It should be agnostic to the intensity of that lighting.

The issue may be that we're incorporating the light intensity into this calculation, when this intensity is already accounted for in the lit background colour?

Or maybe I'm misunderstanding, could you illustrate the relevant code with the multiplier? I checked public and srp on my phone but didn't see it, but might have missed it

**Comment by daleeidd** [comment]
I see. When I added the light intensity it was to solve the problem of caustics appearing under point lights like the mines in the main scene. I might have to think of a better way to prevent other lights from interfering. Maybe using light layers in HDRP. I don't know about the other pipelines yet.

I sent the line to you for HDRP on discord. Here is the line for built-in:
https://github.com/crest-ocean/crest/blob/master/crest/Assets/Crest/Crest/Shaders/OceanEmission.hlsl#L155

**Comment by daleeidd** [comment]
I have reverted the cause of this issue for all pipelines by removing the caustics strength scaling by sun light and sea depth. Will be out for 4.5

**Comment by daleeidd** [comment]
4.5 is released which solves this issue.
