### ISSUE TITLE
Make the ocean possible to be added to a 'Light Layer' (HDRP)

### ISSUE THREAD

**Issue by script526** [crest-ocean/crest#598]
I would like to make the sun reflections on the ocean more bright ('Sea of Thieves look') by increasing the sun light intensity but keep default lighting on all of the other objects in the scene.

Typically, in order to do so, you have to add the desired object to a separate light layer in the mesh renderer settings so that it receives more or less light but the problem is that the ocean renderer doesn't have this option.

Documentations on the light layers please: https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@7.4/manual/Light-Layers.html

The current workaround would be to increase the light intensity and then to add everything but the ocean to a separate layer but it seems not right - when you have to add every mesh just because you're no able to add the ocean.

**Comment by daleeidd** [comment]
So I had a look at this, and we already allow you to assign a primary light on the ocean renderer. We could just copy over the mask from that light to the mesh renderers.

Add the following to the _OceanBuilder.cs_ file at around line 481:
```csharp
mr.renderingLayerMask = (uint)OceanRenderer.Instance._primaryLight.renderingLayerMask;
```

Then you will need to click on the _Rebuild Ocean_ button on the _Ocean Renderer_ component.

What do you think?

**Comment by script526** [comment]
I'll try that out on Monday and let you know, thank you.

**Comment by daleeidd** [comment]
@script526 Thanks!

@huwb Otherwise, we could simply add a light mask property to the ocean renderer. This would give more control. But there is the possible issue of confusion over what light is lighting the ocean since there could be a mismatch with primary light mask and ocean renderer mask. We mitigate with validation.

**Comment by huwb** [comment]
Thats a good point. I think i'd be inclined to give less control at the beginning and see if more control is requested, if you think this sounds reasonable.

**Comment by script526** [comment]
Hey guys, I don't seem to have to 'rebuild ocean' button. I'm using Crest 4.2. So, adding the line you have provided makes no effect. Also, I don't quite understand what should happen.

Speaking of the primary light. Do you want me to have two different direction lights? One for the ocean and another for everything else? Could you please elaborate.

**Comment by daleeidd** [comment]
> I don't seem to have a 'rebuild ocean' button. I'm using Crest 4.2. So, adding the line you have provided makes no effect.

Oh right. Adding the line will be enough then. In 4.3 the ocean executing in edit mode was introduced which would require this.

> Do you want me to have two different direction lights? One for the ocean and another for everything else?

I must of misunderstood your request. How do you plan on changing the lighting?

**Comment by script526** [comment]
Well, I was told by a colleague that using Light Layers feature you can specify which object receives more or less light from the same directional light. After researching a bit I realized that appeared to be wrong. Sorry, I started using Unity a couple months ago and still don't know much.

So, apparently, you are right, I need to have another directional light for the ocean (the exact copy of the main light with just increased intensity) and to place it to the 'primary slot' of the ocean renderer component. If in this case the main directional light doesn't affect the ocean at all then I assume my problem would be solved. I haven't tried that yet though.

**Comment by daleeidd** [comment]
This will be added with Crest 4.5. Rather than copying the layers over, we added a rendering layer mask property (handles light/shadow layers) to the ocean renderer. To get the most out of the feature, you will need HDRP 8.2 as it introduces light layers to the indirect lighting controller.

**Comment by script526** [comment]
Thank you, I'll keep in mind.

**Comment by daleeidd** [comment]
4.5 is released which adds support for this feature. Please comment if you have anything more to add or open a new issue. Thank you.

**Comment by script526** [comment]
Thank you.
