### ISSUE TITLE
[URP] Query ring buffer exhausted

### ISSUE THREAD

**Issue by kroer** [crest-ocean/crest#605]
Many error messages in a log after play.

E/Unity(20684): Query ring buffer exhausted. Please report this to developers.
E/Unity(20684): Crest.QueryBase:Update()

I don't know what info can help you, so ask any questions.

**Versions**
Unity 2019.4.6f1, URP 7.3.1, OceanCrest 4.3

**Platform**
 - Android 10

**Hardware**
 - Galaxy S10 (Mali-G76 MP12)
 - Galaxy Note 10 Lite (Mali-G72 MP18)

**Comment by daleeidd** [comment]
Thank you for reporting.

Is this a developer or release build?
Does this issue only occur for some devices?
Is this one of our example scenes or one of your own?
We did make some improvements in this area for Crest 4.4. Would you be willing to try upgrading and see if it solves it?

**Comment by kroer** [comment]
- Development build.
 - Now it reproduced only on Galaxy S10.
 - It occurs on our scene.
 - We update to 4.4 an hour ago and will be testing it again today or tomorrow.

If after the testing message will still appear, I will try to make a minimal scene to reproduce it and send it to you.

**Comment by daleeidd** [comment]
Thanks. Look forward to what you find.

**Comment by kroer** [comment]
We receive the error on 4.4 from time to time. Can't build a minimal scene to reproduce it yet. But the error message slightly changed.

08-04 15:13:13.820: E/Unity(9078): (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
08-04 15:13:13.884: E/Unity(9078): Query ring buffer exhausted. Please report this to developers.
08-04 15:13:13.884: E/Unity(9078): Crest.SegmentRegistrarRingBuffer:AcquireNew()
08-04 15:13:13.884: E/Unity(9078): Crest.QueryBase:UpdateQueries()
08-04 15:13:13.884: E/Unity(9078): Crest.OceanRenderer:RunUpdate()

**Comment by huwb** [comment]
It might just be a case of the queries taking longer to do the round trip occasionally on some devices and we may just need to increase the number of buffers. I'll take a look for the param now.

**Comment by huwb** [comment]
Could you please try increasing max requests to 5 or 6:

https://github.com/crest-ocean/crest/blob/master/crest/Assets/Crest/Crest/Scripts/Collision/QueryBase.cs#L28

**Comment by huwb** [comment]
Just bumping this to check for an update

**Comment by daleeidd** [comment]
4.7 is out. I will close this issue as it will likely also be solved by #696. But if it isn't, please reopen.
