### ISSUE TITLE
Freaking out dynamic waves from out of nothing

### ISSUE THREAD

**Issue by klauskobald** [crest-ocean/crest#606]
**Describe the bug**
In proximity of the camera (a square) the ocean begins to jitter and build up to monster spikes.
It is happening in the UpdateDynWaves.compute. For some reason the particles begin to get in resonance somehow.
I described this issue some months ago and I am still trying to get rid of it with all kind of tricks, like raising the damping factor to 1, when boat is not moving. This works kind of but not really in all circumstances.

**To Reproduce**
These are the SimSettingsWave:
damping: 0.3
courant: 1.49
simsteps: 2
horiz displ: 20
clamp: 0.3
Gravity multi: 20

I have registered dynamic waves input with 
factorParallel: 6.3, ortho: 3.1
strength: 330
But these only control who strong the waves will be created. So, even when the boat is not moving or very slowly it creates some input I asume.

**Platform**
It´s rarely happening in my editor
On iOS it´s happening after like 3-5 minutes

**Hardware**
iPad Pro

**What I found out**
I changed the render texture in LodDataMgrDynWaves.cs to RGFloat (instead of Half), because I thought it´s maybe to less precission. But in contrary it is even worst (see image).
There is no "cheaper" float then half. But maybe it would help to "round" some values to 0 if they become very tiny? I tried that but failed because I do not really understand the math there.

**Comment by klauskobald** [comment]
Upload failed - hier is the image:
[Freak Out Spikes](http://clients.kobald.com/dyb/show/freakout.jpg)

**Comment by klauskobald** [comment]
It´s also happening in Editor with the same parameters after a while, however I had to permanently excite it with "engine" which creates small dynamic waves inputs.
[Freak Out Spikes - Editor](http://clients.kobald.com/dyb/show/freakout2.jpg)

By the way - I brought up this issue I think over 1 year ago, cause it alos happens in the 3boat demo, as far as I remember.

**Comment by klauskobald** [comment]
I had a closer look to updateDynamicWaves.
in there is a line
	weightEdge = lerp(0.95, 1, weightEdge);
which later is used for damping. It seems that 1 as no damping is not a good idea.
I changed to 
	weightEdge = lerp(0.95, 0.991, weightEdge);
Which calm down the spikes even if they show up. A higher value did not work.
However this also dampens the wanted waves which can be compensated by increasing some other values.
So this is not an elegant solution but at least it works for now.

As an input:
I think what should be done is a lowpass filter or even better a bandpass filter that dampens the frequency of the jittering. I've implemented filters 20 years ago for an audio plugin. There is plenty of code snippets how to do that and they are not very expensiv to calculate.

**Comment by huwb** [comment]
Hello, there is documentation that converts sim settings and stability: https://github.com/crest-ocean/crest/blob/master/USERGUIDE.md#simulation-setup

I think you need to reduce the courant number.

**Comment by klauskobald** [comment]
I have read this.
But the courant number sets the iteration step size, if I understand this correctly:
            var maxDt = 0.5f * Cmax * ocean.CalcGridSize(lodIdx) / waveSpeed;
so, reducing it will simply slow down simulation, which means the jitter will happen later. I tried this out.

**Comment by huwb** [comment]
Yeah reducing the step size should indeed reduce the timestep which should make the sim more stable.

Does it still blow up for you with reduced courant number? I think a value of 1 is at the limit of stability, 1.49 should be inherently unstable. I think 0.75 is maybe a good target.

**Comment by klauskobald** [comment]
I know what you mean. I will give it a try another time. Anyhow, I think the multiplicator for vtp and ftp should never get the chance to be 1. As I told, it reacts different on GPUs. There might be floating-point precision issues, which could lead to over 1 a tiny bit.

**Comment by huwb** [comment]
It has a specific damping term that is not close to 1 elsewhere in that shader.

**Comment by huwb** [comment]
I'll assume that resolved it, let us know if not

**Comment by klauskobald** [comment]
not really. I get only rid of it when I patch it with
weightEdge = lerp(0.95, 0.991, weightEdge);
but maybe that´s a precision problem as well. I will check this maybe sometime. I am currently in public beta and will not change anything now.
