### ISSUE TITLE
How do I find the Emit Particles When Submerged script?

### ISSUE THREAD

**Issue by Shizzane** [crest-ocean/crest#607]
I downloaded the zip file which looks like a complete unity project. Just wondering where the script is? Or did I download it wrong? I'm new to Github. 

Cheers.

**Comment by moosichu** [comment]
Did you download the correct branch?

https://github.com/crest-ocean/crest/archive/feature/emit-particles-when-submerged.zip

This feature has not been merged into the main branch yet - so won't be there if that is what you downloaded. 

Let me know if this helps.

**Comment by Shizzane** [comment]
Ok thanks..I think this is the one I downloaded....just cant find the
script. What is it called?

Thanks!

**Comment by Shizzane** [comment]
NM found it lol..didnt look in "FX"! 😥

**Comment by huwb** [comment]
I think its demonstrated in the main.unity example scene, worth checking
there as a starting point.

**Comment by moosichu** [comment]
Closing this issue for now - if you have any more issues we will see updates here. Seems like you found it though.
