### ISSUE TITLE
how do I add a floating fix / origin to the crest?

### ISSUE THREAD

**Issue by ardiansareza3** [crest-ocean/crest#609]
I tried adding a floating fix to a crest I don't know where to start with crest, a lot of assets like Enviro & Vegetation Studio they add features to this so they provide a place to put the transform world anchor

**Comment by daleeidd** [comment]
There is a section on floating origin in the user guide. Have you read and tried the following yet?

https://github.com/crest-ocean/crest/blob/master/USERGUIDE.md#floating-origin

**Comment by daleeidd** [comment]
I'll close this for now. If you still have troubles, I will see your response.
