### ISSUE TITLE
Flickering shadow

### ISSUE THREAD

**Issue by klauskobald** [crest-ocean/crest#616]
This can be observed on low framerates. It seems as the shadows are created every other frame.
(any platform and editor Mac)

Set shadowSettings to frameweights = 1.
Reduce the framerate with Application.targetFrameRate = 1;
Interesting: I could not observe this issue by stepping frame by frame!

example video:
http://clients.kobald.com/dyb/show/shadowmaps/crest-shadow-flicker-1fps.mov

The issue is not a show stopper. Effect can be reduced by lowering frameweights to about 0.5.

**Comment by daleeidd** [comment]
I can get flickering if I reduce the shadow map resolution. If I increase the shadow normal bias, I can get the "striping" of shadows. What are you shadow settings for that video?

**Comment by klauskobald** [comment]
depth bias=1
normal bias=0 -> yes, that moves the shadow outward, when greater 0
shadowmap 1024, but it happens with all resolutions
I played with these values a lot, but it does not change the every other frame flickering.
watch this:
http://clients.kobald.com/dyb/show/shadowmaps/crest-shadow-flicker-normal-bias.mov
Moving the bias and resolution at 3 fps. 
frameweights=0.2 > which has not much impact at lower frame rates. I assume this is because urp maybe runs faster in the background?

**Comment by daleeidd** [comment]
Thanks. Hmm. Do you have multiple cameras enabled in the scene (just being enabled is enough even if not used)? I know there was a bug in URP where the shadow data pass was being called for all cameras.

**Comment by huwb** [comment]
+1 - i think i had scene view and game view open at the same time and got flickering - i think

**Comment by klauskobald** [comment]
I have several cameras but only one that renders ocean. Sometimes a second ocean enabled one get´s activated for close up. I don´t think, that´s the reason, but I will check!

**Comment by huwb** [comment]
I think we fixed this one together? It was precision of the shadow calculation which we set to float? Or is this different?

**Comment by klauskobald** [comment]
I think that is fixed. It was also an "half"-issue.
