### ISSUE TITLE
Water at horizon edge is black

### ISSUE THREAD

**Issue by andrew-sidereal** [crest-ocean/crest#617]
**Describe the bug**
It's the right & left edges which show this. If I rotate camera, it rotates the black bands with it.

**Screenshots / video**
1. https://i.imgur.com/QlMkZfV.jpg
2. https://i.imgur.com/dCLTKHG.png

**Log**
https://i.imgur.com/Zua3Wan.png

**Versions**
built-in rendering pipeline, v2019.4.4

**To Reproduce**
Basic ocean setup with some waves.

**Platform**
 - in editor

**Comment by huwb** [comment]
That's pretty weird. Could you experiment with the far clip plane setting on the camera?

Could you posted screenshots showing the ocean renderer component settings and the camera settings?

**Comment by andrew-sidereal** [comment]
Thanks for taking the time to look into this. I took bunch o screenshots of the camera settings with different far plane values, as well as the ocean game object settings. You can see them all here: https://imgur.com/a/5DPo9sd

Please let me know if there's anything else I can do to help solve this. Thank you!

**Comment by daleeidd** [comment]
Do you know how old your version of Crest is? Are you grabbing it from the master branch?

Does it occur in the main example scene? Have you tried to narrow it down by disabling Enviro and Map Magic or anything else in the scene?

**Comment by andrew-sidereal** [comment]
I got Crest from the master branch either Aug 12th or Aug 14th.

Thank you for helping me think through this. The Crest demo scene works wonderfully.

I've narrowed down my issue to the Enviro Sky Manager. Here are a couple before/after shots: https://imgur.com/a/sBR2WAQ

Are there steps required to properly integrate this with Enviro? I'd appreciate any help you can offer.

Thank you,
Andrew

**Comment by daleeidd** [comment]
Did you follow the integration guide provided by Enviro?

We have a copy on our wiki. I am pretty sure it is still up-to-date:
https://github.com/crest-ocean/crest/wiki/How-to-use-Crest-with-Enviro

**Comment by andrew-sidereal** [comment]
I've completed that guide and it enables Enviro fog. It was clear and easy
to follow -- thank you. However, the same issue still exists. I see this
error in the console: "There is no skybox set in the lighting settings
window. Ocean color will be incorrect." Any guidance on how to fix this
when using Enviro?

Here are a number of shots from night-time, when it's most dramatic. It's
like the square around the player/main-cam is properly shaded, but beyond
that it's not.
https://imgur.com/a/x0bJu9I

Thank both for all of your help!

**Comment by andrew-sidereal** [comment]
I also did some more experimentation with the far clipping plane of the main camera. You can see in these four photos that it does have an effect on the issue. Increases the far clipping plane increases the square of "correct" rendering around the player/main-cam. However, the issue still persists an is observable in game-mode. Hopefully these pictures illustrate it well:  https://imgur.com/a/YkF4i93

**Comment by daleeidd** [comment]
> "There is no skybox set in the lighting settings
window. Ocean color will be incorrect." Any guidance on how to fix this
when using Enviro?

Not sure how to fix this with Enviro. If you look at the light settings, you will see a setting called _Skybox Material_ which will be not assigned based on that validation message. There might be something in the Enviro documentation about what needs to go there.

> I also did some more experimentation with the far clipping plane of the main camera

It looks like an issue with the reflection probe Enviro provides. I am guessing that Enviro changes its size based on the far clipping plane values, but it is not enough to cover the ocean. If you disable the reflection probe you should see the ocean have constant lighting.

**Comment by andrew-sidereal** [comment]
I was able to fix the Skybox Material being recognized by moving Enviro to be earlier in the Script Execution Order. It resolved the remaining warnings, which is great, but unfortunately it didn't resolve the bug in question. 

You are right about the reflection probe. I tested it with and without and here are the results: https://imgur.com/a/aQzsAlG

With the reflection probe enabled, the ocean is properly colored in a square around the player, but then incorrectly colored beyond that. 

With the reflection probe disabled, the ocean is consistent everywhere, but incorrectly colored.

Now, the question is how to have it correctly colored everywhere, not just in the square around the player.

**Comment by daleeidd** [comment]
Good to hear. You'll just need to expand the size of the reflection probe to cover the ocean. You might need to refer the documentation for Enviro or asking Enviro developer on the best approach if it isn't as simple as expanding the bounds in the inspector.

Since it isn't an issue with Crest, I will close this. But I will see any replies :)
