### ISSUE TITLE
Check if the created texture in LodDataMgr is actually working on the GPU

### ISSUE THREAD

**Issue by klauskobald** [crest-ocean/crest#621]
As we know, there is issues on Android which can be maybe solved easily by testing, if a texture is throwing errors. I think these errors could occur on all platforms as well depending on the GPU. 

SystemInfo.SupportsRenderTextureFormat is not enough to check!
So,
I am currently trying to implement a texture-format probe system that iterates thru a replacement list for a given format.

I create a texture like so:
var desc = new RenderTextureDescriptor(64, 64, rtf, 0);
[…]
result.enableRandomWrite = true;
result.Create();

BUT….

it seems that result.create() does not fail, even when readwrite is not supported.
Maybe a call has to be made to the GPU? How would I do that? My suspicion is to actually have commands sent to the GPU and wait for the result? The LodDataMgr would have then to wait before going into operation.

A second approach I could try is this: 
All LodDataMgr register with a textureProvider. If an error is happening later, then analyse the exception in the callback Application.logMessageReceived and change to the next replacement texture format and replace texture in LodDataMgr.

**Comment by daleeidd** [comment]
https://docs.unity3d.com/ScriptReference/Experimental.Rendering.FormatUsage.LoadStore.html

Huw mentioned this on the other issue. It's experimental. Do you think it is worth trying?

**Comment by klauskobald** [comment]
I found this:
SystemInfo.GetCompatibleFormat(gf, FormatUsage.LoadStore)
where gf is a GraphicsFormat. And return value is again a GraphicsFormat.
But how would I convert a RenderTexture into a graphicformat?

**Comment by daleeidd** [comment]
The following utility should help:
GraphicsFormatUtility.GetGraphicsFormat()
GraphicsFormatUtility.GetRenderTextureFormat()

**Comment by klauskobald** [comment]
I think we are getting somewhere!
I added this function to LodDataMgr and used it everywhere instead of TextureFormat.
<pre>
protected RenderTextureFormat GetValidatedTextureFormat()
{
    var gf = GraphicsFormatUtility.GetGraphicsFormat(TextureFormat, true);
    var cgf = NeedToReadWriteTextureData ? SystemInfo.GetCompatibleFormat(gf, FormatUsage.LoadStore) : gf;

    if (cgf == GraphicsFormat.None)
        throw new System.Exception("RenderTextureProbe: cannot find a replacement for " + TextureFormat);

    var r = GraphicsFormatUtility.GetRenderTextureFormat(cgf);
    if (cgf != gf)
        Debug.Log($"RenderTextureProbe: will use {r} instead of {TextureFormat}");

    return r;
}

</pre>

This eliminates all "unsuported renderformat" errors - heureka!
Anyway, some things seem not to work correctly. I have to investigate further. It seems the foam gets rendered as little white squares only.
The problem might be, that on Oculus Quest all replacements are ARGB32 and ARGBHalf also for formats like R8, R16, RG16. 
<pre>
RenderTextureProbe: will use ARGB32 instead of R8
RenderTextureProbe: will use ARGBHalf instead of RGHalf
RenderTextureProbe: will use ARGBHalf instead of RHalf
RenderTextureProbe: will use ARGB32 instead of RG16

</pre>

So this might break things.
I will push the app to google and will watch the prelaunch test movies.

**Comment by klauskobald** [comment]
I got pretty good results. no more unsupported texture errors. There is only one device showing the same foam problem as the oculus quest does:
http://clients.kobald.com/dyb/show/crest-foam-on-SonyXZ1.mp4

no big show stopper - people can select a version without foam but maybe we find the problem.

**Comment by klauskobald** [comment]
not working
Quest and XZ1 use Adreno 540

working
Pixel 4 uses Adreno 640
Galaxy S9 Mali-G72

**Comment by daleeidd** [comment]
That's good to hear. I think this looks very promising. We could even go all in on the GraphicsFormat since it has pretty good support. But what you have done would be a nice small change to solving this issue.

It is possible that the foam issue is unrelated to these additions. I am not sure what it is at this stage. So "not working" is in regards to the foam issue? And you haven't seen any other problems with these changes?

What are your thoughts @huwb?

**Comment by klauskobald** [comment]
yes, sorry. it‘s only the foam. I did not check flow, since I am not using it currently. So all other features including dynamic waves work.

**Comment by huwb** [comment]
Thanks for this @klauskobald . 

Yeah I think we should aim to incorporate this if it behaves well for us

The foam issue is very strange. It might be what you mentioned about expanding the format. It could be useful to see the foam data on the debug overlay to get a sense of what it's doing (and it will show off there is craziness in some of the channels).

The only thing that occurs to me is that bad things can happen if your texture has eg 4 channels but you only write 1 out from a shader. A test would be to always write 4 channels from all foam related shaders. Not sure that helps though.

**Comment by huwb** [comment]
As an aside, the quest formats are pretty mental

RGHalf goes to argbhalf, but rg16 goes to argb32? In my head RGHalf and rg16 should be the same.

Also R8 going to argb32 is insanity, and might be something we want to catch

**Comment by huwb** [comment]
Oh re going all in on graphicsformat, sounds good if we can? What does support currently look like?

**Comment by daleeidd** [comment]
> Oh re going all in on graphicsformat, sounds good if we can? What does support currently look like?

https://docs.unity3d.com/ScriptReference/Experimental.Rendering.GraphicsFormat.html

It's defined under the experimental namespace, but there is no "experimental" warning banner. We are already using it in HDRP since RTHandles takes GraphicsFormat only.

It was introduced 2018.2 beta according to this thread it looks like:
https://forum.unity.com/threads/feedback-or-comments-needed-for-texture-formats.503765/

The only thing is we lose stuff like Default and DefaultHDR formats.

**Comment by daleeidd** [comment]
Will be out for Crest 4.7. Thank you for your help.

**Comment by daleeidd** [comment]
4.7 is out so this one can be closed. Thanks again!

**Comment by daleeidd** [comment]
Just linking what I believe is a related closed issue #493
