### ISSUE TITLE
Jittering in ocean waves in the farout (Déjà-vu)

### ISSUE THREAD

**Issue by klauskobald** [crest-ocean/crest#622]
Smaller waves are not rolling smoothly. One can see them in little steps going up and down. This happens not at the center of the world but further away.

It is a similar thing like we had with the shadows 
https://github.com/crest-ocean/crest/issues/612

**Platform**
iOS - again

**Hardware**
iPad

**Solution**
I fired a replace "bazooka" at the shaders.
All reals against floats but that did not help. 
All halfs against floats -> Bingo! No jittering anymore.

So, please help me to narrow that down:
I assume it must be somewhere in the gerstner calculations.

Any ideas?

**Comment by klauskobald** [comment]
I narrowed it down to GerstnerShared.hlsl!
Replacing all halfs with floats does it. Maybe not all of the halfs have to be replaced? But maybe it does not matter. For me it seems, that most GPUs do not use halfs at all.

**Comment by daleeidd** [comment]
Thank you for doing this. It has been really helpful.

@huwb might have a better idea than me, but I am hoping that only the following needs to be changed to floats since it is dealing with the world position:
```
// spatial location
half4 x = Dx * worldPosXZ.x + Dz * worldPosXZ.y;
```

**Comment by klauskobald** [comment]
yes. changing this line to float4 is sufficient!

**Comment by daleeidd** [comment]
Thanks @klauskobald. Will be out with 4.6 but I don't think many will come across this issue so I will close it. If you have any more to add just reply and I will see it.

**Comment by huwb** [comment]
Thanks both!
