### ISSUE TITLE
Reflection objects are not created, when instance of crest is changed

### ISSUE THREAD

**Issue by klauskobald** [crest-ocean/crest#623]
**Solution**
Move code from OceanPlanarReflection.Start to OceanPlanarReflection.OnEnable.

Reason: I have a setting to turn reflection on/off. So, reflection script is disabled if that switch is off.

**Comment by daleeidd** [comment]
Is this the same issue as #576?

**Comment by klauskobald** [comment]
ah, yes sorry!

**Comment by daleeidd** [comment]
No worries. Closing as is duplicate of #576
