### ISSUE TITLE
[HDRP] Weird caustics in latest crest

### ISSUE THREAD

**Issue by cloakedch** [crest-ocean/crest#625]
After upgrading to the latest august update I noticed that the caustics covers much more area when submerged.

Caustics above sea level:
[![surfaced](https://user-images.githubusercontent.com/32439069/90956147-faee6e80-e483-11ea-9819-67d17f2eb3c7.png)
](url)

Caustics below sea level:
![submerged](https://user-images.githubusercontent.com/32439069/90956148-fe81f580-e483-11ea-8d3e-8e4e1c1bf0e2.png)

I remember that the caustics looked the same before the upgrade (above and below sea level were identical).
Does this look like intended or is this a bug?

**Comment by huwb** [comment]
I have not understood. What do you mean by covers much more area?

We did some tweaks to the caustics to make them work over a wider range of lighting conditions, so they might look a bit different. The above does not look wrong to me, i dont think.

**Comment by cloakedch** [comment]
If we look at the caustics below sea level, we see that the blue and red refractions occupy more area (are larger) than when we see the same above the surface.

This was not the case before the update and I was wondering why the caustics are different when seen below the surface.

![Unbenannt](https://user-images.githubusercontent.com/32439069/91040463-9875a980-e60e-11ea-8c3c-0c64a397ab87.png)

**Comment by daleeidd** [comment]
What version of Crest did you upgrade from?

Caustics for HDRP has always looked different between above and below water (unless you are upgrading from a very early Crest HDRP version where distortion underwater was broken). From above water we use refraction from the surface normals to distort the caustics. But from below we use a distortion texture.

**Comment by cloakedch** [comment]
I think I have upgraded from the version that was current at the beginning of August. I did not notice the effect with that version.

This is fine with me. I just wanted to know if it isreally normal or if it is a bug. Thanks for the support.
