### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by daleeidd** [crest-ocean/crest#630]
**Describe the bug**
Reported on Discord. Occasionally, memory usage will grow until it crashes Unity when the editor is left with an active ocean in scene.

**Screenshots / video**
![iu67iu6i](https://user-images.githubusercontent.com/5249806/91191315-7b41e900-e6a9-11ea-92c4-f0dd01baf1df.jpg)

**Versions**
Crest 4.5, HDRP 7.3.1 and Unity 2019.4.8.f1

**Platform**
 - Editor
 - Windows

**Additional context**
We fixed a few memory issues a little while ago which were easier to pinpoint. This one is "occasionally" so it will be more difficult.

**Comment by daleeidd** [comment]
From Discord:
> so there is still a memory leak in editor mode in the latest hdrp version on 2020.1.  The scene with crest I left open overnight went from 4gb ram usage to 25gb.  This looks like maybe a different issue then one I hit previously that seemed linked to entering/exiting play mode.   Refocusing Unity took a while and that brought the memory down quite a bit.

**Comment by huwb** [comment]
Interesting. Any suspicions as to the culprit? Any potential repro steps, or seemingly random so far?

I feel like its CPU memory, but i'm not 100% sure. If you can trap it happen it would be interesting to see the profiler memory pane while connected to the editor.

**Comment by daleeidd** [comment]
I forgot to add this was reported on Discord by two users (updated post). I haven't experienced this myself. It's hard to know since the timeframe is so long.

**Comment by huwb** [comment]
One issue is that I think the ocean may be updating every editor frame even if the viewport is rendering infrequently. I think this is a regression, or maybe it was always broken. This may exacerbate any memory leak (but doesn't explain it).

I'm still yet to see this happen across multiple editor versions and multiple PCs. Maybe it's an editor setting, or window layout/settings or something..

**Comment by huwb** [comment]
On I've seen it now and holy moly it's bad. It comes from creating async GPU readback requests while in edit mode (not play mode). It seems to be an engine bug.

I think a short term fix could just not do them in edit mode. I don't think we rely on them.

**Comment by daleeidd** [comment]
Perfect. Did you use the Unity memory profile to find it?

**Comment by huwb** [comment]
Sort of - the profiler showed unity memory increasing, but it was not attributed to any of the stats, or call stacks, so I binary searched to find the culprit.

**Comment by huwb** [comment]
Fixed in 2019.4.8, and 2020.1.?

https://issuetracker.unity3d.com/issues/asyncgpureadback-can-leak-memory-under-certain-circumstances

**Comment by daleeidd** [comment]
Apparently 2020.1.2f1 specifically. And 2020.2.0a20 too
