### ISSUE TITLE
Shore foam is clipping when cam near.

### ISSUE THREAD

**Issue by andrew-sidereal** [crest-ocean/crest#645]
**Describe the bug**
The foam disappears as the camera approaches.

**Screenshots / video**
Far away: https://i.imgur.com/6Vh8aGr.png
Nearer: https://i.imgur.com/PQN8Lwl.png

**Versions**
Built-in pipeline
2019.4.4

**Comment by daleeidd** [comment]
It's hard to tell as the water level is different in these two images. Are you able to reproduce without changing the water level? It is very likely that the ocean depth cache hasn't been updated causing more foam to appear than it should.

**Comment by andrew-sidereal** [comment]
This is no longer occurring, so let's consider it "unreproducible" for now.
I'm not sure what changed, but sometimes just restarting Unity clears
things like this up. That may have been all which was needed.

**Comment by daleeidd** [comment]
No worries. I'll close this for now. If it continues to be an issue then comment here and I will re-open.
