### ISSUE TITLE
[SRP] Underwater is not rendered in Unity 2020.1.0f1 (Crest version 2020.09.02)

### ISSUE THREAD

**Issue by Karu1977** [crest-ocean/crest#646]
For some reason newest Github Crest vesion (2020.09.02) for Standard Unity Rendering Pipeline don't show underwater. I compared with old version (downloaded at 2020.04.09), the old version renders underwater normally, the new one - no. Unity version is 2020.1.0f1, GPU is Nvidia RTX 2060.

**Comment by huwb** [comment]
Sometimes the underwater material breaks. Could you try toggling one of the material options on the underwater material? This should be enough to wake it up.

**Comment by daleeidd** [comment]
I've had a look and underwater works in 2020 for me. I tested on 2020.1.2f1. This is very likely the issue Huw mentioned. I'll close this issue, but please comment here if re-importing the underwater curtain material doesn't solve the issue and I will re-open.

**Comment by Karu1977** [comment]
Sorry, was busy with other work. Just tryed the new version, uploaded 2 days ado. From the start the same behaviour (no underwater rendering). Found the Ocean_UnderwaterCurtain material initially it displayed as magenta (like invalid material). Toggled first parameter (Shadowing) and it started to work, in new and old project too.
