### ISSUE TITLE
Shadows suddenly disappeared

### ISSUE THREAD

**Issue by Kandob** [crest-ocean/crest#651]
**Describe the bug**
Shadows used to work fine but they've suddenly disappeared, even when using the material that comes with crest. I'm using a camera with forward rendering, shadows are enabled in the material and the sim settings are linked. I've tried it in another scene where it used to worked too.

**Screenshots / video**
![Screenshot 2020-09-14 033228](https://user-images.githubusercontent.com/14958256/93034635-0542f900-f63b-11ea-8066-e604ed2045ba.jpg)

**Log**
No errors/warnings.

**Versions**
2019.3.0f3 Built in RP

**Platform**
 - Editor and standalone
 - Windows

**Hardware**
GTX 1070

**Comment by daleeidd** [comment]
Thanks for reporting. What has changed? Upgrading Unity or Crest?

**Comment by Kandob** [comment]
I haven't upgraded anything, the shadows just suddenly disappeared from one day to the next. Is there anything else that could affect the shadows like quality settings or plugins?

**Comment by daleeidd** [comment]
Have you tried viewing the shadow data in the ocean debug GUI? Or have you checked the frame debugger?

> Is there anything else that could affect the shadows like quality settings or plugins?

Not that I can think of other than shadows being enabled.

> the shadows just suddenly disappeared from one day to the next

Have you tried clearing the Library folder or anything like that?

**Comment by huwb** [comment]
Just to add, you might compare shadow settings in your project with those in the example project

**Comment by Kandob** [comment]
> Have you tried viewing the shadow data in the ocean debug GUI? Or have you checked the frame debugger?

I don't see an option to view the shadow data, there's just "Process Shadows" in the menu on the left.
![Screenshot 2020-09-15 101236](https://user-images.githubusercontent.com/14958256/93184067-16bffa00-f73c-11ea-8a6f-b840d8771ab7.jpg)

> Have you tried clearing the Library folder or anything like that?

I'd prefer not removing the whole folder since the project I'm working on is huge, it would take ages to rebuild. Is there anything specific I can try removing?

> Just to add, you might compare shadow settings in your project with those in the example project

I've compared them and they're exactly the same. I did notice the shadow debug toggle missing in the GUI even though "Create shadow data" is ticked.

**Comment by huwb** [comment]
You need to click the create shadow option on the ocean renderer component

**Comment by Kandob** [comment]
It's ticked, here are my settings:
![image](https://user-images.githubusercontent.com/14958256/93187533-2fcaaa00-f740-11ea-876c-22fcdce6c259.png)

**Comment by daleeidd** [comment]
> I'd prefer not removing the whole folder since the project I'm working on is huge, it would take ages to rebuild. Is there anything specific I can try removing?

We'll leave it for now.

How old is your version of Crest?

It looks like the shadow sim is being disabled at runtime. Is _Create Shadow Data_ checked when entering play mode? If your version of Crest is before when the ocean is running in edit mode (pretty certain it is), then you should see components for each simulation attached to the ocean renderer game object; can you see one for shadows in play mode? Also, if you look at the following file, there should be a _Start_ method. There might be some places where it exits early without logging:

_/Assets/Crest/Crest/Scripts/LodData/Shadows/LodDataMgrShadow.cs_

**Comment by Kandob** [comment]
>  Is Create Shadow Data checked when entering play mode?

Yes it's still checked.

> If your version of Crest is before when the ocean is running in edit mode (pretty certain it is)

Yeah I think it is, I didn't even know that was added. I only keep an eye on the releases so that's the version I'm using (Feb 2020 Update)

> can you see one for shadows in play mode?

No I don't see one.

> Also, if you look at the following file, there should be a Start method. There might be some places where it exits early without logging:

All exceptions seem to be caught as far as I'm seeing, but maybe i'm not seeing any errors because it's not being added to the ocean gameobject.

![image](https://user-images.githubusercontent.com/14958256/93231777-67a21380-f779-11ea-893d-e4e63c4c5c92.png)

**Comment by daleeidd** [comment]
> I only keep an eye on the releases so that's the version I'm using (Feb 2020 Update)

We have stopped producing releases. Updates will need to be downloaded from the master branch. It will be a big upgrade since 2019.4 is now a requirement.

> No I don't see one.

Not sure what could be causing it. The create function is pretty simple and you would see an error. Line 185 with the following line in OceanBuilder is where that component gets created:
```csharp
ocean._lodDataShadow = LodDataMgr.Create<LodDataMgrShadow, SimSettingsShadow>(ocean.gameObject, ref ocean._simSettingsShadow);
```

**Comment by Kandob** [comment]
I have no idea what could be causing this. But I've upgraded my project to 2019.4 and imported the latest version of Crest, shadows seem to be working fine now. If it happens again I'll reopen this issue. Thanks a lot for the support!

**Comment by huwb** [comment]
That's really odd.. thanks for getting back to us
