### ISSUE TITLE
How do I increase the center lod?

### ISSUE THREAD

**Issue by klauskobald** [crest-ocean/crest#659]
This is not a bug, more a question:

I am optimizing for lo-end devices with these settings:
Ocean Detail Params:
min - max scale: 32 - 128
lod data res: 64
down sample factor: 1 
lod count: 2

which brings only a small square of details, where foam is created. But borders are clearly visible and it´s not where the camera is pointing sometimes. Is there a way to increase that center square?

![crest-foam-center](https://user-images.githubusercontent.com/278428/94084909-b2083d80-fdd4-11ea-9f5f-8c6c240dc09e.jpg)

**Comment by klauskobald** [comment]
I found increasing the lod count seems to solve it. have to check how the cpu impact is. is this the way to go?

**Comment by huwb** [comment]
The general issue is that there are a lot of waves that are rendering into lod 0 with your settings. You could increase amplitude of bigger wavelengths, or reduce smaller wavelengths to balance it out.

Increasing lod data resolution would expand the range of those waves so it isn't such a small square, but you are looking at low end perf so may not be an option.

**Comment by klauskobald** [comment]
great - will look into that. anyhow I found out, that a higher LOD is not so much a performance killer. it´s more the size of the textures. I also found out, that dynamic waves depend somehow on the resolution of the LODs - half resolution would mean I have to multiply the size of waterinteraction objects by 2.
