### ISSUE TITLE
Height Queries not working on Linux Standalone build (Query ring buffer exhausted.)

### ISSUE THREAD

**Issue by skaughtx0r** [crest-ocean/crest#662]
**Describe the bug**
When running a standalone build of Crest on Linux the height queries are not working. The log is filled with `Query ring buffer exhausted. Please report this to developers.` messages.

**Screenshots / video**
Everything renders normally.

**Log**
```
Underwater must be enabled on the ocean material for UnderwaterPostProcess to work
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogError(Object, Object)
Crest.UnderwaterPostProcess:InitialisedCorrectly() (at /home/chops/repos/crest-oceanrender/crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterPostProcess.cs:85)
Crest.UnderwaterPostProcess:Start() (at /home/chops/repos/crest-oceanrender/crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterPostProcess.cs:114)

(Filename: /home/chops/repos/crest-oceanrender/crest/Assets/Crest/Crest/Scripts/Underwater/UnderwaterPostProcess.cs Line: 85)

Query ring buffer exhausted. Please report this to developers.
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Crest.SegmentRegistrarRingBuffer:AcquireNew() (at /home/chops/repos/crest-oceanrender/crest/Assets/Crest/Crest/Scripts/Collision/QueryBase.cs:100)
Crest.QueryBase:UpdateQueries() (at /home/chops/repos/crest-oceanrender/crest/Assets/Crest/Crest/Scripts/Collision/QueryBase.cs:486)
Crest.OceanRenderer:RunUpdate() (at /home/chops/repos/crest-oceanrender/crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs:701)
Crest.OceanRenderer:LateUpdate() (at /home/chops/repos/crest-oceanrender/crest/Assets/Crest/Crest/Scripts/OceanRenderer.cs:689)

(Filename: /home/chops/repos/crest-oceanrender/crest/Assets/Crest/Crest/Scripts/Collision/QueryBase.cs Line: 100)
```

**Versions**
Pipeline: built-in
Unity 2019.4.11f1

**To Reproduce**
1. Create a standalone build with the `BoatScene` in the repo.
2. Run the standalone build.

**Platform**
 - Standalone
 - Linux: Ubuntu 18.04

**Hardware**
GPU: NVIDIA Quadro M3000M (Vulkan)

**Additional context**
Full log is attached: 
[BoatScene_log.txt](https://github.com/crest-ocean/crest/files/5319432/BoatScene_log.txt)

**Comment by huwb** [comment]
Sorry I never got back to you, had been a mental month.

It's this still an issue?

Maybe the round trip time for GPU readbacks is legit longer for this setup, could you try simply increasing the buffet size

https://github.com/crest-ocean/crest/blob/83e2e6b133a18a8d8de6eedec69230610b4975d7/crest/Assets/Crest/Crest/Scripts/Collision/QueryBase.cs#L70

**Comment by skaughtx0r** [comment]
@huwb Doubling s_maxRequests seemed to work. I set it to 8 instead of 4. That works with the example boat scene anyway. Seems like kind of a sketchy solution as it might be hardware dependent. Maybe if it fails it should increase the buffer until it works, instead of just spewing errors?

**Comment by huwb** [comment]
It's more concerning to me that's there's such a high latency on getting the query results back, this is likely to cause it's own set of problems and I wouldn't want to simply let this grow.

Also I've seen situations in the past where in some error cases queries are queued up but not processed which also exhausts the buffer, and I wouldn't want to grow the buffer size on that case.

Understood about other hardware setups but the current size has been ok until now and it really shouldn't take longer than this for results to come back.

I'd rather keep it simple and increase the current size by a fixed amount, but perhaps extend the error message to hint at this problem in the future. 

Can increase the size by 2, that would allow prob 4 or 5 frames of latency for quotes to come back from the GPU which is fairly extreme.

**Comment by skaughtx0r** [comment]
Are you saying that increasing the size of the queue will add latency to the queries? If that's the case I'm not sure we should be messing with the current size for this edge case. I will test this stuff out on a different Linux computer with a better GPU to see if I have the same problem.

**Comment by huwb** [comment]
The latency depends only on the os/hardware. The queue size is the max latency the system will support. Adding 2 will allow latencies up to 5/5 frames without complaining which is the max id be ok with.
.

**Comment by skaughtx0r** [comment]
@huwb I just re-tested adding `2` to the `s_maxRequests` and it doesn't work. It seems to start working when I bump it plus `3`.

```C#
const int s_maxRequests = 7;
```

**Comment by daleeidd** [comment]
4.7 is out so I will close this issue. If the issue still persists, then please comment. Thank you for your help.
