### ISSUE TITLE
Ocean shader breaks when placing Crest under sub folder

### ISSUE THREAD

**Issue by daleeidd** [crest-ocean/crest#664]
**Describe the bug**
Reported on discord. Ocean shader breaks when placing Crest under sub folder. This is due to use of hard-coded paths.

**Versions**
Crest 4.5

**To Reproduce**
Move Crest folder into a sub folder.

**Additional context**
Discord user suggested we use a local path ("./ShadergraphFramework/") which appeared to work for them. These paths are generated by Shader Graph.

**Comment by huwb** [comment]
Oh nuts. That's dodgy! 

Guess I'll fix them up in the generated shader

**Comment by huwb** [comment]
Is the `./` at the beginning required? I tried without and it seemed to work but happy to include it if its needed

**Comment by daleeidd** [comment]
Works fine without it

**Comment by daleeidd** [comment]
Just noting here for the time being. There are still ABS paths that need fixing outside of the shader in C#. We can use GUIDs to get the path instead. Or maybe relative path. Will look later.

**Comment by MPierer** [comment]
Can confirm, works fine without "./" rel-path prefix.
Can you elaborate which ABS paths in C#?

**Comment by daleeidd** [comment]
They are only for the editor. Searching _Assets/Crest/Crest_ will show either one or two files used in the editor. Not that important really.

The fix for the shader will be out for 4.6.

**Comment by daleeidd** [comment]
4.6 is out which fixes the path issue for the shader.
