### ISSUE TITLE
Remove foam input

### ISSUE THREAD

**Issue by Kandob** [crest-ocean/crest#670]
There is a way to deposit foam onto the ocean but sometimes I would like to remove foam in shallow areas and I currently haven't found a way to do that, using a black texture instead of a white one doesn't work. Is it possible to add this feature?

**Comment by daleeidd** [comment]
Thanks. Added. Will be out in 4.7.

**Comment by Kandob** [comment]
I've tested it and it works great, thanks!

**Comment by daleeidd** [comment]
Thanks. 4.7 is out so everyone else should have it too now.
