### ISSUE TITLE
Do not cull underwater ocean tiles when underwater effect is not enabled

### ISSUE THREAD

**Issue by daleeidd** [crest-ocean/crest#672]
Requested by @olavrv

Underwater tiles should only be culled when underwater effect is used. We could do this intelligently (complicated due to multiple implementations of underwater effect) or simply add a toggle somewhere.

This sort of blurs the lines between bug report and feature request.

**Comment by daleeidd** [comment]
For those that just want to disable it as a workaround, remove the following:

```csharp
// Cull tiles the viewer cannot see through the underwater fog.
if (!isCulled)
{
    isCulled = definitelyUnderwater && (Viewpoint.position - tile.Rend.bounds.ClosestPoint(Viewpoint.position)).magnitude >= volumeExtinctionLength;
}
```

from the following file:
_/Assets/Crest/Crest/Scripts/OceanRenderer.cs_

**Comment by huwb** [comment]
Thanks, did you have a specific idea for a fancier approach?

He could set fog density to 0 on the material which would presumably achieve this effect.

**Comment by olavrv** [comment]
I got help from @daleeidd on this issue, so I am happy. He mentioned that a toggle somewhere in the editor would be nice, and that sounds great to me...

**Comment by daleeidd** [comment]
@huwb I was thinking we could only do underwater culling if underwater effect is active. Wouldn't be too difficult to do, but I wasn't in a rush to do it due to the many implementations we currently have. I was exploring a CrestCamera component to try and simplify a lot of this stuff. More details on that soon.

**Comment by huwb** [comment]
What is the use case for having underwater without fog? I believe setting the fog density to 0 is the correct solution to this.

**Comment by olavrv** [comment]
@huwb My use case is that I have made my own underwater environment - just want the ocean surface from crest. I have fog, standard unity volumetric HDRP fog..

**Comment by huwb** [comment]
So can you set the fog density to 0 on crest material, thereby removing our fog and fixing the culling issue? Sorry i must sound like a broken record :)

**Comment by olavrv** [comment]
@huwb I haven't tried that, but if that fixes culling issues, I can do that instead.

**Comment by dampete** [comment]
I added a boolean that just checks together with the specific lines daleeid mentioned. Having the density set to 0 on the material doesn't solve the problem because it's useful to be able to set that to whatever value so we can configure how far we can see under the water from above the water...

**Comment by huwb** [comment]
I'm still in the understanding phase so bare with me..

The tiles should be culled when they are no longer visible / are obscured by fog. What is the use case where you want to disable culling of tiles that should anyway be invisible?

I.e. could we see where the current tech is falling short?

**Comment by olavrv** [comment]
@huwb This is my use case: I wanted to go below the ocean surface and look up to see the underside of the water surface. I am not using any Crest underwater post effects etc. When I did this, the ocean tiles culled (many of them, not all). Explained to the best of my ability :D

**Comment by dampete** [comment]
The current way the water density works doesn't yield satisfactory visuals (at least according to what I have tried) and moreso with the default setup I can still clearly see all the underwater tiles being culled (using the Submarine scene as reference). Furthermore, to get the correct visuals for above water translucency I had to tweak the 3 density values, which messes with the average density calculation and ended up affecting the underwater visuals in unintended ways. In my current setup I have a volume for above sea level and another for below the surface.

**Comment by huwb** [comment]
Oh you're not using the underwater effect? Are you using your own fog? Or is you water completely transparent when the camera is underwater?

**Comment by dampete** [comment]
I'm currently using my own underwater effects and fog. But even when I had the default submarine example scene the underwater tiles were culling way before the fog would obscure them when I moved the camera down.

**Comment by huwb** [comment]
Culling being wrong with our underwater stuff sounds like a bug we should fix.

It sounds reasonable to use your own fogging/volume stuff, so this sounds reasonable. We could therefore add an option to disable culling. Maybe we should disable culling if the crest underwater effects are not being used. What do you think @daleeidd ?

**Comment by daleeidd** [comment]
@huwb Sounds good. I'll also investigate the culling bug.

**Comment by daleeidd** [comment]
Culling will be skipped if underwater post process is not being used. Will be out for 4.7.

**Comment by daleeidd** [comment]
4.7 is out so this one can be closed. Thank you for the help.
