### ISSUE TITLE
[URP] Any method to change the water transparency?

### ISSUE THREAD

**Issue by Lukikay** [crest-ocean/crest#682]
Hi, I'm wondering that does it possible to change ocean transparency? 

For the default setting, it's barely to see an object that 5 meters underwater. So is there any setting to change the water transparency and let it still clear, which looks like only 1 meter underwater? (URP)

Thanks.

**Comment by daleeidd** [comment]
Have you tried the depth fog density parameter on the ocean material? Read more in the second paragraph [here](https://github.com/crest-ocean/crest/blob/master/USERGUIDE.md#underwater).

**Comment by daleeidd** [comment]
I'll close this one for now since we have quite a few open issues. Reply if you need more information and I will reopen.
