### ISSUE TITLE
Buoyancy force: along water normal rather than upward

### ISSUE THREAD

**Issue by StarChick971** [crest-ocean/crest#683]
Hello,
I have been using  **_Set Water Height To Geometry_** shader which works well for a bump wave using a custom mesh.
However, when an object is floating on that bump, or any wave actually, it is not being pushed downward the wave as it could be expected. Indeed, it is only pushed upward by buoyancy whatever the slope of the wave as shown here (using _Simple Floating object_ script):
![2020-11-07_record_854x480-15h14m](https://user-images.githubusercontent.com/54045907/98467443-9b2b7800-21d5-11eb-9439-b500eded896b.gif)

Compared to **DynamicWaterPhysics2** asset, CREST lacks of a simple normal buoyancy approach, I mean pushing floating objects along the water normal and not simply upward.
Here is a short GIF below to illustrate the comparison where:
1. Sphere red: CREST's _Simple Floating object_ script
2. Sphere blue: DWP2's _Water object_ script
![2020-11-07@16h37m_record_1280x720](https://user-images.githubusercontent.com/54045907/98467005-4edf3880-21d3-11eb-9b80-6847ba499f91.gif)
The wave pushes the sphere 2 (DWP2) forward as intended.

_Remark_: Both spheres have _RigidBody_ with constrained rotations on XYZ, still red one is still rotating... ->**bug**?

Please note that the goal is **not** to have **complex** simulation as DWP2 (DWP2 calculates all forces on submerged mesh faces resulting into buoyancy force along their normals)

Last but note least, this feature could be a **toggle boolean** on the _Simple floating object script_ because any big water object (like the big ship in main demo) could be tilt by a tiny wave whereas it shouldn't.

**Comment by huwb** [comment]
Ok i've finally caved and made a PR :). #685

**Comment by StarChick971** [comment]
Great! I will test it ASAP.

**Comment by daleeidd** [comment]
Will be out for 4.7

**Comment by daleeidd** [comment]
4.7 is out so this one can be closed. Thank you for the help.
