### ISSUE TITLE
World-space UI doesn't render if "Create Shadow Data" is checked.

### ISSUE THREAD

**Issue by rvpeterson** [crest-ocean/crest#686]
**Describe the bug**
Any _Canvas_ GameObjects with _Render Mode_ set to _World Space_ don't render when _Create Shadow Data_ is checked on _Ocean Renderer_.

**Versions**

- HDRP
- Unity 2020.1.12f1
- Windows 10 pro 64-bit Build 19041

**To Reproduce**
1. Open any Crest example scene,
2. Create a Canvas object, set _Render Mode_ to _World Space_ and set size/position accordingly.
3. On the Ocean object, set _Create Shadow Data_ to true on the _Ocean Renderer_ script.
4. The Canvas will no longer render in editor or play mode.

**Platform**
 - Editor, play mode, standalone
 - Windows x86 and x86_64

**Hardware**
- Intel Core i7-4790K
- 16gb RAM
- NVIDIA GeForce GTX 970

**Comment by daleeidd** [comment]
I'll have this fixed for the next release. For now, can you try uncommented three lines at around line 50 for the _SampleShadows.cs_ file to see if it solves the problem?

**Comment by rvpeterson** [comment]
Sorry for the delay, I can confirm that uncommenting those lines fixes the problem.

**Comment by daleeidd** [comment]
Thanks. Fix will be out for Crest 4.7.

**Comment by daleeidd** [comment]
4.7 is out so this one can be closed.
