### ISSUE TITLE
Inland Crest

### ISSUE THREAD

**Issue by fikoljuky** [crest-ocean/crest#687]
Hello.

Would it be possible to add Crest inside a volume? It would be used for parts like in the picture bellow where there is a swamp/river/lake inland. It should behave like crest, and use a sepparate material from the ocean one. 

It would be a bonus if it could be moved up or down the Y axis so you could potentialy place a lake on top of a mountain and still be able to swim/dive in it. 

![unknown](https://user-images.githubusercontent.com/29865680/98683028-df00b780-2364-11eb-80e0-6091d43fc49a.png)

**Comment by daleeidd** [comment]
Thanks for opening. Please see #676 or #379 as those sound similar to what you want.
