### ISSUE TITLE
Error CS1029 on Version 2020.1

### ISSUE THREAD

**Issue by huwb** [crest-ocean/crest#690]
**Describe the bug**

I always get this error message when I start the HDR-project:

Assets/Crest/Crest/Scripts/OceanRenderer.cs(16,8): error CS1029: #error: 'This version of Crest requires Unity 2019.4 or later.‘

**Versions**
I use the current Unity version 2020.10Ob43439

**Platform**
 - Editor or standalone?
 - Platform (win/mac/...)

**Comment by huwb** [comment]
@daleeidd received this support mail. Don't really understand how this can happen. Have you encountered this?

**Comment by daleeidd** [comment]
I haven't. I have 2020.1.9 and 2020.2 beta. Is that the 2020.1 beta? Updating Unity should solve it. We did had this issue in our own code when we checked version using scripting (rather than preprocessor code) which doesn't look like is the case here.

**Comment by daleeidd** [comment]
I'll close this one for now. Reopen if you think it is still an issue or hear back from the support request.
