### ISSUE TITLE
Rendering changes near the far clip plane with transparency enabled.  This makes camera stacking troublesome.

### ISSUE THREAD

**Issue by ptarpley** [crest-ocean/crest#693]
**Describe the bug**
Rendering changes near the far clip plane with transparency enabled. This makes camera stacking troublesome

**Screenshots / video**
Far camera clip plane changing rendering: https://imgur.com/eLogEW9
![Image](https://i.imgur.com/eLogEW9.jpeg)

Seam w/stacked cameras: https://imgur.com/65VYhFf
![Image](https://i.imgur.com/65VYhFf.jpeg)

**Versions**
Built-in pipeline, running Unity 2019.4.12f1

**To Reproduce**
1. Reduce camera far clip plane, and observe that instead of just pulling in the plane, the rendering near the far clip plane changes.

**To Reproduce With Stacked Camera (intended use-case)**
1. Open whirlpool demo scene
2. Add a GameObject under the existing camera
    1. Add camera component to the new object
    2. Verify local position/rotation is 0, 0, 0
    3. Change clear flags to depth only.
    4. Change far clip plane to 20
4. Change near clip plane of original camera to 20

Run and observe that there is a visible seam due to rendering differently near the far clip plane.

**Platform**
 - Editor and standalone
 - Platform: win

**Hardware**
Nvidia GTX 1080
Intel i7-6900k

**Additional context**
We frequently have two cameras, one rending objects close to the camera, and one rendering objects far away.

**Comment by daleeidd** [comment]
I think this has to do with depth buffer issues. Two cameras writing to the same depth buffer will produce issues. More can be found here.

https://forum.unity.com/threads/multiple-cameras-near-and-far-clipping-planes.947595/

**Comment by daleeidd** [comment]
I'll close this one for now as I don't think this is something we can solve with data provided by Unity to our shader. If there is an example of a shader that uses a depth texture where this problem is addressed, or documentation that provide a solution, then please comment here.

Here is a post about the current state of this issue for URP:
https://forum.unity.com/threads/stacked-cameras-and-depth-based-post-processing.991175/

**Comment by daleeidd** [comment]
Just to add, it can work if any feature on Crest that uses the depth buffer is disabled.
