### ISSUE TITLE
Foam is not rendered at the far clip plane. This makes camera stacking troublesome.

### ISSUE THREAD

**Issue by ptarpley** [crest-ocean/crest#694]
**Describe the bug**
Foam is not rendered at the far clip plane. This makes camera stacking troublesome.

**Screenshots / video**
Far clip plane w/no foam near the end: https://imgur.com/Pc2TVvb
![Near](https://i.imgur.com/Pc2TVvb.jpeg)

Issue w/stacked cameras: https://imgur.com/HzJoQiC
![Far](https://i.imgur.com/HzJoQiC.jpeg)

**Versions**
Built-in pipeline, running Unity 2019.4.12f1

**To Reproduce**
1. Reduce camera far clip plane, and observe that instead of just pulling in the plane, the rendering near the far clip plane changes.

**To Reproduce With Stacked Camera (intended use-case)**
1. Open whirlpool demo scene
2. Add a GameObject under the existing camera
    1. Add camera component to the new object
    2. Verify local position/rotation is 0, 0, 0
    3. Change clear flags to depth only.
    4. Change far clip plane to 20
4. Change near clip plane of original camera to 20

Run and observe that there is a visible seam in the foam due to not being rendered near the far clip plane.

**Platform**
 - Editor and standalone
 - Platform: win

**Hardware**
Nvidia GTX 1080
Intel i7-6900k

**Additional context**
We frequently have two cameras, one rending objects close to the camera, and one rendering objects far away.

**Comment by daleeidd** [comment]
As a workaround, reducing the _Shoreline Foam Min Depth_ closes the gap. It uses the depth texture. It looks like there might be some compromises to make with this approach. Unless you can find a way to maintain the background texture and depth texture.

**Comment by daleeidd** [comment]
I'll close this one for now in favour of #693 since they appear to be the same issue.
