### ISSUE TITLE
Directional Light still visible when moon/sun are under horizon

### ISSUE THREAD

**Issue by gr3tchel** [crest-ocean/crest#695]
Hello, I don't know if this issue was already pointed out, but I'm having issues with Directional Light still visible when moon/sun are under horizon, as in the attached screenshot.
Is there a fix or a setting I'm missing that adjust this?
I'm using the built-in render pipeline version.

![moon](https://user-images.githubusercontent.com/15156089/99856639-af825400-2b89-11eb-981c-4644d4680b3f.png)

**Comment by daleeidd** [comment]
Thanks for opening. You will have to decrease the intensity of the sun/moon light as it sets. This is what most weather assets will do for you. I'll close this one as this isn't an issue with Crest. But I will see your replies if you need to ask something related.
