### ISSUE TITLE
UnderwaterPostProcessHDRP: _firstRenderer always on true

### ISSUE THREAD

**Issue by OkoGoran** [crest-ocean/crest#706]
I guess this is a bug. The _copyOceanMaterialParamsEachFrame is actually ignored, since _firstRenderer stays always true. 
Crest HDRP 4.6 
![image](https://user-images.githubusercontent.com/58563011/100728370-c580e780-33c7-11eb-842e-b7ccdde61c99.png)

**Comment by daleeidd** [comment]
Thank you. Fix will be out for 4.7.

Add `_firstRender = false;` at the end of the _Render_ function body to patch it for now if need be.

**Comment by daleeidd** [comment]
4.7 is out so this one can be closed. Thanks for the help.
